- .gitignore
- CONTRIBUTING.md
- LICENSE
- OWNERS
- OWNERS_ALIASES
- README.md
- RELEASE.md
- SECURITY_CONTACTS
- code-of-conduct.md
- https://github.com/kubernetes/kubernetes-template-project
> Setup controller-platform repo from the template

- pkg/admission/certprovisioner/certprovisioner.go
- pkg/admission/certprovisioner/certprovisioner_test.go
- pkg/admission/certprovisioner/doc.go
- pkg/admission/certprovisioner/selfsignedcertprovisioner.go
- pkg/admission/certprovisioner/selfsignedcertprovisioner_test.go
Move
https://github.com/kubernetes-sigs/kubebuilder/pull/243
and
https://github.com/kubernetes-sigs/kubebuilder/pull/245
Preparation for migrating https://github.com/mengqiy/WebhookCertManager/pull/1/commits/89cdb8423ff8cba4b76d62e8a271528eb3694a4c to the controller v2 lib.
> move certprovisioner pkg

- pkg/manager/internal.go
- pkg/runtime/inject/inject.go
- pkg/source/example_test.go
- pkg/source/source.go
- pkg/source/source_test.go
Address: https://github.com/kubernetes-sigs/kubebuilder/issues/254
> Implement the ChannelSource

- pkg/manager/manager_test.go
- pkg/source/source_test.go
Fix: https://github.com/kubernetes-sigs/controller-runtime/issues/24
> Get source related tests to 100% coverage

- pkg/cache/internal/informers_map.go
Most of the lister logic (both here and in Kubernetes generate listers)
assume that the namespace index is present by default, so we should
always set it up.
> Ensure that informers have the namespace index

- pkg/controller/controller.go
- pkg/internal/controller/controller.go
- pkg/internal/recorder/recorder.go
- pkg/internal/recorder/recorder_integration_test.go
- pkg/internal/recorder/recorder_suite_test.go
- pkg/internal/recorder/recorder_test.go
- pkg/manager/internal.go
- pkg/manager/manager.go
- pkg/manager/manager_test.go
- pkg/recorder/recorder.go
Address: https://github.com/kubernetes-sigs/kubebuilder/issues/255
more tests are to be added
> Implement InjectRecorder

- .gitignore
- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/informer_cache.go
The cache refactor broke the cache reader implementation (invalid
assumptions about names, arguments, and the way reflection works).
This fixes it, and adds back in some working tests to ensure that
it doesn't break again.
> Make sure cache Reader still works

- pkg/client/client.go
- pkg/client/client_cache.go
- pkg/client/client_test.go
- pkg/client/interfaces.go
This fixes the non-cache client list, which had a null pointer
dereference (opts.Namespace), incorrect resource handling (need the
resource for the items, not the list itself), and incorrect handling of
nil list options (the underlying metav1.ListOptions needs to always be
non-nil, even if empty).
> Fix non-cache client list

- pkg/cache/cache_suite_test.go
- pkg/client/client_suite_test.go
- pkg/client/config/config.go
- pkg/client/fake/client_suite_test.go
- pkg/controller/controller_suite_test.go
- pkg/envtest/crd.go
- pkg/envtest/doc.go
- pkg/envtest/envtest_suite_test.go
- pkg/envtest/envtest_test.go
- pkg/envtest/examplecrd1.yaml
- pkg/envtest/examplecrd2.yaml
- pkg/envtest/ginkgo.go
- pkg/envtest/notcrd.yaml
- pkg/envtest/server.go
- pkg/handler/eventhandler_suite_test.go
- pkg/internal/controller/controller_suite_test.go
- pkg/internal/recorder/recorder_suite_test.go
- pkg/manager/manager_suite_test.go
- pkg/predicate/predicate_suite_test.go
- pkg/runtime/inject/inject_suite_test.go
- pkg/runtime/log/log_suite_test.go
- pkg/runtime/signals/signals_suite_test.go
- pkg/source/internal/internal_suite_test.go
- pkg/source/source_suite_test.go
- also rename test package to envtest
> Support installing CRDs from yaml files in test package

- pkg/client/client_test.go
Fixes one of the commented out tests -- field selector test.
> Fixed field selector test

- pkg/admission/cert/writer/certwriter.go
- pkg/admission/cert/writer/certwriter_test.go
- pkg/admission/cert/writer/error.go
- pkg/admission/cert/writer/fs.go
- pkg/admission/cert/writer/fs_test.go
- pkg/admission/cert/writer/internal/atomic/atomic_writer.go
- pkg/admission/cert/writer/internal/atomic/atomic_writer_test.go
- pkg/admission/cert/writer/secret.go
- pkg/admission/cert/writer/secret_test.go
- test.sh
As in the commit message, the 1st commit is porting an util pkg from k/k.
> Implement fs writer

- pkg/handler/enqueue.go
- pkg/handler/enqueue_mapped.go
- pkg/handler/enqueue_owner.go
Carrying over the fix from Kubebuilder PR https://github.com/kubernetes-sigs/kubebuilder/pull/291
> use Add instead of AddRateLimited in eventhandlers

- pkg/cache/internal/informers_map.go
- pkg/controller/controller.go
- pkg/doc.go
- pkg/handler/enqueue_owner.go
- pkg/internal/controller/controller.go
https://github.com/kubernetes-sigs/controller-runtime/pull/48
> address feedback on PR 48

- pkg/patterns/application/application.go
- pkg/patterns/application/application_suite_test.go
- pkg/patterns/application/application_test.go
- pkg/patterns/application/doc.go
- pkg/patterns/application/example_test.go
- pkg/patterns/operator/doc.go
Looking to get feedback on simplifying this pattern.
> Add simple application pattern package

- pkg/predicate/predicate.go
- pkg/predicate/predicate_suite_test.go
- pkg/predicate/predicate_test.go
https://github.com/kubernetes-sigs/kubebuilder/issues/240
> Implement predicate

- Gopkg.lock
- pkg/runtime/log/log.go
- vendor/github.com/go-logr/zapr/zapr.go
fix vendor zapr, otherwise generated project will not compile due to https://github.com/go-logr/zapr/commit/7536572e8d55209135cd5e7ccf7fce43dca217ab
> fix vendor zapr

- pkg/admission/cert/writer/secret.go
- pkg/controller/controllerutil/controllerutil_test.go
- pkg/source/internal/internal_suite_test.go
test package name should be consist with https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controllerutil/controllerutil_suite_test.go#L1
Otherwise, causing issue when building with bazel.
> fix controllerutil_test

- pkg/client/config/config.go
Fix passing the kubeconfig to the client factory.
> config: fix using the KUBECONFIG to build the client

- pkg/runtime/log/log.go
- pkg/runtime/log/null.go
The null logger from logr is in the same package as the testing logger,
which means it accidentally adds testing flags to all binaries that
import it.  Copy the null logger into the pkg/runtime/log package
to avoid this.
> Avoid adding test flags when using the null logger

- Gopkg.toml
It's not directly used by anything, and the transitive deps should pull
in the proper version if needed.
Partial fix for #89
> Remove kube-aggregator from Gopkg.toml

- pkg/cache/cache.go
- pkg/manager/manager.go
Allows setting the resync interval to something besides the default of 10 hours for all informers managed by the cache.
I'm not sure how to test this, because the resync interval seems to be irretrievable from the cache or its informers.
Fixes #87.
> Add a resync option to manager options

- pkg/controller/controllerutil/controllerutil.go
- pkg/controller/controllerutil/controllerutil_test.go
> Fix duplicate controller references

- pkg/internal/controller/controller.go
Currently errors returned by reconcilers are discarded from logs. This PR surfaces them.
> Surface reconcile error in logs

- OWNERS_ALIASES
The OWNERS_ALIASES needs aliases as map keys, not as list items.
> Update OWNERS_ALIASES to fix approver bot

- pkg/manager/manager.go
Removes the advice about when to change, since sync period is more subtle than can be explained in a comment. Replaces it with a warning to know what you're doing before changing it.
Followup from the conversation with @DirectXMan12 in #88.
> Clarify SyncPeriod comment

- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/fake/client.go
- pkg/client/interfaces.go
- pkg/client/split.go
- pkg/manager/manager.go
Sending this (WIP) PR for an early feedback on the interface before I add tests.
> client: update status subresource support

- pkg/envtest/ginkgo.go
- pkg/envtest/printer/ginkgo.go
- pkg/envtest/server.go
- pkg/runtime/log/log_suite_test.go
This allows you to use an external cluster with envtest.  In the
case where `UseExistingCluster` is set to true, envtest will skip
initializing the control plane, and if config is not otherwise set,
it will populate the config from local kubeconfigs or in-cluster config.
> External clusters in envtest

- pkg/webhook/admission/admission_suite_test.go
- pkg/webhook/admission/decode_test.go
- pkg/webhook/admission/http.go
- pkg/webhook/admission/http_test.go
- pkg/webhook/admission/response.go
- pkg/webhook/admission/response_test.go
- pkg/webhook/admission/webhook.go
- pkg/webhook/admission/webhook_test.go
Fix several nil pointer issues when testing the unhappy path in the unit test.
> add tests for webhook/admission pkg

- hack/verify.sh
This PR fixes an failing linter check due to renaming.
> gas linter renamed to gosec

- CONTRIBUTING.md
- README.md
1. More detailed test steps
1. The solution to issues which I have encountered.
Thanks for review.
> improve contributing guide

- pkg/controller/controllerutil/controllerutil.go
- pkg/controller/controllerutil/controllerutil_suite_test.go
- pkg/controller/controllerutil/controllerutil_test.go
- pkg/controller/controllerutil/example_test.go
> Add CreateOrUpdate utility method

- pkg/admission/cert/writer/internal/atomic/atomic_writer_test.go
- pkg/internal/controller/controller.go
- pkg/internal/controller/controller_test.go
- pkg/reconcile/reconcile.go
This is a requirement for migrating cluster-api to controller-runtime.
> Support delaying requeue for objectkey.

- hack/verify.sh
gosec complains when we load from a file path which is a variable. Example error message:
```
pkg/envtest/crd.go:204::warning: Potential file inclusion via variable,MEDIUM,HIGH (gosec)
``` 
One possible way to make it work is ignoring this kind of error by running `gosec` as a custom linter and exclude G304 errors.
> skip gosec linting for now

- example/main.go
- example/mutatingwebhook.go
- example/validatingwebhook.go
- pkg/manager/internal.go
- pkg/manager/manager.go
- pkg/runtime/inject/inject.go
- pkg/webhook/admission/builder/builder.go
- pkg/webhook/admission/decode.go
- pkg/webhook/admission/decode_test.go
- pkg/webhook/admission/http.go
- pkg/webhook/admission/http_test.go
- pkg/webhook/admission/response.go
- pkg/webhook/admission/response_test.go
- pkg/webhook/admission/types/types.go
- pkg/webhook/admission/webhook.go
- pkg/webhook/admission/webhook_test.go
- pkg/webhook/server.go
inject client and decoder for webhook server and underlying webhook handlers
> inject client and decoder for webhook

- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/fake/client.go
- pkg/client/interfaces.go
Allows Delete requests to carry options like GracePeriodSeconds, Preconditions, and PropagationPolicy. I chose the functional options pattern here so the function signature remains the same for all existing callsites.
To use the default options, call Delete with the same signature as before:
```go
client.Delete(context.TODO(), obj)
```
This Delete call sets a GracePeriodSeconds for the request:
```go
client.Delete(context.TODO(), obj, client.GracePeriodSeconds(1))
```
Multiple options can be set:
```go
client.Delete(context.TODO(), obj,
client.GracePeriodSeconds(1),
client.PropagationPolicy(metav1.DeletePropagationForeground))
```
I wrote tests for the DeleteOptions struct, but I wasn't sure how to test the actual request content. With the current testing strategy, we can only test …
> Add options to client.Delete()

- pkg/builder/example_test.go
- pkg/cache/cache_test.go
- pkg/cache/informer_cache.go
- pkg/cache/informertest/fake_cache.go
- pkg/cache/internal/cache_reader.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
- pkg/client/interfaces.go
- pkg/webhook/internal/cert/writer/secret_test.go
Replaces:
`List(ctx, ListOptions, list)`
with:
`List(ctx, list, ...Option)`
This matches the functional options signature of `client.Delete` in #94.
A few examples (I tried formatting these as a table but it wasn't wide enough):
Select all:
```go
// current
List(ctx, nil, list)
// proposed
List(ctx, list)
```
Filter by namespace:
```go
// current
List(ctx, client.InNamespace(ns), list)
// proposed
List(ctx, list, client.InNamespace(ns))
```
Filter by namespace and labels:
```go
// current
List(ctx, client.InNamespace(ns).MatchingLabels(labels), list)
// proposed
List(ctx, list, client.InNamespace(ns), client.MatchingLabels(labels))
```
To assemble a `ListOptions` with the builder methods or some other strategy, use the `UseListOptions` functional option:
```go
lo := &client.ListOptions{} …
```
> Convert client.List to use functional options

- pkg/webhook/bootstrap.go
- pkg/webhook/internal/cert/provisioner.go
- pkg/webhook/internal/cert/provisioner_test.go
- pkg/webhook/internal/cert/writer/fs.go
- pkg/webhook/util.go
fix issues when using fs cert writer (the default one is secret writer):
- non-443 port support in URL mode
- ensure not port is in host name when gen the cert
> fix issues when running on master

- pkg/builder/example_test.go
- pkg/cache/cache_test.go
- pkg/cache/informer_cache.go
- pkg/cache/informertest/fake_cache.go
- pkg/cache/internal/cache_reader.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
- pkg/client/interfaces.go
- pkg/webhook/internal/cert/writer/secret_test.go
Reverts kubernetes-sigs/controller-runtime#106
#106 is a breaking change to the client interface.
Per suggestion from @pwittrock, we are going to revert it for now before we make a decision about how to deal with it.
We can decide later if we want to [introduce the new signature as a new method and mark the old one as deprecated](https://github.com/kubernetes-sigs/controller-runtime/pull/106) or do a `v0.2.0` release for it.
> Revert "Convert client.List to use functional options"

- pkg/webhook/server.go
With this change, users can register arbitrary http.Handler in Server, e.g. `/version` endpoint with a handler, `/metrics` with a Prometheus handler or other monitoring system.
> support register arbitrary http.Handler in Server

- pkg/cache/cache_test.go
- pkg/cache/informer_cache.go
- pkg/cache/internal/deleg_map.go
- pkg/cache/internal/informers_map.go
- pkg/client/apiutil/apimachinery.go
- pkg/client/client.go
- pkg/client/client_cache.go
- pkg/client/client_test.go
- pkg/client/split.go
- pkg/client/typed_client.go
- pkg/client/unstructured_client.go
- pkg/manager/manager.go
Attempt to fix #17 and I think it also addresses #33 
/cc @DirectXMan12 @pwittrock can you PTAL and let me know if I am even on the right track?
> Adding ability for clients, cache and watcher to work with unstructured

- pkg/cache/internal/informers_map.go
I'm building a controller using the package and have been running my tests using `ginkgo -race`, I came across this race condition which led me to a small fix.
```
WARNING: DATA RACE
Write at 0x00c000e65440 by goroutine 23:
runtime.mapassign()
/usr/local/Cellar/go/1.11/libexec/src/runtime/map.go:549 +0x0
github.com/pusher/faros/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal.(*specificInformersMap).Get.func2()
/Users/joel/go/src/github.com/pusher/faros/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:180 +0x456
github.com/pusher/faros/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal.(*specificInformersMap).Get()
/Users/joel/go/src/github.com/pusher/faros/vendor/sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:190 +0x161 …
```
> Use read mutex when iterating over informers map

- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/internal/deleg_map.go
- pkg/cache/internal/informers_map.go
- pkg/manager/manager.go
Fixes #124 
A namespace option can be passed from the manager to the cache which restricts the ListWatch for all informers to the desired namespace. 
This way a manager can be run with a Role instead of a ClusterRole.
> Option to restrict informer cache to a namespace

- pkg/client/typed_client.go
This change passes the context in the client methods to the underlying
object requests created using client-go's Request for `typedClient`.
Context isn't passed to the `unstructuredClient` because the
`dynamicResourceClient` in client-go doesn't accepts any context.
Fixes #40
> pkg/client: Pass ctx to typedClient requests

- Gopkg.lock
- pkg/source/source.go
Fix: kubernetes-sigs/kubebuilder#337
New output:
```
$ make run
go generate ./pkg/... ./cmd/...
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...
go run ./cmd/manager/main.go
2018/08/31 10:40:04 Registering Components.
2018/08/31 10:40:04 must install CRD {core.hawq.org MyResource} before calling Start
exit status 1
make: *** [run] Error 1
```
Thanks for the review.
>  Prompt to install CRD when Kind no found

- pkg/source/source.go
This will set the `String` method for the sources to fix #153
> Adding string methods for the sources.

- pkg/envtest/server.go
This allows configuring the start and stop timeouts for the controlplane. I've created this PR after repeated test failures in the kubernetes-sigs/cluster-api repo due to `timeout waiting for process kube-apiserver to start`, e.G. in https://github.com/kubernetes-sigs/cluster-api/pull/523
> Make start and stop timeouts for test controlplane configurable

- pkg/manager/internal.go
It always gets called as a goroutine, so nothing expects it to block. This
change slightly simplifies the code and lets the goroutine die instead of
keeping it around forever.
> lets controllerManager.start() return instead of blocking

- pkg/manager/internal.go
Following discussion and comments from @droot in #163, I've refactored the leader election and controller manager `Start` to make it a little easier to read and remove the double `select` blocks that I had added.
I've also taken the liberty of removing the leader electors stop channel from the equation, we don't particularly need it and this should make it easier to upgrade in the future (client-go 9 has a different signature for `OnStartedLeading`).
> Refactor leader election in manager.Start

- pkg/envtest/server.go
Fix an issue that cause kubebuilder CI to fail
E.g. failure https://travis-ci.org/kubernetes-sigs/kubebuilder/builds/446423305?utm_source=github_status&utm_medium=notification
Default the timeout to 20s per https://github.com/kubernetes-sigs/controller-runtime/blob/dd4e86a3b40fd6b437992bbf4021e23f8b8a2528/pkg/envtest/server.go#L91
> fix testenv

- example/main.go
- pkg/webhook/bootstrap.go
- pkg/webhook/server.go
This PR changes an option introduced in #174.
We always install webhook config prior v0.1.5 releases.
We introduced an option `InstallWebhookConfig` recently and was released on Oct 25 in v0.1.5.
If `InstallWebhookConfig` is not an pointer, it will be defaulted to `false` by golang.
That means existing user who are upgrading from previous controller-runtime version will be break, because they expect webhook config installer to be on.
> Rename InstallWebhookConfig and change it to a pointer

- pkg/internal/controller/controller.go
This enables controller to be able to create new watches after it has started.
This is required for cases where you are writing some meta-controller
which discovers new types to watch during the reconcilation.
> do not hold the lock after controller has started

- pkg/internal/controller/metrics/metrics.go
Enabled Prometheus collector for process metrics and Go runtime
> added process metrics and Go runtime metrics

- pkg/envtest/server.go
This change exports DefaultKubeAPIServerFlags, allowing a user to
append the default flags with other custom flags and set it to
Environment.KubeAPIServerFlags.
If KubeAPIServerFlags is not set, DefaultKubeAPIServerFlags is used when
the API server starts.
Fixes #112
> envtest: export DefaultKubeAPIServerFlags & make flags configurable

- pkg/doc.go
- pkg/envtest/server.go
- pkg/webhook/internal/cert/provisioner.go
> Cleanup duplicated words

- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
Adds a `NewFakeClientWithScheme` function that takes a `*runtime.Scheme` as its first argument. `NewFakeClient` is now a wrapper around `NewFakeClientWithScheme`, passing it the default `scheme.Scheme`.
Fixes #137.
> Add scheme support to fake client

- pkg/webhook/internal/cert/writer/secret_test.go
Now that #213 is in, these tests can be updated to use typed lists instead of `corev1.List`. I find the tests are clearer without the use of `Raw` hacks.
@mengqiy I'm assuming the use of `corev1.List` and JSON marshaling was a workaround for the issue with the fake client fixed in #213, but I could be wrong about that. You can decide what style you prefer. :smile:
> Use typed lists in cert writer tests

- README.md
- VERSIONING.md
This is mostly a proposal at this point.  I've started to outline the branch strategy we've loosely discussed in the past, with some motivations and discussion of alternatives.
> :book: Versioning and Branching Strategy

- .github/PULL_REQUEST_TEMPLATE/breaking_change.md
- .github/PULL_REQUEST_TEMPLATE/bug_fix.md
- .github/PULL_REQUEST_TEMPLATE/compat_feature.md
- .github/PULL_REQUEST_TEMPLATE/docs.md
- .github/PULL_REQUEST_TEMPLATE/other.md
- VERSIONING.md
This introduces PR templates for each of the different types of changes (as per [the versioning document](VERSIONING.md)).  It also fixes and clarifies the aforementioned versioning document (around build steps and separately tagged commits).
> :running: PR Templates

- .github/PULL_REQUEST_TEMPLATE/breaking_change.md
- .github/PULL_REQUEST_TEMPLATE/bug_fix.md
- .github/PULL_REQUEST_TEMPLATE/compat_feature.md
- .github/PULL_REQUEST_TEMPLATE/docs.md
- .github/PULL_REQUEST_TEMPLATE/other.md
- .github/pull_request_template.md
- README.md
The template picker only works for issues, but you can still have
multiple PR templates that can be used with a query parameter, but
that's kind-of unweildy.  We'll have the default PR template, and keep
the separate ones around linked-to from the readme as examples.
> :running: Add default PR template

- pkg/source/source.go
Fix: https://github.com/kubernetes-sigs/controller-runtime/issues/187
> :bug: fix incorrect logr usage

- pkg/manager/internal.go
Fixes #196.
Move metrics serving to before we separate into the leader election vs non leader election start process.
This allows prometheus to count non-leader targets as up, but will just receive an empty response for non-leaders and so no inaccurate metrics are collected.
> :bug: Serve metrics even if not leader

- pkg/metrics/listener.go
The PR flips the default of the unreleased metrics feature.
The reason is that we spin up a controller-manager in each of our controller's unit test, e.g. https://github.com/kubernetes-sigs/kubebuilder/blob/master/test/project/pkg/controller/firstmate/firstmate_controller_test.go
When there are multiple controllers in the same project, they will race for binding to the same default port which will cause some of them failing.
The plan is that in v0.1 branch we leave it off by default and in v0.2 release (happening very soon) we flip the default to on.
> :sparkles: change metrics default to off

- pkg/internal/controller/controller.go
The previous implementation lacked delayed execution, leading to
`end - now` not reflecting the duration of the reconcile request handling.
> :bug: Fix reconcile duration metric

- pkg/webhook/bootstrap.go
This feature is useful for webhook to not block themselves.
The following scenario can be problematic: a webhook intercepts all pod creation requests. The user brings down the webhook server (maybe a statefulSet or deployment) and leave the webhook configuration object in the APIServer. The user recreates the webhook server (maybe a statefulSet or deployment), the workload API (statefulSet or deployment) will try to create new pods. This operations will be blocked by failing to call the webhook.
> :sparkles: default namespace selector for webhook

- pkg/internal/controller/controller.go
- pkg/internal/controller/controller_test.go
- pkg/internal/controller/metrics/metrics.go
This PR adds a new metric 'reconciles_total' to track total reconciles per controller. 
Note: yet to add tests for it, sending in for early feedback.
> :sparkles: added reconciles_total metric

- example/main.go
- pkg/webhook/admission/http.go
- pkg/webhook/admission/http_test.go
- pkg/webhook/admission/webhook.go
- pkg/webhook/admission/webhook_test.go
- pkg/webhook/internal/metrics/metrics.go
Add 2 metrics for webhook:
- Number of total requests
- Latency of processing admission requests
> :sparkles: add metrics for webhooks

- pkg/manager/manager.go
- pkg/manager/manager_test.go
* Allow the user to specify in the options how to create the client,
cache, and how to construct the delegating client.
fixes #226
> :sparkles: Allow user to define how create managed objects

- pkg/webhook/bootstrap.go
> :bug: fix `nil` error when using `BootstrapOptions.Host`

- pkg/envtest/crd.go
- pkg/envtest/server.go
There was a minor style violation in the style of error reporting in envtest, plus envtest lacked logging entirely.  This fixes both of those issues.
> :sparkles: Fix up error reporting and logging in envtest

- Gopkg.lock
- pkg/internal/controller/controller.go
- pkg/internal/controller/controller_test.go
- pkg/internal/controller/metrics/metrics.go
- pkg/metrics/client_go_adapter.go
- pkg/source/source_integration_test.go
This exposes the client-go metrics (client, workqueue, reflector)
metrics in the controller-runtime registry.
It also fixes a typo in the tests, and fixes our Gopkg.toml to prune some unnecessary requires (since I had to do a `dep ensure` anyway, and it was taking forever without the changes).
> :sparkles: Expose client-go metrics

- pkg/builder/example_test.go
- pkg/cache/cache_test.go
- pkg/cache/informer_cache.go
- pkg/cache/informertest/fake_cache.go
- pkg/cache/internal/cache_reader.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/example_test.go
- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
- pkg/client/interfaces.go
- pkg/client/split.go
- pkg/client/typed_client.go
- pkg/client/unstructured_client.go
- pkg/webhook/internal/cert/writer/secret_test.go
Replaces:
`List(ctx, ListOptions, list)`
with:
`List(ctx, list, ...Option)`
This matches the functional options signature of `client.Delete` in #94.
A few examples (I tried formatting these as a table but it wasn't wide enough):
Select all:
```go
// current
List(ctx, nil, list)
// proposed
List(ctx, list)
```
Filter by namespace:
```go
// current
List(ctx, client.InNamespace(ns), list)
// proposed
List(ctx, list, client.InNamespace(ns))
```
Filter by namespace and labels:
```go
// current
List(ctx, client.InNamespace(ns).MatchingLabels(labels), list)
// proposed
List(ctx, list, client.InNamespace(ns), client.MatchingLabels(labels))
```
To assemble a `ListOptions` with the builder methods or some other strategy, use the `UseListOptions` functional option:
```go
lo := &client.ListOptions{} …
```
> :warning: Convert client.List to use functional options

- Gopkg.lock
- pkg/handler/enqueue_owner.go
- pkg/handler/eventhandler_suite_test.go
- pkg/handler/eventhandler_test.go
- pkg/manager/internal.go
- pkg/runtime/inject/inject.go
Determines if the owner object is cluster scoped, and if it is will not use the object's namespace in the reconcile request.
To complete this, it adds dependency injection for the managers RESTMapper.
> :bug: EnqueueRequestForOwner correctly enqueue cluster-scoped owner

- Gopkg.lock
- pkg/webhook/server.go
- pkg/webhook/server_test.go
- pkg/webhook/webhook_suite_test.go
fixes #191 
fixes #192
Tests are on the way.
> :bug: fix issue when webhook server refreshing cert

- pkg/webhook/webhook_suite_test.go
This fixes the tests so that the build can pass.
> :bug: update call to ZapLoggerTo after refactor

- pkg/client/config/config.go
Renames master to controlplane as discussed in the [Jan 31st steering meeting](https://docs.google.com/document/d/1qazwMIHGeF3iUh5xMJIJ6PDr-S3bNkT8tNLRkSiOkOU/edit#)
Related: https://github.com/kubernetes/website/issues/6525
> :sparkles: Master -> Control Plane

- pkg/cache/internal/cache_reader.go
- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
- pkg/internal/objectutil/filter.go
This commit allows passing label matches to the fake client `List()` function. 
This feature was not working properly before (no filters applied at all).
This is done in a way similar to the `CachedReader`. Both now share a common call to `listutil.FilterWithLabels`.
One thing worth discussing:
I wasn't sure where to extract this common function in the package hierarchy. Keeping it in `cache/internal` does not work since the fake client cannot use a package named `internal`. Looking at other packages I could not find the right place for it.
Hence the new `cache/listutil` package. It still feels a bit wrong, suggestions for a new location are very welcome!
Partial fix for #293.
> :bug: fix labels list option in fake client

- pkg/log/zap/zap.go
> :sparkles: Add zap.RawLoggerTo which returns a configured zap logger

- pkg/webhook/server.go
**Update**: Since this PR was originally made, the ability to configure the webhook server host was removed from master. Rather than fixing a bug, this PR now introduces a new minor, non-breaking feature.
I would still like to see this merged if possible, as it's handy for integration testing using the webhook server on developer machines that are (perhaps a little overzealously) configured with a firewall to loudly complain if new server processes begin listening on non-loopback interfaces.
~~The webhook server can be configured with a host to bind to, defaulting to all IPs (empty string) if not set. This was not actually used.~~
> :bug: Webhook server uses its configured host if set

- pkg/builder/build.go
When use builder pkg to construct a controller, if a config is provided, we should use it.
If a config is not provided by the user, we should try to use manager's config.
If manager is not specified, we should then try to use [GetConfig()](https://github.com/kubernetes-sigs/controller-runtime/blob/c84fba842c566876050ccfea7fe9f33d870fb451/pkg/client/config/config.go#L60-L82).
> :bug: try manager's config before kubeconfig

- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/informer_cache.go
- pkg/cache/informertest/fake_cache.go
- pkg/cache/multi_namespace_cache.go
- pkg/manager/example_test.go
- pkg/manager/manager.go
This will add the ability to set up a multi-namespace cache. This also has a backward incompatible change in the `Informers` interface which effects the `cache` interface. 
This is based on the discussion from the BoF.
/cc @DirectXMan12 @mhrivnak @hasbro17 
Wanted to get some early feedback before starting on tests.
> :warning: adding multi namespaces cache

- pkg/controller/controllerutil/controllerutil.go
- pkg/controller/controllerutil/controllerutil_test.go
- pkg/controller/controllerutil/example_test.go
#313 breaks `CreateOrUpdate` by not calling the `MutateFn` when new objects are created. This patch fixes that and updates the tests to better reflect the expected behavior.
> :warning: Call MutateFn on CreateOrUpdate regardless of the operation

- pkg/controller/controller.go
- pkg/source/internal/eventsource.go
Fix some typos in comment.
- iff -> if
- remove unnecessary "and"
> :bug: Fix typos in comment

- pkg/envtest/server.go
- pkg/webhook/webhook_suite_test.go
This squashes some remaining references to runtime/log, which would have
forced pulling in Zap.
> :bug: Squash some remaining references to runtime/log

- Gopkg.lock
- Gopkg.toml
- vendor/k8s.io/api/core/v1/generated.proto
- vendor/k8s.io/api/core/v1/types.go
- vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
- vendor/k8s.io/apimachinery/pkg/api/errors/errors.go
- vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
- vendor/k8s.io/apimachinery/pkg/runtime/codec.go
- vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go
- vendor/k8s.io/client-go/transport/token_source.go
It is in the best interests of any k8s API consumer that we always vendor in the latest patch release of a minor version.
As controller-runtime acts as the primary source of k8s-dependencies for cluster-API and its providers, best practices mandate that we update the versions at the root so that they percolate down to the Cluster API providers. If this change is not accepted, we would be forced to use override deps.
>  ✨ update kubernetes 1.13 to the latest patch release

- pkg/manager/internal.go
- pkg/manager/manager.go
- pkg/manager/manager_test.go
- pkg/runtime/inject/inject.go
- pkg/runtime/inject/inject_test.go
Adding the APIReader onto the manager and allowing users to use dependency injection to add this to their types.
> :sparkles: adding APIReader to the manager and injection.

- pkg/builder/build.go
It's convention in the Go community that a function's deprecation notice
is separated by a new paragraph from the function's documentation. Tools
like staticcheck determine if a function has been deprecated by checking
the beginning of new paragraphs.
This changelist modifies the deprecation notices in the builder package
to follow this convention, allowing linters like staticcheck,
gometalinter, and golangci-lint to warn users of the package.
> :book: improve builder deprecation messages

- pkg/builder/build.go
- pkg/builder/build_test.go
- pkg/builder/builder_suite_test.go
- pkg/manager/manager_test.go
- pkg/webhook/admission/decode_test.go
- pkg/webhook/server.go
Followup PR per https://github.com/kubernetes-sigs/controller-runtime/pull/328#issuecomment-471138778
> :running: add tests for simplified webhook interface

- hack/check-everything.sh
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
- pkg/client/interfaces.go
- pkg/client/typed_client.go
- pkg/client/unstructured_client.go
This PR adds `CreateOptions` and `UpdateOptions` to the `Client` package to allow client users to set the `DryRun` option when creating and updating resources using the client. This should allow users to see the result of all Admission controllers before persisting changes.
I've attempted to match the patterns in `DeleteOptions` and `ListOptions` as much as possible but since the only valid value for `DryRun` is `all` (see [here](https://github.com/kubernetes/apimachinery/blob/dcb391cde5ca0298013d43336817d20b74650702/pkg/apis/meta/v1/types.go#L501-L507)) I've not made that configurable, but it could be easily changed. I've also had to name the two `OptionFuncs` `CreateDryRunAll` and `UpdateDryRunAll` which I don't particularly like, has anyway any better ideas for names for these?
> :warning: Add Server-Side DryRun support to Client

- Gopkg.lock
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
- pkg/client/interfaces.go
- pkg/client/patch.go
- pkg/client/typed_client.go
- pkg/client/unstructured_client.go
This adds the `Patch` method to the `Client` interface as well as to the two implementations (`typedClient`, `unstructuredClient`).
> ⚠️ Implement Patch method

- pkg/client/config/config.go
- pkg/envtest/server.go
The default QPS on REST clients is 5 (with burst to 10), which is rather slow.  This is especially true when running a test server, since you want to run tests pretty quickly, and the test cluster is default.
For normal clients, we probably want to default to what the KCM defaults to (our situation isn't quite the same, since we actually share the client across controllers, so we should follow up dealing with that at some point).  This gives us 20 QPS with burst to 30.
> :sparkles: Default QPS to a saner value in and out of tests

- pkg/client/fake/client.go
Changes proposed in this pull request:
- Really simple fix for used scheme in fake client in `List` method. 
**Background**
This bug https://github.com/kubernetes-sigs/controller-runtime/issues/137 was already fixed by this PR: https://github.com/kubernetes-sigs/controller-runtime/pull/213. Unfortunately in this [PR](https://github.com/kubernetes-sigs/controller-runtime/pull/294/files#diff-62fbcb10a0dc0bc5b0a1bba07b8eefb0R92) the bug was reintroduced - probably by mistake.
**NOTE:** 
I also tried to change the tests to never regress but such action will complicate the test suite, so IMO is really not worth to do that. But if you think that tests coverage should be added then let's decide which `types` should be used and how the test suite should look like, e.g. full tests …
> 🐛Fix used scheme for fake client in List method

- README.md
This PR fixes a dead link to examples in README.md.
/fix #361
> :book: Fix a dead link to examples

- pkg/source/source.go
Before fc804a41 (#267), the `cache.Informers` interface methods returned
`k8s.io/client-go/tools/cache.SharedIndexInformer`s which were by default
compatible with the built-in `source.Informer`. Users could create arbitrary
`cache.Cache` instances (or get them from the `Manager`) and then use
`controller.Watch` to drive a controller with a `source.Informer` from the
`cache.Cache`.
With fc804a41, the `cache.Informers` interface was changed to return
`cache.Informer` instances; however, `source.Informer` was not updated to accept
a `cache.Informer`, and so users can no longer use the built-in
`source.Informer` with `cache.Cache`.
The `cache.Informer` interface appears to satisfy the needs of
`source.Informer`. This commit broadens `source.Informer` to accept a
`cache.Informer`, restoring …
> :warning: source: make the Informer source compatible with cache.Informer

- pkg/client/fake/client.go
User code may use this fake client in tests without setting up logging, making errors here extremely difficult to track down. Panic logs more reliably with better debugging details.
I didn't change any of the other `os.Exit(1)` calls, since they're in CR's own tests. I'd love to know why the tests don't use panic generally. Is it to eliminate the option to recover?
> :bug: Panic instead of Exit in FakeClient

- pkg/internal/controller/controller.go
[This check](https://github.com/kubernetes-sigs/controller-runtime/blob/e4c40bc20113bec130047ba0a42cec39ca0d6476/pkg/internal/controller/controller.go#L202) covers the case obj equals nil.
> :bug: Remove redundant check

- pkg/cache/internal/informers_map.go
`specificInformersMap.Get` may accidentally return an unsynced `Informer` (contained in the returned `MapEntry`). The condition occurs when 2 callers concurrently call `Get` for the same GVK after the `specificInformersMap` has been started. The first won't find the GVK in the cache. It will add it and wait for the informer to sync. The second will find it in the cache and erroneously return it before it syncs.This patch guarantees that all returned informers are synced by checking before return.
> :bug: Ensure returned informers are always correctly synced

- pkg/client/apiutil/apimachinery.go
The Kubernetes client allows for users to configure a serializer which
is used to encode and decode resources exchanged with the Kubernetes API
server.
This changeset modifies the controller-runtime client to only set the
default serializer if the NegotiatedSerializer option is nil.
Signed-off-by: Terin Stock <terin@cloudflare.com>
> :sparkles: support custom negotiated serializer :bug:

- pkg/log/deleg.go
I was attempting to [add some logging](https://github.com/pusher/faros/pull/114) to our project Faros, but we run our tests with the `-race` flag and the tests failed while detecting a race in controller-runtime ([logs here](https://prow.pusher.com/view/gcs/pusher-ci-cluster-35535/pr-logs/pull/pusher_faros/114/pull-faros-test-ginkgo/1112733698010124288)).
I then created this branch, added a [commit](https://github.com/pusher/faros/pull/114/commits/db9851c02320c2fc7c7c7e50aca7f7ad2aab2333) to test the fix for the race and [my tests all passed](https://prow.pusher.com/view/gcs/pusher-ci-cluster-35535/pr-logs/pull/pusher_faros/114/pull-faros-test-ginkgo/1112736340442615808) 😄
>  🐛 Add mutex to loggerPromise to prevent races

- pkg/webhook/server.go
Add back support for serving HTTP2 from the webhook server.
Fixes #408
> Add back http2 support :bug:

- pkg/builder/build_test.go
- pkg/webhook/admission/response.go
- pkg/webhook/admission/response_test.go
In ValidationResponse, use 200 if allowed, otherwise use 403 (Forbidden).
> :sparkles: use more reasonable status code for ValidationResponse

- Gopkg.lock
- pkg/envtest/crd.go
- pkg/envtest/envtest_test.go
- pkg/envtest/multiplecrds.yaml
Updated`envtests` to support loading multiple CRDs from single file
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/369
> ✨ envtest can load multiple CRDs from single file

- hack/check-everything.sh
Update bash scripts to install gometalinter.v2 and dep if they are missing and SKIP_FETCH_TOOLS is false. This allows installation of the tools in docker containers in Prow.
> 🏃 task: enable running tests in prow

- pkg/cache/internal/cache_reader.go
- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
- pkg/internal/objectutil/filter.go
This commit allows passing label matches to the fake client List()
function.
This is done in a way similar to the CachedReader. Both now share a
common call to `objectutil.FilterWithLabels`.
Signed-off-by: sebgl <contact.sebgl@gmail.com>
Backporting https://github.com/kubernetes-sigs/controller-runtime/pull/311 into release-0.1 branch.
> :bug: Enable labels list options in fake client

- pkg/internal/controller/controller.go
- pkg/internal/controller/controller_test.go
This PR fixes #392. Reset the failure count if `return result.Result{RequeueAfter: resyncPeriod}, nil` is returned by the reconcile loop.
> :bug: Reset Failure count for reconcile loops using RequestAfter

- pkg/webhook/conversion/conversion_test.go
This PR fixes expect statements in the conversion tests to be more idiomatic.
> :running: fix expect statement in conversion tests to be idiomatic

- pkg/client/typed_client.go
Currently the typedClient.List call passes in the serialized object in the body of the HTTP request. This is unnecessary and should not be done. This PR makes it so that body is not passed in the HTTP request.
@DirectXMan12
cc @ilkercelikyilmaz
> :bug: List requests should not pass a body.

- pkg/webhook/server.go
This PR is reverting the change in https://github.com/kubernetes-sigs/controller-runtime/commit/ad30658629f706b1ac24f52eee6f861179111f79#diff-fbc18bb07cdd05391b7081acc1dfe170R81
Allowing port 0 doesn't actually provide much values when doing testing, since user will need to run some command e.g. `netstat` to figure which port is assigned. And it also make defaulting port hard.
This change is not a breaking change since https://github.com/kubernetes-sigs/controller-runtime/commit/ad30658629f706b1ac24f52eee6f861179111f79#diff-fbc18bb07cdd05391b7081acc1dfe170R81 has not been released in a stable release yet.
In term of testing, we could use `addr.Suggest()` to get an available port and then use it in testing.
> :sparkles: stop allowing port 0

- pkg/cache/cache_test.go
- pkg/cache/internal/cache_reader.go
Fixes #284. Populates GroupVersionKind for objects returned by the List method.
This supersedes #296. I've rebased the branch, fixed up the conflicts and found an issue where we seemed to not be deepcopying items out of the cache before returning.
I've maintained @liyinan926's ownership of the commits so they should still be credited for their work.
/CC @DirectXMan12
> :bug: Populate GVK for listed objects

- examples/conversion/pkg/apis/jobs/v1/register.go
- examples/conversion/pkg/apis/jobs/v2/register.go
- pkg/builder/build.go
- pkg/manager/internal.go
- pkg/webhook/conversion/conversion.go
- pkg/webhook/conversion/conversion_test.go
This PR enables conversion webhook by default.
It also logs a warning at startup if a type is a multi-version and doesn't implement conversion. Users will get a false-positive if they build a controller for non-managed multi-version types. Looking for ideas to handle it better.
> :sparkles: enable conversion webhook by default

- example_test.go
- pkg/manager/internal.go
- pkg/manager/manager.go
> Make leader election lease duration configurable through manager options

- examples/crd/pkg/groupversion_info.go
- examples/crd/pkg/resource.go
- pkg/manager/internal.go
- pkg/manager/manager.go
- pkg/manager/manager_test.go
controller manager support 2 set of runables
- one set is managed by leader election. i.e. only one replica running.
- one set is not managed by leader election. i.e. always running.
> support HA (non leader election) components

- pkg/handler/enqueue_mapped.go
Previously, we weren't injecting dependencies into the Mapper in the
enqueue-mapped handler.  This makes more complicated to things that
require clients, etc.
> :bug: Ensure that enqueuemapped's mapper gets deps

- pkg/client/client_test.go
- pkg/client/interfaces.go
implement `IgnoreNotFound` that ignores `NotFound` errors
create test cases
Fixes #357 
This allows to easily ignore `NotFound` errors which is often required in case where it's just necessary to see that a resource is gone.
> ✨ Implement `IgnoreNotFound`

- Gopkg.lock
- pkg/webhook/internal/certwatcher/certwatcher.go
- pkg/webhook/server.go
This watches the configured TLS certificate and key files for admission webhooks.  On any change, it attempts to reload them from disk.
Fixes: #390
> ✨ webhook: Handle TLS certificate rotation

- pkg/webhook/server.go
webhook server should not use leader election by default.
Ref: https://github.com/kubernetes-sigs/controller-runtime/pull/424
> :sparkles: webhook server doesn't use leader election by default

- examples/builtins/main.go
- pkg/controller/controller.go
- pkg/doc.go
- pkg/handler/doc.go
Someone erroneously performed a global case-insensitive
s/Reconcile/Reconciler/g, which resulted in bad docs statements such as
"Setup a new controller to _Reconciler_ ReplicaSets" and "Reconciler is
called to _Reconciler_ an object by Namespace/Name", which should
obviously be "Setup a new controller to _reconcile_ ReplicaSets"
and "Reconciler is called to _reconcile_ an object..."
> 📖 Fix docs & comments referring to "Reconciler" instead of "reconcile"

- pkg/webhook/conversion/conversion.go
- pkg/webhook/conversion/conversion_test.go
We need to set "success" status in conversion response when we successfully convert the object.
kube-apiserver rejects it if the status is not set.
> :bug: set status in conversion response

- pkg/internal/controller/controller.go
update internal controller process loop, this also fix #440
> :bug: update internal controller for more clean code and metrics

- pkg/envtest/server.go
support setting "UseExistingCluster" via OS Env, address #222
> :sparkles: Allow setting "UseExistingCluster" via environment

- pkg/builder/build.go
This switches the default controller name in the builder to just
lower(<kind>) which fixes any issues that arrise from it showing up in
the deprecated metrics (which use the workqueue name as part of the
metric name).
It also allows overriding name in case of two controllers reconciling
the same type using the builder.
> :sparkles: Allow setting controller name, fix default

- hack/release/common.sh
- hack/release/release-notes.sh
This supports generating release notes when we cross "major" version
boundaries and need to create a new release branch.
> :running: support release notes on new version

- pkg/envtest/server.go
Support bridging the control plane output to the stdout and stderr
> :sparkles: more visibility of the testing control plane

- VERSIONING.md
- hack/release/common.sh
- hack/release/release-notes.sh
fixes #433
I was thinking using `:see_no_evil:` :see_no_evil:, but I feel the wording `evil` may be offending. So this PR stay with `:ghost:` :ghost:.
> :running: use :ghost: for no release note commits

- Gopkg.lock
- Gopkg.toml
- vendor/k8s.io/api/core/v1/generated.proto
- vendor/k8s.io/api/core/v1/types.go
- vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
- vendor/k8s.io/apimachinery/pkg/api/errors/errors.go
- vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
- vendor/k8s.io/apimachinery/pkg/runtime/codec.go
- vendor/k8s.io/apimachinery/pkg/runtime/serializer/streaming/streaming.go
- vendor/k8s.io/client-go/transport/token_source.go
This PR updates this repository's dependencies to `1.13.4`, this is mainly to match `controller-tools` latest release, which is already at this version.
> :sparkles: Update Kubernetes to 1.13.4 [release-0.1]

- .github/main.workflow
- hack/release/Dockerfile
- hack/release/common.sh
- hack/release/verify-emoji.sh
This introduces a GitHub action that verifies emoji.  We could move this
to prow, but in the mean time, it can live here.
It's a bit wonky b/c PRs show up oddly in GH actions for security reasons, but basically, we receive the PR request, figure out the actual head commit, and add a check status depending on if the emoji is ok
> :running: Verify Emoji with GH actions

- pkg/manager/internal.go
- pkg/manager/manager_test.go
In `controllerManager`, `startLeaderElectionRunnables` doesn't protect its read of `leaderElectionRunnables` and write of `started`. This may cause a Runnable to be run twice:
- `startNonLeaderElectionRunnables` sets `started` to true
- `Add` appends the runnable to `leaderElectionRunnables`, sees that that `started` is true, and starts the runnable
- `startLeaderElectionRunnables` starts all of the runnables in `leaderElectionRunnables`
See https://travis-ci.org/kubernetes-sigs/controller-runtime/jobs/541066866 for an example.
> 🐛 Fix runnable race in manager

- pkg/metrics/client_go_adapter.go
- pkg/metrics/workqueue.go
Migration work was already done to move controller-runtime from k8s v1.13 to v1.14, however this introduced certain issues.
Unfortunately, workqueue_queue_duration_seconds and workqueue_work_duration_seconds were included in v0.1.10, but were recorded with microsecond values. Moving to k8s v1.14 corrects those values to seconds.
Primarily this change removes the metrics that were deprecated in k8s v1.14, but were never previously included in v0.1 of controller-runtime and thereby fixes #436.
The one metric that was deprecated and retained is longest_running_processor_microseconds, as it was included in v0.1.10.
> 🐛 remove deprecated workqueue metrics with invalid names

- pkg/manager/internal.go
Closing of internalStop channel should be propagated to a context that is passed to leaderelector.Run.
> 🐛Pass appropriate context to leaderelector.Run

- examples/builtins/main.go
- examples/builtins/mutatingwebhook.go
- examples/builtins/validatingwebhook.go
- examples/crd/pkg/resource.go
- go.mod
- make it more consistent with the CRD example
- add missing markers for webhook
- also go modules want to add `fsnotify` in go.mod.
> :book: minor updates to the examples

- pkg/builder/build.go
- pkg/builder/build_test.go
If a kind has implemented Defaulter and(or) Validator interface(s),
multiple controllers for this kind should be able to be added to the
same controller manager.
fixes #483
> :bug: stop registering webhooks with same path when adding multiple controllers

- pkg/runtime/scheme/scheme.go
pkg/runtime/scheme was supposed to maintain a type alias to make it
easier for people to upgrade and/or interact with projects written
around older versions, but apparently, I forgot to actually leave the
type alias around.  This fixes that.
> :sparkles: Fix runtime/scheme type aliases

- alias.go
- examples/crd/main.go
- go.sum
- pkg/builder/controller.go
- pkg/builder/controller_test.go
- pkg/builder/example_webhook_test.go
- pkg/builder/webhook.go
- pkg/builder/webhook_test.go
`build.go`=> `controller.go` + `webhook.go`
`build_test.go`=> `controller_test.go` + `webhook_test.go`
TODO: figure out if `For` method in webhook builder should be variadic?
> :warning: split the webhook builder out as a separate builder.

- .gitignore
- pkg/client/client_test.go
- pkg/client/options.go
> ✨ Fix typo

- pkg/manager/internal.go
fix #478 @DirectXMan12 @abursavich ptal
> :bug: fix runnable run twice issue

- Gopkg.lock
- pkg/client/config/config.go
This PR adds a new function to the config package. Before it was only possible to retrieve the current context of a kubeconfig file via `GetConfig`. Now there's an additional `GetConfigWithContext` where a specific context can be retrieved. 
The advantage is when developing locally (run controllers via IDE) with a specified context, the controller is not dependent on whatever the current context is of the used kubeconfig file.
Fixes #479
> :sparkles: add GetConfigWithContext to retrieve a config with a specific context

- pkg/webhook/conversion/conversion.go
- pkg/webhook/conversion/conversion_test.go
IsConvertible used to use obj.GetObjectKind().GroupVersionKind() to get
GVK which will not work if apiVersion and kind fields are not set. Now
it uses scheme.ObjectKinds(obj).
> :bug: IsConvertible should not error on uninitialized struct.

- examples/builtins/main.go
Remove unused disableWebhookConfigInstaller flag in the builtins example.
Related to #300.
> :bug: Remove unused disableWebhookConfigInstaller flag

- FAQ.md
- TMP-LOGGING.md
- VERSIONING.md
- doc.go
- examples/builtins/controller.go
- pkg/builder/builder_suite_test.go
- pkg/builder/webhook.go
- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/internal/cache_reader.go
- pkg/client/client.go
- pkg/client/example_test.go
- pkg/client/patch.go
- pkg/controller/controllerutil/controllerutil_test.go
- pkg/leaderelection/leader_election.go
- pkg/manager/manager.go
- pkg/metrics/client_go_adapter.go
- pkg/runtime/inject/inject_test.go
- pkg/runtime/log/log.go
- pkg/webhook/admission/webhook_test.go
- pkg/webhook/internal/certwatcher/certwatcher.go
This fixes various typos in the codebase, comments, and log messages
> :running: fix various typos

- pkg/manager/manager.go
While the concrete Options struct documents delegating behavior, and the
main overview documents it as well, this adds a note to `manager#GetClient`
that it may return a non-live client, just to avoid confusion.
For reference, it's also documented @ https://godoc.org/sigs.k8s.io/controller-runtime#hdr-Clients_and_Caches and https://godoc.org/sigs.k8s.io/controller-runtime/pkg/manager#Options, but it may not always be obvious that you need to look in either of those places.
We don't concretely say what the client will be, since it's an interface, just that it *may* be non-direct.  Concrete documentation is left to the referenced Options func.
> :book: Note on Manager#GetClient about delegating clients

- pkg/webhook/admission/decode.go
When user tries to decode an object, it should always not be empty. This
error gives people hints when they running into this kind of issues. e.g.
kube-apiserver doesn't include the object in the admission review for
deletion events.
We needs this before landing https://github.com/kubernetes-sigs/controller-runtime/pull/525
> :sparkles: decoder now errors out when encountering an empty runtime.RawExtension

- examples/crd/pkg/resource.go
- pkg/builder/webhook.go
- pkg/builder/webhook_test.go
- pkg/webhook/admission/validator.go
- Currently validator interface supports create and update
- Add support for delete as well, which could be a breaking change
- Users need to implement ValidateDelete since interface is updated
> :warning: support delete validation in validator interface

- pkg/webhook/server.go
We now use https://golang.org/pkg/os/#TempDir to get the os specific
temp dir. Otherwise, it won't work for Windows users.
We also switch to use the os-aware `Join` method.
> :bug: stop using hardcoded temp dir

- pkg/cache/informer_cache.go
- pkg/cache/informertest/fake_cache.go
- pkg/cache/internal/cache_reader.go
- pkg/cache/multi_namespace_cache.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/doc.go
- pkg/client/fake/client.go
- pkg/client/interfaces.go
- pkg/client/options.go
- pkg/client/split.go
- pkg/client/typed_client.go
- pkg/client/unstructured_client.go
This switches over our functional options to actually be interfaced-based.  Practically, this feels incredibly similar for users, to the point where I expect nobody will have to change their code (with the exception of Preconditions, which was a pointer).
The upsides are slightly more ergonomic options in some cases (like `client.MatchingLabels{"foo": "bar"}` instead of needing `client.MatchingLabels(map[string]string{"foo": "bar"})`, although the latter still works), as well as the removal of the need for separate variants for options that apply across different operations.
Technically, this is a breaking change, since there are type signature changes.
Fixes #503 (see that issue for more details)
> :warning: Functional Options Redux

- pkg/controller/controllerutil/controllerutil.go
fix grammer of error in SetControllerReference
> 🐛 fix grammer of error in SetControllerReference

- pkg/envtest/crd.go
Logging the whole CRD resource is incredibly verbose as it includes every description of every field in the OpenAPI schema.
> :running: Only log CRD name during installation

- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/example_test.go
- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
- pkg/client/interfaces.go
- pkg/client/options.go
- pkg/client/typed_client.go
- pkg/client/unstructured_client.go
implement `CollectionOptions` in `DeleteOptions` that allow to issue a
`DeleteCollection` call under the hood
add tests + examples
Co-Authored-By: Aaron Clawson <Aaron.Clawson@gmail.com>
Edited By directxman12: function naming, rebase
> ✨ Implement delete collection via delete options

- pkg/client/client.go
- pkg/client/client_test.go
> :bug: Preserve GroupVersionKind during Update/Patch

- pkg/builder/controller.go
- pkg/builder/controller_test.go
- pkg/builder/webhook.go
- pkg/builder/webhook_test.go
- pkg/patterns/application/doc.go
Allow reconcilers to add watches dynamically by getting a handle to the controller created by the builder via `Build` (changes the signature of `Build`).
Fixes #540
> :warning: Allow reconcilers to add watches dynamically

- pkg/builder/controller.go
- pkg/builder/controller_test.go
Fixes: https://github.com/kubernetes-sigs/controller-runtime/issues/317
- Currently there is no way to override MaxConcurrentReconciles using builder
- Provide a method to override controller options
- Another approach was to provide MaxConcurrentReconciles itself, but it isnt future proof incase additional options are added
> :bug: surface controller options when using builder

- pkg/webhook/admission/http.go
- pkg/webhook/admission/http_test.go
- pkg/webhook/admission/webhook.go
Rather than synthesizing a fresh `context.Context` for each admission Webhook request, instead pass through a `Context` obtained from the original `http.Request` passed in to the `http.Handler`. This way, we can wrap middleware `http.Handler`s around the `webhook.Admission` handlers, such as those that establish tracing spans, instrumentation, or logging context, and have our `admission.Handler`s continue to use that same context.
Note that if an `http.Request` had no `Context` bound explicitly with `http.WithContext`, [the `Request.Context` method returns `context.Background`](https://golang.org/src/net/http/request.go?s=12215:12258#L339).
> :sparkles: Pass HTTP request Context through to admission Webhook handlers

- hack/check-everything.sh
Currently this is used to determine if `golangci-lint` and `dep` are installed. This fixes the bash syntax to correctly determine if its installed. So locally and in CI the tools will not be reinstalled every time
As you can see in [the build](https://travis-ci.org/kubernetes-sigs/controller-runtime/jobs/562844729#L525) dep is properly now detected
Additionally I've noticed in both [the contributing docs](https://github.com/kubernetes-sigs/controller-runtime/blob/72ab3feaa306ee16af7aa2bd9a6b916b042bffd3/CONTRIBUTING.md#test-locally) and in [CI](https://github.com/kubernetes-sigs/controller-runtime/blob/72ab3feaa306ee16af7aa2bd9a6b916b042bffd3/.travis.yml#L21) these tools are installed outside of this script anyways though, and don't exactly align everywhere
> :running: Properly check if binary exists

- pkg/builder/controller_test.go
Replace SimpleController with ControllerManagedBy.
HEAD is broken, because 2 independent PRs merged w/o 2nd run of the tests.
Ref: https://github.com/kubernetes-sigs/controller-runtime/pull/520/files#diff-6f42001696c3446318d286d877537c05R133 and https://github.com/kubernetes-sigs/controller-runtime/pull/542/files#diff-df5180876f8262addc299c5c76c39542L56
> :bug: fix SimpleController in builder test

- pkg/runtime/log/log.go
In `runtime/log` we have 2 variables [`ZapLogger`](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/runtime/log/log.go#L35) and [`ZapLoggerTo`](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/runtime/log/log.go#L40). 
They both point to the same function `zap.Logger`. In case of  `ZapLoggerTo` it probably should point to `zap.LoggerTo`.
Fixes #558
> ✨ ZapLoggerTo points to zap.LoggerTo

- pkg/predicate/predicate.go
- pkg/predicate/predicate_test.go
Adds a `GenerationChangedPredicate` predicate similar to the `ResourceVersionChangedPredicate` that will filter out update events if an object's `metadata.generation` is unchanged.
This predicate is needed since the CRD status subresource is more commonly enabled now which allows users to filter out updates that have no spec changes.
Since this is a common ask, this predicate is better suited as a helper in the predicate library rather than having users write it themselves or being somewhere [downstream in the operator-sdk](https://github.com/operator-framework/operator-sdk/blob/6c7039c373244e8e485edd447adbf6b86bffeda6/pkg/predicate/predicate.go).
**Side note:** For CRD objects the Generation increment is skipped on metatdata updates as expected. But this behavior isn't consistent for …
> ✨ Add predicate for Generation change on update event

- pkg/doc.go
- pkg/handler/eventhandler.go
The implementations of `EventHandler` are
- `EnqueueRequestForObject`
- `EnqueueRequestForOwner`
- `EnqueueRequestsFromMapFunc`
The first two are singular `Request`, the last one is plural `Requests`.
This PR fixes the docs in a couple places to use the correct plural form.
> :book: fix spelling of function EnqueueRequestsFromMapFunc

- pkg/doc.go
> :book: Update example dir in godoc

- hack/ci-check-everything.sh
This PR adds a script to run tests in Prow. Done to resolve #276
> :running: Add script to run tests in Prow

- go.mod
- go.sum
:bug:
ref https://github.com/googleapis/gnostic/issues/147 and https://github.com/kubernetes-sigs/controller-runtime/issues/583
People cannot patch upgrade controller-runtime without this change, because https://proxy.golang.org/github.com/googleapis/gnostic/@v/list reports a zombie v0.2.1 release
> :bug: Minor upgrade of gnostic to v0.3.1

- pkg/client/options.go
`MatchingSelector` provides the full [`fields.Selector`](https://godoc.org/k8s.io/apimachinery/pkg/fields#Selector) API for listing/deleting resources. See #576 for more details.
Closes #576
> :sparkles: pkg/client/options.go: MatchingSelector can add a fields.Selector to ListOptions

- pkg/internal/recorder/recorder.go
- pkg/internal/recorder/recorder_test.go
- pkg/manager/manager.go
- pkg/manager/manager_test.go
A less-invasive alternative to #587. Lets the user optionally specify their own EventBroadcaster, which allows specifying options for event distribution
> :sparkles: Let users specify their own EventBroadcaster for the manager

- Gopkg.lock
- pkg/client/options.go
- pkg/client/options_test.go
Currently setting multiple `ListOption`s is pretty annoying, because it is not defined as a function but as an interface, which can not be defined inline.
This PR extends the existing `ListOptions` struct to implement the `ListOption` interface to allow using it as a `ListOption`.
If anyhow possible, I'd be super, super glad if we could get this into the `release-0.2` branch as well :grimacing: 
/assign @DirectXMan12
> :sparkles: Client option types implement client option interfaces

- pkg/manager/internal.go
- pkg/manager/manager.go
add webhook certDir args. 
fixes #568
> should support webhook certDir args

- hack/release/release-notes.sh
This makes the release notes script tolerant of manual merges, which
helps when calculating the release notes before doing the GitHub branch
merge.
> :running: Make the release notes script tolerant of merges

- pkg/builder/builder_suite_test.go
- pkg/envtest/crd.go
- pkg/envtest/envtest_test.go
- pkg/envtest/helper.go
- pkg/envtest/server.go
This change provides better control for installing CRDs in `envtest`.
Fixes #541
> :sparkles: Expose CRDInstallOptions via envtest.Environment

- pkg/client/client_test.go
- pkg/client/options.go
> ✨ Add Limit and Continue functional list options for client

- pkg/client/options.go
- pkg/client/options_test.go
Limit and continue support for ListOptions were recently added, but it
was missing in ApplyToList method.
> 🐛 Set limit and continue in ApplyToList method

- go.mod
- pkg/cache/internal/cache_reader.go
`CacheReader.List` method creates deep copies of objects retrieved from the index and then passes them on to `objectutil.FilterWithLabels` which again deep copies objects matching the label selector. This PR inlines the label filtering logic to avoid the double deep copy.
Fixes #621
> :sparkles: Avoid extra deep copy in CacheReader.List

- pkg/client/apiutil/apimachinery.go
Fix https://github.com/kubernetes-sigs/controller-runtime/issues/613
>  🐛Prevent NewDiscoveryRESTMapper from panicking by calling NewDiscoveryClientForConfig

- pkg/cache/informer_cache.go
- pkg/cache/internal/cache_reader.go
- pkg/cache/internal/deleg_map.go
- pkg/cache/internal/informers_map.go
- pkg/controller/controller_integration_test.go
Makes the cache return a distinct error when trying to read from it without having started it first.
Fixes #623
> :bug: Return error when trying to read from an unstarted cache

- go.mod
- go.sum
- hack/test-all.sh
- pkg/cache/cache_test.go
- pkg/client/apiutil/apiutil_suite_test.go
- pkg/client/apiutil/dynamicrestmapper.go
- pkg/client/apiutil/dynamicrestmapper_test.go
- pkg/internal/controller/controller_test.go
- pkg/manager/manager.go
- pkg/manager/manager_test.go
- pkg/reconcile/reconciletest/reconcile.go
- pkg/source/source_integration_test.go
pkg/client/apiutil: `DynamicRESTMapper` will reload the delegated `meta.RESTMapper` on a cache miss. API calls are rate-limited by a [token bucket](https://en.wikipedia.org/wiki/Token_bucket), and will return an `ErrRateLimited` containing a `time.Duration` signifying a wait time.
See https://github.com/operator-framework/operator-sdk/pull/1329 for a discussion of why reloading on a cache miss is desirable.
**Discussion points:**
- Any API changes needed.
- How we want to rate limit, and what we want UX to look like.
- Changes needed in other packages.
Closes #321 
/cc @DirectXMan12 @mengqiy @joelanford @hasbro17
> :warning: DynamicRESTMapper that reloads on REST cache miss

- hack/release/release-notes.sh
A merge commit has snuck into our history, so we need to tolerate it
when running the release notes script :-(.
> :running: Tolerate merge commits in the release notes script

- pkg/manager/manager.go
The DynamicRESTMapper PR accidentally set lazy discovery by default.  To
avoid causing confusion, I think we should stick with eager discovery by
default, at least for now.
> :ghost: Don't do lazy discovery by default

- pkg/healthz/doc.go
- pkg/healthz/healthz.go
- pkg/healthz/healthz_suite_test.go
- pkg/healthz/healthz_test.go
- pkg/manager/internal.go
- pkg/manager/manager.go
- pkg/manager/manager_test.go
Attempt to solve https://github.com/kubernetes-sigs/controller-runtime/issues/297.  Adds server, that can serve readiness and liveness probes. Probes return response based on manager's fields `isReady` and `isAlive`, that can be changed via methods `SetReady`/`SetAlive`
> ✨ added health probes

- pkg/log/zap/zap.go
This adds helpers for common Zap options, so that users don't have to
write them themselves.
It also fixes the Deprecation warnings to use the standard syntax, and
fixes the options godocs to follow proper godocs format.
> :sparkles: Add helpers for common Zap options

- pkg/controller/controllerutil/controllerutil.go
- pkg/controller/controllerutil/controllerutil_test.go
https://github.com/kubernetes-sigs/controller-runtime/issues/485
I don't have a particular preference between the runtime.Object and metav1.Object in the signature. I see both reasons from the linked issue as valid. Figured i'd open as such and ask for feedback.
> ✨ implement helpers for add/remove finalizer

- pkg/webhook/admission/http.go
- pkg/webhook/admission/http_test.go
- pkg/webhook/admission/webhook_test.go
- pkg/webhook/server.go
I have added more logs at places where it deems necessary. If you guys have any good ideas, please let me know!
Issue: https://github.com/kubernetes-sigs/controller-runtime/issues/340
> ✨ Improve webhook loggings

- pkg/builder/controller_test.go
- pkg/controller/controller.go
- pkg/internal/controller/controller.go
- pkg/internal/controller/controller_test.go
- pkg/manager/internal.go
- pkg/manager/manager.go
- pkg/manager/manager_test.go
This prevents a couple of goroutine leaks related to the controller and manager logic.
The first is in controller: `controller.New` previously created a new workqueue, which launched goroutines expecting to be stopped with `Shutdown`.  This is semi-unexpected in CR, since we generally state that things don't happen until Start is called (and, indeed, we don't call shutdown unless start is called).  This means that calling `controller.New` without ever starting the controller will cause a goroutine leak.  We fix this by delaying workqueue initialization (and consequently source starting) until the controller's Start is called.
The second is in the manager's handling of errors -- we used to use an error channel to report errors from internal goroutines and runnables.  However, we only ever …
> :bug: prevent controller.New and manager's errChan from leaking goroutines

- pkg/client/config/config.go
- pkg/client/config/config_suite_test.go
- pkg/client/config/config_test.go
This PR adds support in `pkg/client/config.GetConfig()` and `pkg/client/config.GetConfigWithContext()` to handle multi-value KUBECONFIG environment variable values, as documented in the [docs about kubeconfig](https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/#set-the-kubeconfig-environment-variable).
It also adds unit tests, which test config loading for the kubeconfig flag, environment variable, and default home directory location. In-cluster configurations are not tested because they require files to exist in hard-coded file system locations.
Closes #564
> :sparkles: Add support for multi-value KUBECONFIG

- pkg/log/zap/zap.go
- pkg/log/zap/zap_test.go
This PR fixes a bug where `func UseDevMode(enabled bool)` always sets the `Development` option to `true`, regardless of the value of `enabled`.
This PR also adds tests for the `New()` function and the `Opts`-related functions.
> :bug: pkg/log/zap: use enabled in UseDevMode, add tests

- pkg/envtest/server.go
Allows envtest based tests to run offline.
Fixes: #669
> :bug: Allow kube-apiserver to start without a default route

- go.mod
- go.sum
Update to latest testing_frameworks, for better handling of API server startup errors.
* go get sigs.k8s.io/testing_frameworks@v0.1.2
* go mod tidy
> ✨ Update sigs.k8s.io/testing_frameworks to v0.1.2

- pkg/envtest/server.go
This is part of https://github.com/kubernetes-sigs/kubebuilder/issues/1000 and a followup to the work in https://github.com/kubernetes-sigs/kubebuilder/pull/1055.
Adds information on envtest environment variables to the GoDoc.
/kind documentation
> 📖 Document environment variables supported by envtest

- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
In a real system, the ResourceVersion of a resource will be incremented whenever it is written to. To allow tests to rely on this, fakeClient should do the same.
> ✨ fakeClient: bump ResourceVersion on write

- pkg/log/zap/zap.go
This PR adds predefined functional options for more easily setting the logger options in `pkg/log/zap`.
Follow up to #560 per https://github.com/kubernetes-sigs/controller-runtime/pull/560#discussion_r317664717
/cc @DirectXMan12 @alvaroaleman
> ✨ Add helpers for remaining Zap options

- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
- pkg/client/fake/doc.go
Set Kind correctly for unstructured objects 
```
unmarshalerDecoder: Object 'Kind' is missing in '{\"metadata\":{},\"items\":[{\"kind\":\"Deployment\",\"metadata\":{\"name\":\"test-deployment\",\"namespace\":\"ns1\",\"creationTimestamp\":null},\"spec\":{\"selector\":null,\"template\":{\"metadata\":{\"creationTimestamp\":null},\"spec\":{\"containers\":null}},\"strategy\":{}},\"status\":{}},{\"kind\":\"Deployment\",\"metadata\":{\"name\":\"test-deployment-2\",\"namespace\":\"ns1\",\"creationTimestamp\":null,\"labels\":{\"test-label\":\"label-value\"}},\"spec\":{\"selector\":null,\"template\":{\"metadata\":{\"creationTimestamp\":null},\"spec\":{\"containers\":null}},\"strategy\":{}},\"status\":{}}]}', error found in #10 byte of ...|tus\":{}}]}|..., bigger context …
```
> :sparkles:handle unstructured objects correctly in fake client

- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
This is a followup PR of #682.
After examining https://github.com/kubernetes/kubernetes/pull/70087, it seems to be safer to also add APIVersion
> :ghost:add apiversion handling to fake client

- pkg/client/example_test.go
`name` and `namespace` should go into the metadata of the `unstructured.Unstructured` object.
> 🐛 Fix delete example not setting metadata properly for CRDs

- pkg/controller/controllerutil/controllerutil.go
- pkg/controller/controllerutil/controllerutil_test.go
Based on https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents, cross-namespace owner references are disallowed by design. The `SetControllerReference()` should prevent owner reference from setting on dependents in different namespace.
> 🐛 cross-namespace owner references should be disallowed

- pkg/cache/informer_cache.go
- pkg/cache/informer_cache_test.go
This PR makes the `informerCache` implement the `LeaderElectionRunnable` interface to signal that it doesn't need leader election. This is done so other `runnables` that also do not need leader election can use the cache-backed reader.
Fixes #677
> :bug: InformerCache: Do not require leader lease

- pkg/envtest/server.go
fix #641 
service-cluster-ip-range is no longer going to be defaulted after 1.16, so if user not set service-cluster-ip-range, add default value(10.0.0.0/24) to envtest set
> :sparkles: envtest set service-cluster-ip-range if user not set

- go.mod
This soft-bumps to Go 1.13.  Mandatory Go 1.13 changes may follow in
future point releases (e.g. #606).
> :warning: Soft-bump to Go 1.13

- pkg/cache/multi_namespace_cache.go
- Make clear that scenario as "watch all less one namespace" are not recommended for it and recommend the ideal solution for this scenario.
- Make clear that it may face performance issues if your api-server is super flooded or you are watching like 10000 namespaces
**Motivation**
Closes: https://github.com/operator-framework/operator-sdk/issues/2008
> 📖: improve MultiNamespacedCacheBuilder info

- pkg/webhook/server.go
The provisioners were removed in #300 so this docs are no longer relevant.
> 📖 Remove obsolete cert provisioner docs

- CONTRIBUTING.md
- Makefile
- hack/check-everything.sh
- hack/ci-check-everything.sh
**Description of the change:**
- Install golangci-lint via curl as recommended by its docs. See: https://github.com/golangci/golangci-lint#go-get
- Add Makefile and create a target to check all.
> :running: Change the golint install to do it as recommended

- pkg/controller/controllerutil/controllerutil.go
plucking some low hanging fruit
fixes #464
>  🐛 use semantic equality in CreateOrUpdate

- pkg/controller/controllerutil/controllerutil.go
- pkg/controller/controllerutil/controllerutil_test.go
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/699.
An error was returned by the call to `SetControllerReference` if the owner
is already set, but with a different apiVersion (eg. `group/v1beta1`
instead of `group/v1`).
This commit fixes it by ignoring the version in the ref comparison. It
still considers the group though. Having an owner with a different
version does not return an error, but the call to
`SetControllerReference` effectively changes the owner to match the
newer apiVersion.
> :bug: Fix SetControllerReference to consider multiple CRD versions

- pkg/envtest/server.go
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
Fixes #691 by setting the `Environment` CRDs field to contain all installed CRDs whether provided as CRD object types or by path.
> ✨ envtest: surface merged crds

- pkg/cache/cache.go
- pkg/cache/internal/informers_map.go
- pkg/manager/manager.go
all informers use the same resync period, this may cause multi controllers send list requests to apiserver simultaneously, add a jitter to resync period would be better.
fixes #648 
this pr uses `ResyncPeriod ` to add a jitter to the `SyncPeriod` option before finally pass to the `NewInformer` func
> :sparkles: add 10% jitter to ResyncPeriod

- pkg/envtest/crd.go
- pkg/envtest/envtest_test.go
- pkg/envtest/server.go
But only if `USE_EXISTING_CLUSTER` is set to `true` as there's no point in doing it if the control-plane is going away.
Fixes #420
> :sparkles: Clean-up installed CRDs on Stop()

- pkg/webhook/internal/metrics/metrics.go
This PR is for the issue #712 TotalRequests prometheus metrics is not getting used and hence it is removed in this PR.
Fixes #712
> :bug: Remove TotalRequests Prometheus metrics as it is not getting used

- pkg/envtest/crd.go
- pkg/envtest/envtest_test.go
- pkg/envtest/helper.go
This PR enables the usage of files path on CRDInstallOptions.Paths, allowing users to register only a single CRD or an entire directory.
Next step is to bring this to Environment (maybe CRDFilePaths?).
Starts to fix #394
> :sparkles: CRD file path on CRDInstallOptions.Paths

- pkg/envtest/envtest_test.go
- pkg/envtest/server.go
This PR overwrites the ErrorIfPathMissing from CRDInstallOptions via Environment.ErrorIfCRDPathMissing on Start() method.
Similar to PR #511 but propagates the flag and test the Start() with invalid directories.
Closes #481.
> :sparkles: ErrorIfCRDPathMissing on Environment

- pkg/metrics/registry.go
It's currently not possible to replace the predefined Registry with a custom implementation.
I need this because I re-create controllers with the same name at runtime and this causes the default registry to rightfully complain that the metrics for this label combination are already registered. When calling `controller.New()` I have no influence over the metrics creation and errors are always logged with a logger I can also not control.
With this PR I can register my own Registry implementation that silently drops the AlreadyRegistered errors.
We could have used a custom subset of the two predefined Registerer/Gatherer interfaces, but both are so short and only contain what we actually need, so it seemed not worth the effort to replicate the method definitions.
I can see that there are …
> ✨ Define metrics.Registry as an interface

- pkg/controller/controller_integration_test.go
- pkg/envtest/server.go
Currently it is not possible to use envtest to create things with privileged containers in them, because the `--allow-privileged` flag on the kube-apiserver defaults to false. Attempting to do so causes a `Deployment.apps \"deployment-name\" is invalid: spec.template.spec.containers[0].securityContext.privileged: Forbidden: disallowed by cluster policy"`.
This PR changes that.
> :bug: Envtest: Allow creating objects with privileged container specs

- Makefile
- TMP-LOGGING.md
- VERSIONING.md
- pkg/doc.go
Fixes grammar and spelling typos in various places (non-functional changes, not code)
> 📖 (nit) fix grammar and spelling typos

- pkg/client/client.go
Resolves https://github.com/kubernetes-sigs/controller-runtime/issues/734
This commit changes the client package to use the dynamic RESTMapper by
default.
The default RESTMapper caches the discovery endpoint results once and
never updates them.
Because of that, if an api-resource is added after the client is
started, the client will mistakenly think the api-resource doesn't exist.
Signed-off-by: Yannis Zarkadas <yanniszark@arrikto.com>
> :sparkles: client: Use dynamic RESTMapper by default

- pkg/builder/example_test.go
The `ExampleBuilder` uses the default logger, which is the `NullLogger`.  Since this example is (I assume) meant as a comprehensive example, it would be more helpful to print the actual logs.  This PR replaces the default null logger with a zap logger in the example.
> 📖Replace NullLogger with a zap logger in the ExampleBuilder

- pkg/envtest/envtest_test.go
- pkg/envtest/testdata/crds/examplecrd3.yaml
Another folder inside testdata with the CRD file to avoid working with the ones still being deleted.
This fixes the flake test.
> :running: Adding another folder with the CRD avoiding late deleted conflicts

- pkg/cache/cache_test.go
- pkg/client/client_test.go
- pkg/client/example_test.go
- pkg/client/options.go
Replaces usage of deprecated `MatchingField` list option in tests with
`MatchingFields`.
> :running: Remove usage of deprecated MatchingField list option

- pkg/client/client_test.go
- pkg/client/fake/client_test.go
- pkg/client/patch.go
Adds a new patch type called `Merge` for simple patch operations and renames `ConstantPatch` in favor of `RawPatch` (new name). Motivation and discussion can be found in the related issue.
Closes #665
> :sparkles: Add Merge patch type and deprecate ConstantPatch in favor of RawPatch

- pkg/controller/controllerutil/controllerutil.go
I was reading the godoc and noticed that the actual argument didn't match the godoc:
> SetControllerReference sets owner as a Controller OwnerReference on **owned**. This is used for garbage collection of the **owned** object and for reconciling the owner object on changes to **owned** (with a Watch + EnqueueRequestForOwner). Since only one OwnerReference can be a controller, it returns an error if there is another OwnerReference with Controller flag set.
> 📖 Rename "object" to "owned" to match godoc comment.

- pkg/manager/manager.go
- pkg/webhook/server.go
Document the expected names of TLS key and certificate so that users don't have dig through code to discover it.
> 📖 docs: document the expected names of the TLS key and certificate

- pkg/envtest/crd.go
- pkg/envtest/envtest_test.go
- pkg/envtest/testdata/crdv1_original/example_multiversion_crd1.yaml
- pkg/envtest/testdata/crdv1_updated/example_multiversion_crd1_one_more_version.yaml
In testenv, update the CRD if it's already present on the cluster instead of failing to continue.
Fixes #342
Closes #457
> :sparkles: update CRD if already present

- pkg/cache/internal/deleg_map.go
- pkg/cache/internal/informers_map.go
There is currently an unintuitive race condition between starting
a cache, waiting for it to sync, and using it the first time.
The crux of the problem is that WaitForCacheSync can return true
BEFORE the Start function has had a chance to set started to true.
This means that Get and List can return ErrCacheNotStarted even
after WaitForCacheSync has returned true.
This commit adds a channel and a wait function that is called from
WaitForCacheSync to ensure that started has been set to true before
returning.
> :bug: wait for cache start before returning from WaitForCacheSync

- pkg/internal/testing/integration/assets/bin/.gitkeep
- pkg/internal/testing/integration/doc.go
When bringing in the testing framework in #749 download-binaries.sh was not moved over but the references to it remain in the docs. This PR removes them.
>  📖 (:book:, docs) Remove references to 'download-binaries.sh'

- pkg/webhook/server.go
A user may want to use different names for server key/cert, for
example, if it's using the client-go cert manager util, the
certificate is just a unify pem file with both on it.
> :sparkles: Parameterize webhook key/cert name

- pkg/builder/controller.go
Error fix: 
`Builder.Owns()` is equivalent to calling: 
`Watches(&source.Kind{Type: <ForType-apiType>}, &handler.EnqueueRequestForOwner{OwnerType: apiType, IsController: true})`, 
not: 
`Watches(&handler.EnqueueRequestForOwner{&source.Kind{Type: <ForType-apiType>}, &handler.EnqueueRequestForOwner{OwnerType: apiType, IsController: true})`
> 📖 Fix error in doc

- pkg/webhook/conversion/conversion.go
The log message that used this was removed in this commit https://github.com/kubernetes-sigs/controller-runtime/commit/0f2e574d471454928fafffcaaafeed581ef89aae#r36915807
> :running: Remove unused variable from IsConvertible

- CONTRIBUTING.md
- Makefile
Makefile target name was incorrect and running `make check-all` actually did not do anything.
> 🏃 (:running:, other) Fix makefile and docs for running tests

- OWNERS
- OWNERS_ALIASES
- pkg/internal/testing/OWNERS
This cleans up the owners file, making sure that only active members
will be assigned and bringing it in line with the latest docs on the
OWNERS file from the main k/community repo.
> :running: Clean up OWNERS file

- pkg/internal/testing/integration/apiserver.go
When start of controlplane fails, the call to Stop will panic b/c processState was never allocated. The fix just adds a simple non-nil check before calling `s.processState.Stop()`. 
See a failed run here: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/1963/pull-cluster-api-test/1220713178762055683
> 🐛 (:bug:, patch) Fix panic in call to processState.Stop()

- OWNERS_ALIASES
Been active in reviews, very invested in this project and happy to help continue guiding CR to be an amazing tool!
> 🏃🏻‍♀️ Make gerred approver

- pkg/internal/testing/integration/internal/process_test.go
The test is flaky, see https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_controller-runtime/592/pull-controller-runtime-test-master/1220082018474266624 or https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_controller-runtime/776/pull-controller-runtime-test-master/1220286274334625792
My hunch was that 20 millis is not enoughso I tried fixing the test by using much bigger poll interval.
> 🏃 (:running:, other) Try to stabilize the flaky process_test

- pkg/envtest/server.go
- pkg/internal/testing/integration/internal/apiserver.go
After #749 the defaults to API server are now defined in two places - deep into the imported test framework and in envtest. I think it's enough to keep the defaults at one place - that is what this PR does.
> ✨ (:sparkles, minor) APIServer defaults deduplication

- pkg/leaderelection/leader_election.go
- pkg/manager/manager_test.go
With the current defaulting for the leader election ID, there is a clash
as soon as two controller that do not have it explicitly configured run
in the same namespace or have the same namespace configured for leader
election.
This is especially bad since there is no logging about the lock being
held by a different controller, so from a users perspective this looks
like the controller just froze.
Fixes #445
/assign @DirectXMan12 
/cc @JoelSpeed
> :warning: Remove defaulting for leader election ID

- hack/check-everything.sh
- hack/ci-check-everything.sh
- pkg/client/apiutil/dynamicrestmapper.go
- pkg/client/apiutil/dynamicrestmapper_test.go
- pkg/client/fake/client.go
- pkg/envtest/server.go
- pkg/internal/recorder/recorder.go
- pkg/leaderelection/leader_election.go
- pkg/metrics/listener.go
- pkg/webhook/admission/multi.go
- pkg/webhook/conversion/conversion.go
This PR builds on #598 by completing more of the tasks listed in #590:
(note: we already did a soft-bump to 1.13 the previous release, this just starts using the features)
> :warning: Bump to Go 1.13

- pkg/controller/controller_test.go
- pkg/manager/manager_test.go
This PR adds tests both for manager and controller checking the leak of goroutines on start and stop, I put the threshold of 5 in comparison because it has 3 leaks after stop:
```
goroutine 29 [chan receive]:
k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc00021fa80)
goroutine 166 [chan receive]:
k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1(0x291e580, 0xc000212ab0, 0xc000212a80)
goroutine 167 [chan receive]:
k8s.io/client-go/tools/record.(*eventBroadcasterImpl).StartEventWatcher.func1(0x291e580, 0xc000212ae0, 0xc0003fb350)
```
Related with #724
> :running: Verification of leak goroutine on controller and manager

- hack/verify.sh
- pkg/internal/testing/integration/internal/process.go
This PR makes sure the `pollURLUntilOK` function closes the body from `http.Get` if there is no error, and adds `bodyclose` linter to the enabled linters.
> 🐛 Integration test should close http body

- pkg/client/fake/client_test.go
- pkg/client/options.go
>  ✨Add HasLabels helper option for List calls

- pkg/envtest/envtest_test.go
InstallCRDs test has been flaking a lot in various PRs (see https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_controller-runtime/792/pull-controller-runtime-test-master/1225467749271080963/build-log.txt)
Recently we have started waiting for the CRD removal there, each CRD eventually block has a timeout of 1 second, while the overall AfterAll has also timeout of 1 second. This PR raises that timeout to give a more time to teardowns with multiple crds (like the InstallCRDs test).
> 🏃 (:running:, other) Bigger teardown timeout for flaky test

- pkg/client/config/config.go
Following up on the regression introduced in #642 and discussed in #748, this PR detects if $HOME is empty and, if so, automatically sets $HOME to user.Current before using client-go's default loading rules, which only checks $HOME.
As a follow-on, we could submit an issue upstream to see if it makes sense for client-go to use user.Current as a fallback so that we don't have to do it here in controller-runtime.
Closes #748
> :bug: When loading client config, check os/user.HomeDir if $HOME is unset

- pkg/source/source.go
Create a wrapper for Kind without `InjectCache` to create a supported way of setting a cache on source.Kind. This can used, e.g., for watching resources on another cluster.
fixes #650
> ✨ Create a supported way of setting a cache on source.Kind

- OWNERS
- OWNERS_ALIASES
To help with grooming and releases.
Related to https://github.com/kubernetes/org/pull/1619
/assign @DirectXMan12
> Add vincepri to maintainers

- pkg/internal/testing/integration/control_plane.go
- pkg/internal/testing/integration/internal/integration_tests/integration_test.go
This PR is purely re-targeting https://github.com/kubernetes-sigs/testing_frameworks/pull/68 to controller-runtime.
> :sparkles: support restconfig to target the control plane

- .golangci.yml
- hack/check-everything.sh
- hack/verify.sh
- pkg/client/client_cache.go
- pkg/client/fake/client_test.go
- pkg/controller/controller_integration_test.go
- pkg/handler/eventhandler_test.go
- pkg/internal/controller/controller.go
- pkg/leaderelection/fake/leader_election.go
- pkg/log/zap/zap_test.go
- pkg/manager/internal.go
- pkg/manager/signals/signal_test.go
- pkg/reconcile/example_test.go
- pkg/webhook/server.go
This updates golangci-lint, moves the configuration all to `.golangci.yml` and then fixes the linter errors
> :running: Update linter and lint fixes

- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
When an object is created without a `Name` but with a `GenerateName`, the fake client will set a `Name` by appending a randomly generated UID to the end of the `GenerateName` prefix.
This change replicates the behavior of the [API Server's NameGenerator](https://github.com/kubernetes/apiserver/blob/master/pkg/storage/names/generate.go).
> 🐛 Use GenerateName during fake client's Create method

- README.md
- designs/README.md
- designs/template.md
Per the discussion in the controller-runtime this fixes #807 adding so that I can add the design document for #518 
> ✨📖 Adding designs folder and sample template

- go.mod
- go.sum
One of the goals of #590 is 
```
Prune any uses of xerrors
```
So in this PR, I remove the last trace of xerrors.
** Tested How? **
Did a `go build` it worked just fine.
> :running: prune any use of xerrors

- pkg/cache/informer_cache.go
- pkg/cache/informer_cache_unit_test.go
- pkg/controller/controller_integration_test.go
- pkg/controller/controller_suite_test.go
- pkg/controller/controllertest/unconventionallisttypecrd.go
- pkg/controller/testdata/crds/unconventionallisttype.yaml
Makes the cache cope with list types that have a slice of pointers as `Items` field.
Fixes #656
Supersedes and thereby closes #667
> 🐛 Fix informer cache creating pointers to pointers 

- pkg/cache/cache_test.go
- pkg/cache/informer_cache.go
- pkg/cache/internal/deleg_map.go
- pkg/cache/internal/informers_map.go
Follow up to #580 
Fixes #562 
If the context's deadline is exceeded waiting for the cache to sync, then we should return an appropriate error.
This intentionally punts on what a sensible default should be for this timeout based on [this comment](https://github.com/kubernetes-sigs/controller-runtime/pull/580#discussion_r320429256)
> Let's punt on the default for now (do it in a separate PR) so we can at least get the capability in and unbreak people that want to use this.
**What this PR needs**
> ✨ Take context when getting informer.

- pkg/client/client.go
- pkg/client/client_cache.go
- pkg/client/client_test.go
- pkg/client/codec.go
- pkg/client/typed_client.go
- pkg/client/unstructured_client.go
ref: https://github.com/kubernetes-sigs/controller-runtime/issues/41#issuecomment-589237195
aligns the unstructured client with the typed client, sharing a cache between them for object metadata. plumbs context through to the restclient for unstructured client in doing so.
@shawn-hurley mentioned there were previously some issues with this, but as-is the implementation passes all current tests?
also, idk how hacky people consider this 😄 feels like I probably need to fix up some GVKs somewhere in the lists...
> 🐛 respect context in unstructured client

- pkg/metrics/client_go_adapter.go
- pkg/metrics/listener.go
- pkg/metrics/workqueue.go
Update documentation for the metrics package to enumerate all exposed
metrics with an explanation of what they capture.
Fixes #262
> 📖 document exposed metrics

- pkg/controller/controllerutil/controllerutil.go
- pkg/controller/controllerutil/controllerutil_test.go
> :sparkles: Add controllerutil.EnsureOwnerReference

- pkg/envtest/crd.go
- pkg/envtest/envtest_test.go
- pkg/envtest/helper.go
This PR updates the envtest helper to use a local scheme and the `Convert` method, which should preserve the TypeMeta information.
`runtime.DefaultUnstructuredConverter` doesn't know how to populate `TypeMeta` information from the Go Struct, while `scheme.Convert` uses internal helper methods to figure that out. 
From a UX point of view, this change has the benefit that `envtest` users can use the Go structs without worrying about TypeMeta. If TypeMeta isn't present when we install CRDs, the installation will fail and `envtest` won't start.
> :running: Use scheme.Convert to convert unstructrured objects

- pkg/builder/controller_test.go
- pkg/controller/controller.go
- pkg/ratelimiter/doc.go
- pkg/ratelimiter/ratelimiter.go
Exposes rate limiter as a controller option in case users want to use
a different rate limiter than the default one provided by
controller-runtime.
Fixes #631
> ✨Make workqueue rate limiter configurable during controller creation

- pkg/webhook/server.go
Enable webhook server set-up mTLS service to verify client's certificate according to the given CAName
Not sure how to add UT, this package seems no UT for now?
> ✨enable webhook server set-up mTLS service to verify client's certificate

- pkg/cache/cache_test.go
- pkg/envtest/envtest_suite_test.go
- pkg/envtest/envtest_test.go
- pkg/envtest/server.go
- pkg/envtest/webhook.go
- pkg/envtest/webhook_test.go
- pkg/internal/testing/integration/apiserver.go
- pkg/internal/testing/integration/control_plane.go
- pkg/internal/testing/integration/internal/apiserver.go
- pkg/internal/testing/integration/internal/tinyca.go
Ability to test webhooks with envtest
lots of code is reused from PoC done in #645
Fixes #563
Co-authored-by: Solly Ross <sollyross@google.com>
> ⚠ (:warning:, major) Webhook support in envtest

- pkg/webhook/conversion/testdata/main.go
The import path used here is incorrect, and there is no `go.mod` included in the root of this testdata directory to indicate its module name is `testdata.kb.io` (and I'm not actually certain this is a valid module path as it does not contain a `/`.
Additionally, the `api/v1` package itself imports `v2` as `sigs.k8s.io/controller-runtime/pkg/webhook/conversion/testdata/api/v2`: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/webhook/conversion/testdata/api/v1/externaljob_types.go#L23
I noticed this because Bazel attempts to resolve this import path in my project, and fails to resolve it to a real repository, leading to confusing log output when analysing our dependencies 😅
> 🐛 Fix testdata imports in pkg/webhook/conversion

- pkg/controller/controllerutil/controllerutil.go
- pkg/controller/controllerutil/controllerutil_test.go
To be consistent with `SetControllerReference`, rename EnsureOwnerReference to SetOwnerReference.
> 🏃Rename EnsureOwnerReference to SetOwnerReference for consistency

- pkg/envtest/server.go
Export DefaultKubeAPIServerFlags in envtest package to make it possible
for users to modify flags.
Reference https://book.kubebuilder.io/reference/testing/envtest.html#flags
Fixes #841
> 🐛 expose DefaultKubeAPIServerFlags in envtest

- pkg/client/apiutil/dynamicrestmapper.go
- pkg/client/apiutil/dynamicrestmapper_test.go
fixes https://github.com/kubernetes-sigs/controller-runtime/issues/804
this test case fails on master, and should succeed
> 🐛 fix conservative delay in rate limiter

- hack/check-everything.sh
A slight improvement to the script that fetches kubebuilde-tools to avoid re-downloading the binaries if the existing version already matches our expectations.
> 🏃fetch_ext_bins now checks existing version before downloading

- hack/release/release-notes.sh
PR #767 introduces some weird merge commit styles into the git history
by default, so now we have to tolerate them in our release notes script.
> :running: Tolerate (more) merge commits in release notes

- OWNERS_ALIASES
- go.mod
- go.sum
- hack/check-everything.sh
- hack/release/release-notes.sh
- pkg/client/apiutil/dynamicrestmapper.go
- pkg/client/apiutil/dynamicrestmapper_test.go
- pkg/envtest/server.go
- pkg/log/zap/flags.go
- pkg/log/zap/zap.go
```markdown
- Add helpers to configure logger options via pflags (#767)
- fix conservative delay in rate limiter (#859)
- expose DefaultKubeAPIServerFlags in envtest (#846) -- fixes an accidental breaking change in envtest
*Thanks to all our contributors!*
```
> :running: Release v0.5.2

- pkg/envtest/testdata/webhooks/manifests.yaml
- pkg/envtest/webhook.go
- pkg/envtest/webhook_test.go
At the moment the `DirectoryPaths` option of the `WebhookInstallOptions` is broken. This PR fixes it.
Fixed #867
> 🐛 fix version check when reading webhooks from file

- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
This PR changes the fakeclient to:
* Refuse Create requests with RV set
* Refuse Update requests with outdated RV
Note that while this brings the fakeclient more in line with a real client, it is a breaking change and has a good chance of breaking ppls tests.
> :warning: Fakeclient: Reject Update with outdated ResourceVersion

- pkg/builder/controller.go
- pkg/builder/controller_test.go
- pkg/builder/options.go
- This PR adds options for defining the `Predicate`. Watches, Owns, For, and Watches
- Add tests coverage for implemented logic using ginko & gomega 
Implemented with Functional Options pattern as described here: https://github.com/kubernetes-sigs/controller-runtime/pull/602#discussion_r377337991
I decided to go with `Input` struct for each method to have separation and make those methods independent of each other. 
Fixes: https://github.com/kubernetes-sigs/controller-runtime/issues/572
> :warning: Add predicates as variadic args for Owns, For, and Watches func

- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/informer_cache.go
- pkg/cache/informertest/fake_cache.go
- pkg/cache/multi_namespace_cache.go
- pkg/client/example_test.go
- pkg/client/interfaces.go
- pkg/internal/controller/controller_test.go
- pkg/source/source.go
Update all functions on the Informers interface (and IndexField on
FieldIndexer interface) to accept a context.
Fixes #828
> ⚠ update Informers interface to accept context

- pkg/scheme/scheme_test.go
The scheme test knows how many types should be returned, but omitted `CreateOptions` from being explicitly checked.
> 🏃 Use whole list matching for known types.

- pkg/client/options.go
- pkg/client/options_test.go
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/740
Following up on an idea by [@lavalamp](https://github.com/kubernetes/kubernetes/pull/89747#discussion_r401959488) this PR makes `MatchingLabels` construct an invalid selector rather than a (valid) match all selector in case of invalid input, which means the server will reject the request.
/assign @alexeldeib @vincepri
> :bug: MatchingLabels: Make sure requests with invalid labels fail

- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
> :warning: Fakeclient: reject create/update if Name isn't provided

- .golangci.yml
- pkg/builder/options.go
- pkg/builder/webhook.go
- pkg/client/fake/doc.go
- pkg/client/options.go
- pkg/controller/controllertest/unconventionallisttypecrd.go
- pkg/internal/testing/integration/internal/apiserver.go
- pkg/internal/testing/integration/internal/arguments.go
- pkg/internal/testing/integration/internal/etcd.go
- pkg/internal/testing/integration/internal/integration_tests/doc.go
- pkg/internal/testing/integration/internal/process.go
- pkg/internal/testing/integration/internal/tinyca.go
Now, the lint test will be checking the comments for the go-docs and then, it is called in the checks made in prow to allow or not merge the PR. 
Also, in this PR, we have the fix for the places where the comments were missing.
**Motivation**
Closes: #501
> :book: re-enable golangci-lint's godoc comment checking

- pkg/controller/controllerutil/controllerutil.go
When I read the codes in `controllerutil.go`, I found there is a minor typo in the error message.
In the function `SetOwnerReference`, the error message should be
```
return fmt.Errorf("%T is not a runtime.Object, cannot call SetOwnerReference", owner)
```
instead of
```
return fmt.Errorf("%T is not a runtime.Object, cannot call SetControllerReference", owner)
```
> :running: Fix a typo in the error message

- pkg/scheme/scheme.go
In addition to adding scaffolded `utilruntime.Must` for scheme registration in `kubebuilder` (https://github.com/kubernetes-sigs/kubebuilder/pull/1462) this updates the docs for `controller-runtime` docs to include panicking when scheme registration fails. 
You will notice that internal to `localSchemeBuilder` in `client-go` (https://github.com/kubernetes/client-go/blob/master/kubernetes/scheme/register.go#L133) and most schemes within kubernetes they cause panics if anything from conversions to defaults fail.
After discussing with @DirectXMan12 this being left out probably either an oversight to that this pattern was developed after these packages where made.
> Adding docs using utilruntime.Must for scheme registration

- pkg/log/zap/kube_helpers.go
- pkg/log/zap/zap_test.go
Surprisingly `*unstructured.Unstructured` does NOT implement the `fmt.Striger` interface.
We have to work around it in `KubeAwareEncoder` until it is fixed.
> :bug: KubeAwareEncoder should handle unstructured object correctly

- pkg/envtest/crd.go
- pkg/envtest/envtest_test.go
- pkg/envtest/helper.go
There is a bug in how envtest package determine if a CRD should be considered as a duplicate and skipped:
If we specify more than one CRD files that live in the same directory, it always skip the everything but the first CRD.
> :bug: fix CRD filtering in envtest package

- pkg/client/client_test.go
- pkg/client/dryrun.go
- pkg/client/dryrun_test.go
- pkg/client/options.go
- pkg/manager/manager.go
This PR adds a DryRunClient wrapper that enforced DryRun on all mutating operations and plugs that into the client and manager constructors. This is useful to check what a controller does in a production environment without actually doing it.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/831
> ✨ Add DryRunClient wrapper

- hack/check-everything.sh
- pkg/internal/testing/integration/internal/apiserver.go
If we enable ServiceAccount plugin, tests fail with this error. That is because controller normally takes care of creating default service account but that controller is not running in the integration environment.
```
"pods \"test-pod-1\" is forbidden: error looking up service account test-namespace-1/default: serviceaccount \"default\" not found",
```
We either keep that disabled by default or envtest would have to create that SA for the users? Otherwise all users would have to create that SA which I think is not desired.
> ⚠ (:warning:, major) Do not disable admission plugins by default

- pkg/client/config/config_test.go
Where `~/kube/foo.yaml` is a valid yaml, when $KUBECONFIG is set the tests fail. 
```
KUBECONFIG=~/kube/foo.yaml TRACE=1 ./hack/check-everything.sh
```
```
Expected <snip> to be nil
Summarizing 1 Failure:
[Fail] Config GetConfigWithContext when kubeconfig files don't exist [It] should fail 
/Users/mcristi1/go/src/github.com/kubernetes-sigs/controller-runtime/pkg/client/config/config_test.go:85
```
This ensures the env var is unset prior to testing the failure case of `GetConfigWithContext("")`
> :bug: Ensure KUBECONFIG is unset when testing GetConfigWithContext

- pkg/log/zap/flags.go
- pkg/log/zap/zap.go
Update the options using the concrete type *zap.AtomicLevel to instead
use the zapcore.LevelEnabler interface.
Fixes #899
> :warning: log/zap options Level and StacktraceLevel type

- pkg/envtest/webhook.go
Fixed because the constant values had been swapped.
> :bug: Fix swapped constant value in webhook envtest

- hack/apidiff.sh
- hack/tools/go.sum
ref https://github.com/kubernetes-sigs/controller-runtime/pull/909#issuecomment-615505119
> 🏃 don't use apidiff on dirty commits

- pkg/manager/internal.go
- pkg/manager/manager.go
- pkg/manager/manager_test.go
Allows users to add extra http handlers served on custom path to the http server that serves metrics. Might be useful to register some diagnostic endpoints e.g. pprof or custom debug info.
Ref: #684
---
Some additional thoughts: since we expose this, naming the server "metrics server" is not 100% correct anymore. Probably we might call it "diagnostic server" or something, that describes the purpose more clearly. Of course renaming would be a breaking change. As far as I found, the only metrics-related name we expose in the API is `MetricsBindAddress` in manager options.
> ✨Expose metrics http server for extra endpoints

- pkg/controller/controller.go
- pkg/controller/example_test.go
- pkg/manager/internal.go
- pkg/manager/manager.go
- pkg/manager/manager_test.go
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/730
Increasingly in [Crossplane](https://github.com/crossplane) we find that we'd like to use one kind of custom resource to describe how another, arbitrary, kind of custom resource should be reconciled. For example a `kind: Template` resource may configure how a `kind: Widget` resource should be reconciled. This involves the controller that watches for `kind: Template` managing the lifecycles of another set of controllers, including the controller that watches for `kind: Widget`. This is not currently possible in controller-runtime because all controllers are implicitly added to and started by the controller manager, which has no facility for stopping or removing a controller.
This PR makes it possible to start, run, _and …
> ✨Allow controllers to be started and stopped separately from the manager

- pkg/controller/controllerutil/controllerutil.go
- pkg/controller/controllerutil/controllerutil_test.go
> :bug: controllerutil.RemoveFinalizer can occurs slice bounds out of range exception

- pkg/source/internal/eventsource.go
This commit fixes wrong package identifier in comment of type `EventHandler`.
> :book: Correct Wrong Package Identifier in Explanation of EventHandler

- pkg/manager/manager.go
There is a set of cases where ppl might want to wrap the
defaultNewClient, for example:
* To force dry run (currently possible via a manager opt)
* To enforce usage of a given namespace
/assign @mengqiy @DirectXMan12
> :sparkles: Manager: Export defaultNewClient

- pkg/envtest/server.go
The individual test component configuration types accidentally got made internal during the migration of the testing_frameworks code.  This re-exposes them.
Fixes #875
> :bug: cannot specify ControlPlane in envtest.Environment

- pkg/controller/controller.go
- pkg/internal/controller/controller.go
The controller contains the unused Config attribute. Since its exported,
linters will not complain about it, but since its in an internal
package, it is not part of our public api.
> :running: Remove unsed Config attribute from controller

- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/918
This breaks the code that relies on first checking if an object already exists via the error returned from `Create` and then run `Patch`. Since `Patch` call of fake client does an `Update` operation, which checks resource version match, it returns `object was changed` error in these cases because the local object now has resource version 1 but what storage has is resource version 0 since the client was initialized with that object.
> 🐛 Reset resource version if fake client Create call failed

- pkg/controller/controller.go
- pkg/internal/controller/controller.go
- pkg/internal/controller/controller_test.go
- pkg/source/source.go
- pkg/source/source_test.go
Currently, the controller gets a cache injected and waits for that cache
to sync before starting workers. This model works well for single
cluster usecases, but doesn't work at all for multi-cluster usecases, as
the source may be using a completely different cache.
This PR adds a new source.SyncingSource interface and makes the
controller wait for all sources that implement it. Apart from solving
the issue mentioned in the title, this also allows to implement custom
sources that need syncing.
> ✨ Controller: Let sources sync even if they use a different cluster

- pkg/client/interfaces.go
- pkg/controller/controllerutil/controllerutil.go
Signed-off-by: ruromero <rromerom@redhat.com>
Introduce an interface that combines `metav1.Object` and `runtime.Object` as discussed in https://github.com/kubernetes-sigs/controller-runtime/issues/594
The main purpose of this interface is to reduce type conversions between the two and provide generic method signatures that can show potential errors at compile time and help developers to write simpler code.
This can make reconsider many places in this library and dependent ones its usage each time a cast is done, usually like the following:
```
//metav1.Object -> runtime.Object
ro, ok := owner.(runtime.Object)
//runtime.Object -> metav1.Object
o, err := meta.Accessor(obj)
```
An example where this interface can be used is https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg …
> ✨ Introduce controllerutil.Object interface

- pkg/client/fake/client.go
Fix `DeleteAllOf`. It is using a wrong scheme right now.
> :bug: Fix scheme used by `DeleteAllOf` in fake client

- pkg/client/fake/client.go
> Backport release-0.5: Fix scheme used by `DeleteAllOf` in the fake client.

- examples/builtins/controller.go
Reconciler errors are logged by the framework. See https://github.com/kubernetes-sigs/controller-runtime/blob/198197fe0fd7553cadd8afcd3338f8ee4b8a7e3f/pkg/internal/controller/controller.go#L258
Currently in the builtins example errors are logged 2 times - once by `example-controller.reconciler` logger and once by the `controller-runtime.controller` logger. Logging the error in the `reconcileReplicaSet ` itself is superfluous and the controller-runtime idiomatic way would be to return the error and have it logged only once by the `controller-runtime.controller` logger.
> 📖 Prevent errors to be logged multiple times in builtins example

- pkg/controller/controllerutil/controllerutil.go
- pkg/controller/controllerutil/controllerutil_test.go
This is ContainsFinalizer helper in the controllerutil package which checks that provided finalizer exists in the Object meta
Fixes #920
> :sparkles: Add ContainsFinalizer helper to the controllerutil

- pkg/controller/controller.go
- pkg/internal/controller/controller.go
- pkg/internal/controller/controller_test.go
- pkg/source/source.go
- pkg/source/source_test.go
Currently, the controller gets a cache injected and waits for that cache
to sync before starting workers. This model works well for single
cluster usecases, but doesn't work at all for multi-cluster usecases, as
the source may be using a completely different cache.
This PR adds a new source.SyncingSource interface and makes the
controller wait for all sources that implement it. Apart from solving
the issue mentioned in the title, this also allows to implement custom
sources that need syncing.
> Backports for v0.5.4

- pkg/controller/controllerutil/controllerutil.go
As #898 introduces controllerutil.Object interface this fix migrates controllerutil AddFinalizer and RemoveFinalizer to the controllerutil.Object interface and remove *WithError functions as they are not needed anymore as checks are performing on the compile time.
Fixes #959
> :sparkles: Migrate controllerutil AddFinalizer and RemoveFinalizer to controllerutil.Object and deprecate *WithError functions

- go.mod
- pkg/webhook/internal/certwatcher/certwatcher.go
Use github.com/fsnotify/fsnotify instead of deprecated gopkg.in/fsnotify.v1
See https://github.com/fsnotify/fsnotify/blob/master/go.mod#L1
Signed-off-by: Pierre Péronnet <pierre.peronnet@ovhcloud.com>
> 🐛 fix(dependency) Use github.com/fsnotify/fsnotify

- pkg/client/client_test.go
- pkg/client/patch.go
> :sparkles: Add Patch MergeFrom optimistic locking option

- pkg/client/client_test.go
- pkg/client/patch.go
> [0.5] :sparkles: Add Patch MergeFrom optimistic locking option

- pkg/internal/testing/integration/control_plane.go
This patch fixes an issue that occurs when shutting down an `envtest.Environment`. If the API server fails to shutdown, then the etcd process is orphaned. This can result in dozens of running etcd processes when debugging failed tests.
Please see this [Slack discussion](https://kubernetes.slack.com/archives/CAR30FCJZ/p1590779385006000) for more information.
cc @DirectXMan12 @fstrudel
> 🐛 Always shutdown etcd when stopping envtest

- pkg/webhook/internal/metrics/metrics.go
- pkg/webhook/server.go
Add a gauge for requests currently being handled and a counter for the total amount of requests processed.
I used [prometheus/promhttp](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus/promhttp?tab=doc) package which provides nice decorators for `Http.Handler` to handle the metrics instead of the custom code.
> :sparkles: Add webhook total and in-flight metrics

- pkg/runtime/inject/inject.go
> 📖 Nit: improve doc string

- pkg/controller/controller.go
- pkg/internal/controller/controller.go
This removes a set of unused attributes from the controller.
> :running: Remove unused attributes from controller

- pkg/controller/controller.go
- pkg/internal/controller/controller.go
- pkg/internal/controller/controller_test.go
/assign @alvaroaleman @DirectXMan12
>  🏃 Cleanup controller internal logger

- pkg/client/apiutil/apimachinery.go
Just a small nit, given that this function isn't trying to create an informer.
> 🏃 Clarify log line in apiutil.GVKForObject

- go.mod
- go.sum
See https://github.com/kubernetes/kubernetes/pull/91622
> JSON patch implemented by https://github.com/evanphx/json-patch now conforms to RFC6902 replacement semantics and does not accept "replace" patch operations if the specified path does not exist.
> 🏃 Update json-patch dependency to e83c0a1c26c8

- pkg/webhook/example_test.go
Trying to use a nil/zero'ed Manager results the example code to immediate panic on startup, so create a proper Manger instead.
See #1015
> :bug: Fix webhook example

- pkg/envtest/crd.go
- pkg/envtest/webhook.go
fix:https://github.com/kubernetes-sigs/controller-runtime/issues/1027
> feat:remove the whitelist word from our codebase

- pkg/manager/internal.go
- pkg/manager/manager.go
Fixes:https://github.com/kubernetes-sigs/controller-runtime/issues/1028
/cc @vincepri
> feat:Remove master word from our codebase

- pkg/leaderelection/leader_election.go
suffix the leader-election client with `/leader-election` for better auditing
>  🐛 Better UserAgent for leader-election client

- hack/test-all.sh
- pkg/builder/controller_test.go
- pkg/cache/informer_cache_unit_test.go
- pkg/internal/testing/integration/internal/integration_tests/etcd_integration_test.go
- pkg/internal/testing/integration/internal/process_test.go
- pkg/manager/manager_test.go
Changes the test script to run with `--race` and fixes the ~three~ five races found (all of which are in test code)
>  🏃 Run tests with race detector enabled

- pkg/manager/manager.go
Allow controllers to have more control over leader election REST config if desired.
> :sparkles: optionally override leader election client config

- pkg/predicate/predicate.go
- pkg/predicate/predicate_test.go
This PR adds two new boolean predicate functions (`predicate.And()` and `predicate.Or()`) that take a variadic predicates argument.
When creating a watch, multiple predicates can be used, but they are always logically ANDed together. If these boolean predicates existed, it would be easier for users to reuse simple predicates to build complex predicate filters for their watches without having to resort to writing their own monolithic predicate from scratch.
> ✨ pkg/predicate.go: add And and Or predicates

- hack/test-all.sh
According to https://github.com/onsi/ginkgo/issues/280 this doesn't seem
to be properly supported. If we want parallelization, we should use
ginkgos built-in mechanism for that.
> :running: Disable golangs parallel testing

- pkg/reconcile/reconcile.go
- pkg/reconcile/reconcile_test.go
> :sparkles: Add IsZero method to reconcile.Result

- pkg/manager/internal.go
- pkg/manager/manager.go
- pkg/manager/manager_test.go
This PR implements graceful shutdown.
It is a rebased version of https://github.com/kubernetes-sigs/controller-runtime/pull/664 plus a set of "Verschlimmbesserungen":
* There was a deadlock in case the cache start failed, because we required the lock to `close(cm.internalStopper)` but the cache kept it while waiting for sync, so if we shutdown before sync completed, this is a deadlock
* Godocs: https://github.com/kubernetes-sigs/controller-runtime/pull/664/files#r355773233
* Make the things we start `Runnables` as well so they are part of the graceful shutdown: https://github.com/kubernetes-sigs/controller-runtime/pull/664/files#r355783939
* Use a defer to do the graceful shutdown to make sure it always happens
* Return both the graceful shutdown and the run error, rather than only …
> :sparkles: Implement graceful shutdown

- pkg/builder/controller.go
- pkg/builder/controller_test.go
> 🐛 Prefer reconciler from controller.Options

- hack/test-all.sh
> :seedling: Remove -parallel flag from test coverage

- pkg/log/zap/flags.go
- pkg/log/zap/zap.go
- pkg/log/zap/zap_test.go
--Current implementation in `flags.go` has a bug, which is leading to incorrect zap log level to be set. 
--This PR also focuses on aligning `--zap-log-level` with logr levels.
Example: `--zap-log-level=2` should map to using increased verbosity `logr.V(2).Info()`.
-- This PR also disables Sampling for debug levels with increased verbosity,  as they will cause index out of bounds errors in sampling code.
Closes: #990
>  🐛 Fix allowed levels for --zap-log-levels flag to align with logr levels

- hack/test-all.sh
This PR removes the coverage step when running in our CI job (and locally). These commands have been ignored for a long time and are not particularly useful. In the future, we should adopt prow coverage utilities if there is a strong need.
/milestone v0.6.x
> Remove coverage when running tests

- pkg/controller/controller_test.go
- pkg/manager/manager_test.go
This PR disables the leak goroutine tests that are causing a lot of flakes in CI. After a conversation on Slack with @alvaroaleman, we agreed that these tests are very error-prone and should be revisited/rewritten later on.
/milestone v0.6.x
> Mark leak goroutine tests as pending

- pkg/manager/internal.go
- pkg/manager/manager_test.go
This PR fixes #1056 
Now Logger can be injected by the controller manager to the Object which implements the `inject.Logger` interface.
> 🐛  Enable Logger Injection for Controller Manager

- pkg/internal/testing/integration/internal/process_test.go
Hopefully will fix our top failing test. I believe it is failing because we expect it to be exited immediately after it started. However it might need a bit more time after printing the successful start message to be exited.
> 🐛 Test can inspect stdout & stderr: Give some time to exit

- hack/check-everything.sh
- hack/common.sh
- hack/setup-envtest.sh
- hack/test-all.sh
`envtest` is a test framework provided by `controller-runtime` that simplifies running integration tests for controllers.
Currently, it is not straightforward to setup envtest without also setting up kubebuilder. However, Kubebuilder is not a prerequisite to use `envtest`.
This PR splits out the envtest setup code from controller-runtime's CI scripts such that users could easily download and use the envtest setup code in their own CI scripts.
It would work like this:
```console
source <(curl -sfL https://raw.githubusercontent.com/kubernetes-sigs/controller-runtime/master/hack/setup-envtest.sh)
envtest_assets_dir=$(pwd)/test/assets
fetch_envtest_tools "$envtest_assets_dir"
setup_envtest_env "$envtest_assets_dir"
```
> 🏃 setup-envtest.sh: standalone script for setting up envtest

- alias.go
- pkg/log/log.go
/assign @alvaroaleman @detiber 
This we might be able to merge now, given that's not a breaking change
> ✨ Add ability to set/get logger in/from a context.Context

- pkg/builder/controller.go
- pkg/controller/controller.go
- pkg/internal/controller/controller.go
- pkg/manager/internal.go
- pkg/manager/manager.go
/assign @alvaroaleman @detiber 
Made these changes also backward compatible to be able to go in v0.6.2
> :sparkles: Add options to configure a logger for manager and controllers

- pkg/manager/internal.go
- pkg/manager/manager_test.go
When a named readiness/liveness check is registered it should be available under /readyz/<name>.
This PR enables this by adding a trailing slash to the default readyz and healthz endpoints, configuring
the server to handle existing path (`/readyz`) and subpaths (`/readyz/my-check`).
> :sparkles: Make individual readiness and liveness checks accessible

- pkg/webhook/admission/http.go
Currently every webhook requests ended up logging this in debug:
```
2020-06-10T16:04:20.883+0200	DEBUG	controller-runtime.webhook.webhooks	wrote response	{"webhook": "/validate-some-resource", "UID": "e5d00608-7f47-4d00-bd91-b1a8955dc5a7", "allowed": true, "result": {}, "resultError": "got runtime.Object without object metadata: &Status{ListMeta:ListMeta{SelfLink:,ResourceVersion:,Continue:,RemainingItemCount:nil,},Status:,Message:,Reason:,Details:nil,Code:200,}"}
```
The problem is that a `Status` Object is a runtime.Object with no metadata which is not well received by the `zap.KubeAwareEncoder`.
> 🐛 Avoid marshalling error in debug log line

- hack/check-everything.sh
- hack/setup-envtest.sh
This follows up #1092 to address some of the comments and suggestions.
> 🏃 hack/setup-envtest.sh: follow-up from #1092

- .github/PULL_REQUEST_TEMPLATE/other.md
- .github/pull_request_template.md
- VERSIONING.md
- hack/release/common.sh
> Change other/minor emoji for PRs to :seedling:

- pkg/client/config/config.go
- pkg/client/config/config_test.go
Fixes:https://github.com/kubernetes-sigs/controller-runtime/issues/1028
/cc @vincepri
> ⚠️ Remove deprecated "--master" flag

- pkg/client/patch.go
> :warning: Remove deprecated client.ConstantPatch function

- pkg/builder/controller.go
> :warning: Remove deprecated For/WithConfig from controller builder

- pkg/client/client.go
- pkg/client/dryrun.go
- pkg/client/fake/client.go
- pkg/client/interfaces.go
- pkg/client/split.go
- pkg/runtime/inject/inject_test.go
> :warning: Expose RESTMapper on Client interface

- pkg/client/client_test.go
- pkg/client/options.go
> :warning: Remove deprecated pkg/client options

- pkg/controller/controllerutil/controllerutil.go
- pkg/controller/controllerutil/controllerutil_test.go
> :warning: Remove {Add,Remove}FinalizerWithError utils

- example_test.go
- examples/builtins/controller.go
- examples/builtins/main.go
- examples/crd/main.go
- pkg/builder/controller.go
- pkg/builder/controller_test.go
- pkg/builder/example_test.go
- pkg/controller/controller.go
- pkg/controller/controller_integration_test.go
- pkg/controller/controller_test.go
- pkg/controller/example_test.go
- pkg/internal/controller/controller.go
- pkg/internal/controller/controller_test.go
- pkg/internal/recorder/recorder_integration_test.go
- pkg/manager/manager.go
- pkg/manager/manager_test.go
- pkg/reconcile/example_test.go
- pkg/reconcile/reconcile.go
- pkg/reconcile/reconcile_test.go
> ⚠ Add a context w/ logger to Reconciler interface

- pkg/builder/builder_suite_test.go
- pkg/manager/manager_test.go
- pkg/webhook/server.go
Fixes #1018 
This PR changes the default port to serve webhook from 443 to 9443 since 443 causes some issues for no-root users.
> ⚠️ Change default webhook port to 9443

- pkg/envtest/webhook.go
- pkg/envtest/webhook_test.go
Fixes #1019 
This PR adds support to read webhook configurations from files for `WebhookInstallOptions`
> ⚠️ Add support to read webhook configurations from files for WebhookInstallOptions

- pkg/internal/controller/controller.go
Reconciliation errors are going to be logged only if V >= 3,
while success reconciliations are set for V >= 5.
/assign @alvaroaleman @detiber 
Set this as a ⚠️, but we can probably merge in v0.6.2 with a release note for the impact in case we want to.
> ⚠️ Remove logs from internal controller

- pkg/handler/enqueue_mapped.go
- pkg/handler/eventhandler_test.go
- pkg/handler/example_test.go
Makes creation of custom mappers a lot simpler
> :sparkles: Simplify usage of EnqueueRequestsFromMapFunc

- pkg/predicate/predicate.go
- pkg/predicate/predicate_test.go
The LabelSelectorPredicate function implements predicate functions to only reconcile events that contain certain labels.
This allows a user to pre-determine which events will undergo reconciliation via a Selector object that will compare against an event's labels, thereby "filtering" events.
> ✨ Added the LabelSelectorPredicate function for filtering events

- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
As of v0.6.0, the fake client is rejecting Updates where the ResourceVersion is not set on the object. 
It looks like this was introduced as part of #832 to reject Updates where the ResourceVersion does not match, however it didn't special case the case where ResourceVersion is not set on the resource provided to Update but the existing resource has ResourceVersion set.
This PR re-adds support for calling Update with ResourceVersion unset, but maintains the rejection of mismatching ResourceVersion when provided.
> :bug: Fakeclient: Honor AllowUnconditionalUpdate and AllowCreateOnUpdate for resources that support it

- pkg/manager/internal.go
- pkg/manager/manager.go
```
// LeaderElectionReleaseOnCancel defines if the leader should step down voluntarily
// when the Manager ends. This requires the binary to immediately end when the
// Manager is stopped, otherwise this setting is unsafe. Setting this significantly
// speeds up voluntary leader transitions as the new leader doesn't have to wait
// LeaseDuration time first.
```
This is off by default because it might be unsafe.
> :sparkles: Allow configuring LeaderElectionReleaseOnCancel

- pkg/internal/controller/controller.go
- pkg/internal/controller/metrics/metrics.go
Helps debugging issues around reconciliation duration. Right now its impossible to find out the number of workers from metrics and its also impossible to find out the number of active workers. The only thing we have is `workqueue_unfinished_work_seconds` which if big is probably not good but its not clearly indicating if we have one worker that takes longer, if all workers are blocked etc.
> :sparkles: Add metrics for total workers and active workers

- go.mod
- go.sum
- pkg/log/zap/flags.go
- pkg/log/zap/zap.go
- pkg/log/zap/zap_test.go
Description: This PR adds field in Options struct, for adding Encoder configuration options programmatically.
Motivation: This will make it easier for operator developers to specify different Encoder options.
Fixes: #912
>  ✨ Added Encoder Config Options field.

- pkg/client/fake/doc.go
This PR adds more information to let users know of the currently known limitations as they exist in `fake.Client`.
We need this to:
* share this list with potential users of the fake client to help with expectations around TDD
* also will help with discussion around which item on the list may be fixed via its own issue. 
This PR also removes the deprecation warning as per issue #768 and is the first step to see if we can improve TDD experience for unit testing by using the fake Client in various testing use cases and scenarios.
> add a known limitations section to fake Client

- go.mod
- go.sum
- pkg/controller/controller_suite_test.go
- pkg/controller/controller_test.go
- pkg/internal/recorder/recorder.go
- pkg/internal/recorder/recorder_test.go
- pkg/manager/internal.go
- pkg/manager/manager.go
- pkg/manager/manager_suite_test.go
- pkg/manager/manager_test.go
Since we now have the ability shut down the event broadcaster, we can
write mostly goroutine-leak-free event handling setup.  This changes the
default event handling setup to defer the broadcaster initialization the
first time it's used, and then to shut it down once the manager shuts
down.
In the case where a broadcaster is manually specified, it's the
specifier's job to shut down the broadcaster instead.
We'll probably still want to overhaul the whole event system at some
point in the future though.
This also re-enables the tests for leaks, switching them to an
eventually to avoid flakes & reducing the threshold to zero.
Closes #637
/kind bug
> Try to avoid event handling leaks

- pkg/manager/internal.go
- pkg/manager/manager_test.go
By https://github.com/kubernetes-sigs/controller-runtime/pull/1100, subpaths of `/healthz/` can be handled.
However, this change introduced the redirection from `/healthz` to `/healthz/` with 301 (Moved Permanently) when accessing `/healthz` endpoint like following. (Accessing `/healthz/` works fine without the redirect.)
```
→ curl -v -L http://localhost:8080/healthz
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /healthz HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-Type: text/html; charset=utf-8
< Location: /healthz/
< Date: Sun, 23 Aug 2020 08:41:59 GMT
< Content-Length: 44
<
* Ignoring the response-body
* Connection #0 to host localhost left intact
* Issue another request …
```
> :bug: Avoid the redirection to `/healthz/` when calling `/healthz`

- pkg/internal/controller/controller.go
- pkg/internal/controller/controller_test.go
Starting the controller more than once is always wrong. Today, it will
result in:
* Its active workqueue being re-created, resulting in a data race,
breaking the guarantee of "there is at most one worker on a given
queue key" and messed-up metrics
* Starting double as many workers as configured
This PR changes that to instead return an error on all subsequent Start
attempts.
> :bug: Controller: Return error when started more than once

- pkg/log/log.go
- pkg/log/log_test.go
This fixes a couple of bugs in the `log.FromContext` function:
- If the passed in context doesn't contain a logger, it attempts to cast a nil value as `logr.Logger` -- which causes a panic.
- The `keysAndValues` argument has no effect because the logger returned from the `WithValues` method is ignored in the return value.
Fixes #1140
> :bug: Handle empty contexts in log.FromContext

- pkg/webhook/admission/response.go
- pkg/webhook/admission/validator.go
- pkg/webhook/admission/validator_test.go
If a custom webhook validator returns a metav1.Status object as the error, the validation handler will build an admission response with this Status object as is, instead of building a new Status object based on err.Error()
This might be considered as a breaking change since the behaviour of the
validation handler is going to be slightly different from what the users
might expect based on the previous version of the code
> :warning: admission responses with raw Status

- pkg/leaderelection/leader_election.go
- pkg/manager/manager_test.go
This commit changes the leaderlock to ConfigMapsLeasesResourceLock,
which is intended to transition ppl from the ConfigMap to the more
modern Leases. It is breaking because additional RBAC is required.
Related issue is https://github.com/kubernetes-sigs/controller-runtime/issues/460
PRing this now because this change is breaking, so must happen before we cut 0.7.0. Adding an option to override the default is non-breaking, so not as important to happen ASAP.
> ⚠ Change leaderlock from ConfigMap to ConfigMapsLeasesResourceLock

- pkg/source/source.go
- pkg/source/source_test.go
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/942
> :bug: Source.Channel: Cope with pre-existing events in the channel

- pkg/leaderelection/leader_election.go
- pkg/manager/manager.go
- pkg/manager/manager_test.go
This PR makes the leader election resource lock configurable via `manager.Options.LeaderElectionResourceLock`.
It can be set to one of the lock types supported by client-go ([ref](https://github.com/kubernetes/client-go/blob/release-1.19/tools/leaderelection/resourcelock/interface.go#L31-L35)):
- `endpoints`
- `configmaps`
- `leases `
- `endpointsleases`
- `configmapsleases`
It keeps the default of `configmapsleases` introduced by #1144, but allows folks to explicitly configure other LE strategies.
Fixes #460
> ✨ Make leader election resourcelock configurable

- pkg/leaderelection/doc.go
Reading the documentation for the leaderelection pkg I got confused whether the package provides one constructor or multiple constructors. Currently, I can only see one constructur, so hopefully the patch makes sense. Otherwise, please correct me and we can fix it in the other direction :-)
> :book: Fix typo

- pkg/internal/controller/controller.go
- pkg/internal/controller/controller_test.go
The controller internal struct holds a list of watches
(as []watchDescription) when someone calls .Watch() to then start the
watches and informers once we're ready to call Start().
This behavior caused a memory leak in the case Watch was called after
a controller has already been started and if the source.Kind's cache was
either stopped or not available any longer. The leak was caused by the
watches internal slice holding on to all references to each watch ever
issued (and their respective caches).
/assign @alvaroaleman @DirectXMan12 @pwittrock 
I'll backport the fix to release-0.5 and release-0.6 if we all agree that this is the fix we want. For consistency, I also nil'd the c.watches slice after Start() has been called and the …
> 🐛 Controller.Watch() should not store watches if already started

- pkg/internal/controller/controller.go
- pkg/internal/controller/controller_test.go
The controller internal struct holds a list of watches
(as []watchDescription) when someone calls .Watch() to then start the
watches and informers once we're ready to call Start().
This behavior caused a memory leak in the case Watch was called after
a controller has already been started and if the source.Kind's cache was
either stopped or not available any longer. The leak was caused by the
watches internal slice holding on to all references to each watch ever
issued (and their respective caches).
/milestone v0.6.x
> [0.6] :bug: Controller.Watch() should not store watches if already started

- pkg/internal/controller/controller.go
- pkg/internal/controller/controller_test.go
The controller internal struct holds a list of watches
(as []watchDescription) when someone calls .Watch() to then start the
watches and informers once we're ready to call Start().
This behavior caused a memory leak in the case Watch was called after
a controller has already been started and if the source.Kind's cache was
either stopped or not available any longer. The leak was caused by the
watches internal slice holding on to all references to each watch ever
issued (and their respective caches).
/milestone v0.5.x
> [0.5] :bug: Controller.Watch() should not store watches if already started

- pkg/builder/controller.go
- pkg/builder/controller_test.go
The logger in the `Builder` struct is not used anywhere. Instead we need to set it in the controller options.
> 🐛 Fix builders WithLogger method

- pkg/webhook/admission/response.go
- pkg/webhook/admission/response_test.go
[Warnings](https://kubernetes.io/blog/2020/09/03/warnings/#admission-webhooks) have been introduced with K8s 1.19. This allows people who are running webhooks to send a warning message if there is something wrong with a resource (eg not following best practice) that is not a fatal error.
This PR adds a `WithWarnings` helper function that allows you to extend a response with warnings in an easy way. For example: 
```
return admission.Allowed("Resource OK").WithWarnings([]string{"Something wasn't quite right"})
```
Not sure if this is a majorly required helper since people could easily write one themselves, though I thought it could be a useful helper and it only took five minutes to prep, so thought I'd raise the code for discussion, let me know what y'all think.
> ✨  Allow admission responses to send warnings

- designs/move-cluster-specific-code-out-of-manager.md
A proposal based on https://github.com/kubernetes-sigs/controller-runtime/pull/950
/assign @mengqiy @vincepri @estroz
> :running: Proposal to extract cluster-specifics out of the Manager

- pkg/builder/webhook_test.go
- pkg/envtest/webhook.go
- pkg/manager/internal.go
- pkg/webhook/server.go
- pkg/webhook/server_test.go
- pkg/webhook/webhook_suite_test.go
This ensures that the webhook server is both threadsafe & "start-safe"
-- i.e. you can register webhooks after starting the server.  While this
is generally not a common pattern, be allow runnables to be added to the
manager after start, so it makes sense to do the same with hooks & the
server.
Fixes #1148 
/kind bug
> :bug: Ensure that webhook server is thread/start-safe

- pkg/builder/controller.go
- pkg/builder/controller_test.go
Added error checks for the multiple calls of For() on the apiType. Currently, it silently ignores the first apiType and take the second apiType as reconciliation object. This should throw an error that multiple apiType are not allowed for reconciliation.
Fixes #1173
> :sparkles: Add error check for multiple apiTypes as reconciliation object

- pkg/controller/controllerutil/controllerutil.go
- pkg/controller/controllerutil/controllerutil_test.go
This patch introduces a variation on the `controllerutil.CreateOrUpdate` function named `CreateOrPatch`. Instead of issuing update calls, the new function uses a patch to perform a more surgical update to the remote data. Additionally, the implementation relies on logic similar to the [`patch.Helper`](https://github.com/kubernetes-sigs/cluster-api/blob/master/util/patch/patch.go) mechanics from Cluster API. The resource is converted to unstructured data first in order to patch the resource and any potential status separately.
Two new OperationResult values were added:
1. `OperationResultUpdatedStatus` - the resource and its status were updated
2. `OperationResultUpdatedStatusOnly` - only the status was updated
There are tests implemented for `CreateOrPatch` that follow those implemented …
> ✨CreateOrPatch

- pkg/client/fake/client.go
This PR removes the long deprecated function from the fake client, and replaces it with the one that requires a scheme
> :seedling:  Un-deprecate NewFakeClient

- pkg/builder/controller.go
- pkg/builder/controller_test.go
When no reconciliation type is provided in the For(...) function to the Builder, it used to panic. Added the error handling if no apiType is provided in the For(...) function.
Fixes #1181
> :bug: add error check when no apiType is provided for reconciliation

- pkg/client/apiutil/dynamicrestmapper.go
- pkg/client/apiutil/dynamicrestmapper_test.go
Fixes #1120 
This PR fixes the DynamicRESTMapper's behaviour when it is rate limited:
Instead of returning `ErrRateLimited`, it now directly returns the `meta.NoKindMatchError` / `meta.NoResourceMatchError` given by the underlying mapper. This way, existing controller code using `meta.IsNoMatchError` works as expected also in the case when the RESTMapper is rate limited.
**This is breaking ⚠️  because:**
- the `DynamicRESTMapper` does now return a `NoKindMatchError`/`NoResourceMatchError` instead of `ErrRateLimited` in case the resource doesn't exist and it was rate limited
- `ErrRateLimited` and `DelayIfRateLimited` are removed, as they aren't needed anymore
**Additional notes:**
The given rate limit can now be seen as an agreement on how often the mapper should refresh its cache (at …
> ⚠️ DynamicRestMapper: return NoMatchError when resource doesn't exist

- pkg/handler/enqueue_mapped.go
This is a follow-up from a previous change to the handler package that
deprecated the old handler.ToRequestFunc in favor of
EnqueueRequestsFromMapFunc.
While we still want to prefer using EnqueueRequestsFromMapFunc, this
change also exposes the type of MapFunc signature expected. Users can
use this type to test their own mappers in unit tests.
> 🌱 Expose handler.MapFunc to allow implementers to test mappers

- pkg/internal/controller/controller.go
During a code walkthrough noticed that oddly the reconcileHandler was
returning false and stopping the worker entirely when an error is
returned from the reconciler. This change removes the return boolean
from reconcileHandler altogether and a worker is now only stopped when
the queue is shutdown.
/assign @alvaroaleman @ncdc @DirectXMan12
> 🐛 Controller reconcileHandler shouldn't stop a worker on error

- pkg/builder/controller.go
- pkg/builder/controller_test.go
- pkg/builder/webhook_test.go
- pkg/cache/cache.go
- pkg/cache/cache_test.go
- pkg/cache/informer_cache.go
- pkg/cache/informer_cache_unit_test.go
- pkg/cache/informertest/fake_cache.go
- pkg/cache/internal/cache_reader.go
- pkg/cache/multi_namespace_cache.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/dryrun.go
- pkg/client/example_test.go
- pkg/client/fake/client.go
- pkg/client/interfaces.go
- pkg/client/object.go
- pkg/client/split.go
- pkg/client/typed_client.go
- pkg/client/unstructured_client.go
- pkg/controller/controllerutil/controllerutil.go
- pkg/controller/controllerutil/controllerutil_test.go
- pkg/event/event.go
- pkg/handler/enqueue_mapped.go
- pkg/predicate/predicate.go
- pkg/predicate/predicate_test.go
- pkg/source/internal/eventsource.go
- pkg/source/source.go
- pkg/source/source_integration_test.go
This change introduces two interfaces: client.Object and
client.ObjectList.
These interfaces are now used throughout the codebase, more specifically
in the client.
> ⚠ Introduce and use client.Object and client.ObjectList

- VERSIONING.md
This adds a few CR-specific notes around versioning and compatibility,
mainly to emphasize the answer to the "what client-go version can I use"
question.
> :book: Be more specific about compat in VERSIONING

- alias.go
Renames the current (unreleased at the time of writing)
LoggerFromContext to LoggerFrom, and adds a new alias named LoggerInto.
From a user standpoint these new aliases are really clear and
straightfoward, example:
```go
func (r *Reconciler) Reconcile(ctx context.Context, req ctrl.Request) {
log := ctrl.LoggerFrom(ctx)
```
This reads much better than ctrl.LoggerFromContext(ctx) which repeats
the context.
Another use case that this change solves is to enrich the logger with
more values, example:
```go
ctx = ctrl.LoggerInto(ctx, log.WithValues(...))
```
allows the ctx to still be the de-facto context, and the logger for the
inner reconciler function to still only accept ctx, without adding any
more parameters.
/assign …
> 🌱 Add ctrl.{LoggerFrom, LoggerInto}

- pkg/controller/controller.go
- pkg/internal/controller/controller.go
Adds a new GetLogger method required on the controller interface. For
folks using controller without managers it's a good way to get a logger
pre-filled with information about the controller itself and avoid
duplication.
> :seedling: Add controller.GetLogger

- pkg/log/zap/zap.go
Currently, setting the encoding is pretty annoying and requires to
import two more packages apart from log/zap:
```
encoderConfig := uberzap.NewProductionEncoderConfig()
zap.New(zap.Encoder(zapcore.NewJSONEncoder(encoderConfig)))
```
This PR adds a JSONEncoder and ConsoleEncoder opt to simplify this
> :sparkles: Zap: Add JSONEncoder and ConsoleEncoder opts

- designs/move-cluster-specific-code-out-of-manager.md
- example_test.go
- examples/builtins/main.go
- examples/crd/main.go
- examples/scratch-env/main.go
- go.mod
- go.sum
- pkg/builder/controller_test.go
- pkg/builder/example_test.go
- pkg/builder/example_webhook_test.go
- pkg/builder/webhook_test.go
- pkg/controller/controller_integration_test.go
- pkg/controller/controller_test.go
- pkg/envtest/webhook_test.go
- pkg/internal/recorder/recorder_integration_test.go
- pkg/manager/example_test.go
- pkg/manager/internal.go
- pkg/manager/manager.go
- pkg/manager/manager_test.go
- pkg/manager/signals/signal.go
- pkg/manager/signals/signal_test.go
- pkg/webhook/example_test.go
This change reshuffles how the manager accepts and operates on
a context. With this change, the user experience is greatly improved,
users can now use `ctrl.SetupSignalHandler()` to create a context, enrich
it if they want to, and pass it to `manager.Start`.
In addition, this PR changes how the context and stop channel are
handled internally to ensure proper cancellation.
> :warning: Propagate context on Manager.Start(...)

- pkg/envtest/crd.go
- pkg/envtest/envtest_suite_test.go
- pkg/envtest/envtest_test.go
- pkg/envtest/helper.go
- pkg/envtest/server.go
- pkg/envtest/webhook.go
This is a follow-up from an earlier PR that introduced the
client.Object interface. While working in Cluster API downstream,
noticed that this was missing from the envtest codebase.
> :seedling: Use client.Object interface in envtest

- alias.go
> 📖 Add more details for what's included in a logger

- pkg/handler/enqueue_mapped.go
- pkg/handler/eventhandler_test.go
- pkg/handler/example_test.go
We updated the handlers MapObject type to not include a metav1.Object
and a runtime.Object representation of the same object but instead a
client.Object, which is a union of the two above.
The only reason for the MapObject type to exist in the first place
though was to hold these two fields. Now that there is only the
client.Object left, we can use that directly and get rid of the
MapObject type.
> :warning: Handler: Remove MapObject type and use client.Object directly

- pkg/client/fake/client.go
This PR makes sure `tracker.Upgrade` uses the gvk from scheme for `AllowUnconditionalUpdate` and `AllowCreateOnUpdate` in case `TypeMeta` is not defined on the obj
Fixes: https://github.com/kubernetes-sigs/controller-runtime/issues/1212
> 🐛 Tracker upgrade should use gvk from scheme

- .golangci.yml
- pkg/builder/controller.go
- pkg/builder/controller_test.go
- pkg/builder/example_test.go
- pkg/builder/options.go
- pkg/cache/cache_test.go
- pkg/cache/internal/deleg_map.go
- pkg/cache/internal/informers_map.go
- pkg/client/apiutil/apimachinery.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/metadata_client.go
This introduces metadata-only support (PartialObjectMetadata) to the client, cache, and controller builder.  It works much like unstructured does, with an end-use of:
```go
.Owns(&corev1.Pod{}, builder.OnlyMetadata)
// or
.Owns(&metav1.PartialObjectMetadata{/* GVK for corev1.Pod filled out here */})
// ...
var pods metav1.PartialObjectMetadataList
pods.SetGroupVersionKind(corev1.SchemeGroupVersion.WithKind("PodList"))
cl.List(ctx, &pods, client.MatchingLabels{...})
```
Note that like unstructured, the caches are *completely* separate -- asking for an unstructured object or concrete object will end up constructing a separate cache.
Fixes #1159
> :sparkles: metadata-only watches

- pkg/client/namespaced_client.go
- pkg/client/namespaced_client_test.go
This PR adds a namespace enforcing wrapper for client.Client.
This helps while dealing with namespace-scoped objects, where the
namespace value need not be specified in every operation.
This PR addresses the issue: #1073
> :sparkles: Add namespace enforcing wrapper for client.Client

- pkg/client/interfaces.go
- pkg/controller/controllerutil/controllerutil.go
This change removes the need to get an accessor from the runtime object,
because the object interface already has all the information needed.
It also removes the need to return an error, which makes it a little
easier to use.
> :warning: client.ObjectKeyFromObject now uses client.Client

- pkg/client/object.go
It was brought to my attention that the relationship between
client.Object and runtime.Object isn't particularly clear to folks who
are not used to working in the guts of client-go & apimachinery, so this
adds some docs to helpfully clarify and provide examples.
> :book: Improve docs for client.Object

- pkg/client/client.go
Before this change, passing an `unstructured.UnstructuredList` to
`client.List()` would erroneously delegate to the typed client, causing an error
if the target type isn't registered with the client's scheme, violating the
purpose of using `unstructured`.
This patch fixes the client so that the `unstructured.UnstructuredList` is
delegated to the internal unstructured client.
> 🐛 Fix use of `UnstructuredList` with unregistered typed

- pkg/builder/controller.go
- pkg/builder/controller_test.go
- pkg/builder/options.go
This change allows builders to use builder.OnlyMetadata when creating
extra watches with .Watches(...). The code inspects the passed
source.Source, and if it's of type *source.Kind, it calls the internal
project method that allows to use metav1.PartialObjectMetadata in
mapping functions.
/assign @alvaroaleman @DirectXMan12 
> :sparkles: Allow to use builder.OnlyMetadata option with Watches

- alias.go
This adds an alias for using ComponentConfig deferred file loader. This also helps to keep the same number of imports in `main.go` while configuring https://github.com/kubernetes-sigs/kubebuilder/issues/722
Closes #1243 
> ✨ ComponentConfig alias for cfg.File()

- alias.go
- pkg/builder/controller.go
Change built-in logging keys to be consistent with https://github.com/kubernetes-sigs/controller-runtime/blob/master/TMP-LOGGING.md#logging-structured-values-key-value-pairs
>  🌱 Use lowercase space separated keys

- pkg/config/config.go
This changes the deferred file loader loading error handling to return the file name for easier debugging.
Fixes #1250 
> ✨ Updating Component Config error messages

- TMP-LOGGING.md
- pkg/internal/controller/controller.go
This https://github.com/kubernetes-sigs/controller-runtime/pull/1054/files#diff-3f86588ef108e53ef346d3223ca106ccaa8efe72cb1055489665d7675f3da7b4R242 degaded the log level for the Reconcile implementation.
Then this completely remove the error logging https://github.com/kubernetes-sigs/controller-runtime/pull/1096/files#diff-3f86588ef108e53ef346d3223ca106ccaa8efe72cb1055489665d7675f3da7b4L242
When developing new controllers feels counterintuitive that controller runtime eats the error returned by the Reconcile implementation.
This proposes to log the error and let developers to create an additional log in the implementation if they choose to.
>  🌱 Add back error logging for Reconcile implementation

- pkg/builder/controller.go
- pkg/builder/controller_test.go
- pkg/builder/example_test.go
- pkg/builder/options.go
- pkg/cache/cache_test.go
- pkg/cache/internal/deleg_map.go
- pkg/cache/internal/informers_map.go
- pkg/client/apiutil/apimachinery.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/metadata_client.go
Add support for metadata-only watches to release-0.6. Note, this was a manual backport, as there were several conflicts when trying to cherry-pick. All the tests should be passing, but I encourage reviewers to 👀 carefully. Thanks!
From the original PRs:
#1174:
This introduces metadata-only support (PartialObjectMetadata) to the client, cache, and controller builder. It works much like unstructured does, with an end-use of:
```go
.Owns(&corev1.Pod{}, builder.OnlyMetadata)
// or
.Owns(&metav1.PartialObjectMetadata{/* GVK for corev1.Pod filled out here */})
// ...
var pods metav1.PartialObjectMetadataList
pods.SetGroupVersionKind(corev1.SchemeGroupVersion.WithKind("PodList"))
cl.List(ctx, &pods, client.MatchingLabels{...})
```
Note that like unstructured, the caches are completely separate …
> ✨ Backport support for metadata-only watches to release-0.6

- pkg/predicate/predicate.go
- pkg/predicate/predicate_test.go
This PR introduces an `AnnotationChangedPredicate` that skips update events that have no change in the object's annotation.
This predicate complements the `GenerationChangedPredicate` introduced in #553, and is intended to be used in conjunction with it, as in the following example:
```go
Controller.Watch(
&source.Kind{Type: v1.MyCustomKind},
&handler.EnqueueRequestForObject{},
predicate.Or(predicate.GenerationChangedPredicate{}, predicate.AnnotationChangedPredicate{}))
```
This is mostly useful for controllers that need to trigger both when the resource's generation is incremented
(i.e., when the resource' `.spec` changes), or an annotation changes (e.g., for a staging/alpha API).
> ✨ Add predicate for annotations change on update event

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/example_test.go
- pkg/config/v1alpha1/types.go
- pkg/manager/manager.go
- pkg/manager/manager_test.go
This is a breaking change for an unreleased feature that will be rolled out in `0.7.0`. This renames `loader.GetControllerManagerConfiguration()` to `loader.Complete()`.
Fixes #1252
> ✨ rename GetControllerManagerConfiguration to Complete

- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
When changing the fakeclients constructors to take a `client.Object` we missed that its possible to initialize it with `ObjectLists` which do not fulfill that interface. Hence, reverting it back to `runtime.Object`.
> :warning: Fakeclient: Allow to pass ObjectLists to constructors

- pkg/client/client_test.go
- pkg/client/split.go
- pkg/manager/client_builder.go
- pkg/manager/manager.go
- pkg/manager/manager_test.go
- pkg/runtime/inject/inject_test.go
A long standing issue in controller runtime, the delegating client is
the default client that the manager creates. Whenever a user calls
Get/List on a typed object, the internal cache spins up an informer and
start watching *all* objects for that group-version-kind.
This change introduces the ability for the delegating client to take
a list of objects that should always hit the live api-server, and bypass
the cache.
We also offer the ability to build a manager.NewClientFunc with a new
builder that exposes the ability to mark which objects we want to be
uncached.
Marking this as ⚠ because it changes the signature of NewDelegatingClient, which can now return an error.
Related to #1222
> ⚠Add ability for the delegating client to avoid caching objects

- hack/check-everything.sh
- hack/setup-envtest.sh
- pkg/internal/testing/integration/internal/integration_tests/etcd_integration_test.go
Update k8s version in envtest for 0.7.0 release.
cc: @estroz (#1258)
> :sparkles: Update k8s version in envtest

- pkg/builder/controller.go
- pkg/builder/controller_test.go
- pkg/builder/example_test.go
- pkg/builder/options.go
- pkg/cache/cache_test.go
- pkg/cache/internal/deleg_map.go
- pkg/cache/internal/informers_map.go
- pkg/client/apiutil/apimachinery.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/metadata_client.go
- pkg/handler/enqueue_owner.go
This PR backports the metadata only watches to the release-0.5 branch in a non breaking change. The API is a bit different and I had to have some workarounds to make it work, but it seems that it should fit nicely with the rest of it.
In particular, given the lack of Options for the builder For, Watches, and Owns, we support metadata-only types by encapsulating them in a custom internal type, which then gets projected to the actual type when the manager gets built.
/milestone v0.5.x
/assign @alvaroaleman @DirectXMan12 @ncdc
> ✨ Backport release-0.5: Support metadata-only watches 

- pkg/envtest/server.go
- Allow passing the assets path bin via the env config
```go
By("bootstrapping test environment")
testEnv = &envtest.Environment{
CRDDirectoryPaths: []string{filepath.Join("..", "..", "config", "crd", "bases")},
BinaryAssetsDirectory: "filepath.Join("..", "bin")" // See here
}
```
The priority here is: 
0. the specific envvars for each binary: `TEST_ASSET_KUBE_APISERVER`, `TEST_ASSET_ETCD`, `TEST_ASSET_KUBECTL`
1. the path for all env var: `KUBEBUILDER_ASSETS `
2. the value set via the structure in this case `Environment{}` 
3. the default value which is currently `/usr/local/kubebuilder/bin`
**Motivation**
Allow passing the bin path to simplify the required implementation to config the EnvTest when the bin is not in the default path. Currently, if a developer would like …
> :sparkles: Allow passing the assets path bin via the env config

- pkg/cache/internal/deleg_map.go
It seems we are missing a wait for cache sync function for the metadata cache. I think we should do to this cache whatever we do to the unstructured one
Descriptiveness check, begone!
> :bug: Wait for metadata cache to sync

- pkg/manager/manager.go
Related to https://github.com/kubernetes-sigs/controller-runtime/issues/1185
This PR is really a very minor fix, just a typo in the `manager.go` file comments.
> :book: fix minor typo for the GracefulShutdownTimeout field comments

- pkg/internal/controller/metrics/metrics.go
The current metric uses Prometheus [default bucket](https://pkg.go.dev/github.com/prometheus/client_golang/prometheus#pkg-variables) for reconcile time histogram. This bucket is
not sufficient to reason about the percentile of requests which take less than x seconds when x falls outside
the bucket of 10 secs(current last bucket). It's also hard to infer when the reconcile loops are fairly fast, as mentioned in
this issue: kubernetes-sigs#258.
This PR attempts to define explicit buckets for the metrics, values are chosen based on the API-server
request latency defined here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go#L103.
The default Prometheus histogram buckets have also been added(wherever missing) to ensure backward …
> :seedling: Specify buckets for "controller_runtime_reconcile_time_seconds" histogram metrics

- pkg/cache/internal/informers_map.go
- pkg/client/apiutil/apimachinery.go
- pkg/client/client.go
- pkg/client/client_cache.go
Signed-off-by: Siyu Wang <FillZpp.pub@gmail.com>
Use `application/vnd.kubernetes.protobuf` as content-type if it is possible, currently for those native resources defined in client-go.
> :warning: Use application/vnd.kubernetes.protobuf as content-type if possible

- pkg/client/apiutil/apimachinery.go
Depending on the API, the SchemeBuilder might not be exported. Since we
only care about its AddToScheme, take that as argument instead.
/assign @vincepri 
/cc @FillZpp
> :running: AddToProtobufScheme: Take AddToScheme, not Schemebulilder

- pkg/cache/internal/deleg_map.go
This PR backports the metadata cache sync fix, https://github.com/kubernetes-sigs/controller-runtime/pull/1276, to the release-0.6 branch in a non breaking change.
> ✨ Backport release-0.6: Wait for metadata cache to sync

- pkg/cache/internal/deleg_map.go
This PR backports the metadata cache sync fix, https://github.com/kubernetes-sigs/controller-runtime/pull/1276, to the release-0.5 branch in a non breaking change.
> ✨ Backport release-0.5: Wait for metadata cache to sync

- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
- pkg/runtime/inject/inject_test.go
This change allows us to iterate on the fake client without relying on
a small set of arguments passed to
NewFakeClient/NewFakeClientWithScheme.
The new builder accepts a variety of options to initialize the fake
client, including the scheme.
Because the builder seems more of a long term solution, I've marked the
older functions as deprecated in favor of NewClientBuilder.
Note: I dropped the "Fake" prefix given that it stutters with the
package name.
> :sparkles: Add fake.NewClientBuilder to build new fake clients

- pkg/builder/webhook_test.go
- pkg/webhook/admission/decode_test.go
- pkg/webhook/admission/http.go
- pkg/webhook/admission/http_test.go
- pkg/webhook/admission/multi.go
- pkg/webhook/admission/multi_test.go
- pkg/webhook/admission/response.go
- pkg/webhook/admission/response_test.go
- pkg/webhook/admission/validator.go
- pkg/webhook/admission/validator_test.go
- pkg/webhook/admission/webhook.go
- pkg/webhook/admission/webhook_test.go
As per [this review](https://github.com/kubernetes-sigs/controller-runtime/pull/1233#pullrequestreview-534898408) on #1233:
>currently, v1 and v1beta1 are identical [...], which means that we can safely just deserialize v1beta1 into a v1 struct and call it a day, without the duplication
This PR captures the essence of that comment.
> :warning: pkg/webhook/admission: upgrade v1beta1 admission types to v1

- pkg/client/client.go
- pkg/client/client_test.go
After adding the metadata only watch and client support, the List object
was type checking on `Unstructured` instead of `UnstructuredList`.
Now! "Why were the tests passing??" one might ask, it seems that even
though our tests had some using UnstructuredLists and querying against
List, the objects we were asking (appsv1/Deployments) are core objects
that are usually included in the default client-go scheme.Scheme.
For the above reason, the internal `typedClient` was able to make the
request to the API server and convert the list of object back to
UnstructuredList.
/milestone v0.5.x
> 🐛 client.List should check on UnstructuredList, not Unstructured

- pkg/client/client.go
- pkg/client/client_test.go
After adding the metadata only watch and client support, the List object
was type checking on `Unstructured` instead of `UnstructuredList`.
Now! "Why were the tests passing??" one might ask, it seems that even
though our tests had some using UnstructuredLists and querying against
List, the objects we were asking (appsv1/Deployments) are core objects
that are usually included in the default client-go scheme.Scheme.
For the above reason, the internal `typedClient` was able to make the
request to the API server and convert the list of object back to
UnstructuredList.
/milestone v0.6.x
/assign @alvaroaleman @DirectXMan12
> :bug: client.List should check on UnstructuredList, not Unstructured

- pkg/client/client_test.go
After adding the metadata only watch and client support, the List object
was type checking on Unstructured instead of UnstructuredList.
Now! "Why were the tests passing??" one might ask, it seems that even
though our tests had some using UnstructuredLists and querying against
List, the objects we were asking (appsv1/Deployments) are core objects
that are usually included in the default client-go scheme.Scheme.
For the above reason, the internal typedClient was able to make the
request to the API server and convert the list of object back to
UnstructuredList.
/assign @alvaroaleman @DirectXMan12
> 🌱 Add test that checks List works on UnstructuredList not in Scheme

- pkg/manager/internal.go
- pkg/manager/manager.go
- pkg/manager/manager_test.go
Before this PR, the manager injected the controller-runtime-internal logger into controllers, predicates and so on, that implemented the `inject.Logger` interface. This means, controllers and so on were provided with a logger which name is set to `controller-runtime.manager`.
I found this behaviour to be confusing, especially if you provided the manager with a custom logger via `manager.Options.Logger` (e.g. with a different top-level name).
With this PR, the manager injects its own logger or the default one, if none is specified.
> 🐛 Inject manager's logger instead of internal one

- pkg/webhook/admission/http.go
- pkg/webhook/admission/http_test.go
Specifying multiple `admissionReviewVersions` in a webhook config with `v1` as the first version causes untyped (no GVK) `AdmissionReview` responses to fail with an error like
```
failed calling webhook "mfoo.kb.io": expected webhook response of admission.k8s.io/v1, Kind=AdmissionReview, got /, Kind=
```
This error results from the API server [checking response type](https://github.com/kubernetes/apiserver/blob/v0.19.4/pkg/admission/plugin/webhook/request/admissionreview.go#L58-L61) for v1 but not v1beta1. By setting the `AdmissionReview` object's GVK to the request's type if it exists or defaulting to v1, the webhook handler can patch over this problem.
/kind bug
> :bug: pkg/webhook/admission: set GVK on AdmissionReview responses

- pkg/builder/builder_suite_test.go
- pkg/envtest/webhook.go
- pkg/internal/testing/integration/addr/manager.go
- pkg/internal/testing/integration/addr/manager_test.go
- pkg/internal/testing/integration/apiserver.go
- pkg/internal/testing/integration/internal/process.go
- pkg/internal/testing/integration/internal/process_test.go
- pkg/internal/testing/integration/internal/tinyca.go
This requires pre-filling LocalServingHost and possibly LocalServingExternalName with the right listen interface and external name so that the external control plane can reach the webhook server launched by envtest.
Using this successfully for local integration tests against kind and k3s. It does change some APIs but the only compat change is on addr.Suggest and that's explicitly an internal API so I think that's okay?
> ✨ Support for using both an external control plane and automatic webhooks together

- pkg/client/split.go
Currently, when we create a new delegating client and we force some
types to be uncached, we can only specify client.Object(s).
When these objects are passed to the delegating client, and their GVK is
matched against the internal map, the check doesn't take into account
that the client might be issuing a List call with a ObjectList instead
of a metav1.Object.
The proposed solution is taken from the discovery rest mapper, which
does the same ~hack. While it's not perfect, probably close to all
generated objects are going to have a list that has the "List" suffix,
that when removed gives back the original GVK.
If there are other solutions, happy to change this hack.
> :bug: Cache bypass should take into account List types

- pkg/webhook/admission/response.go
In admission v1, API server requires that Patch and PatchType are both
provided or none are provided.  Meanwhile, admission v1beta1 does not
have this kind of requirement.
In controller-runtime, PatchResponseFromRaw sets PatchType regardless
of the existence of patch.  If patch is empty, a response contains
only PatchType and API server does not like it.  Webhook call fails.
This change fixes this issue by not setting PatchType if patch is
empty.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/1295
> 🐛 Do not set PatchType if patch is empty

- pkg/manager/internal.go
Updates serveHealthProbes to use the same anonymous function pattern
that serveMetrics does for performing operations that necessitate
acquiring the controller manager's lock.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
> ✨ Use anonymous function for locking when serving health probes

- pkg/cache/internal/informers_map.go
- pkg/client/codec.go
Updates resouces to resources in pkg/client noConversionParamCodec.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
> ✨ Fix some typos

- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
Currently an object that is added to the tracker will not have a
ResourceVersion set. This can lead to tests that should fail with an
IsConflict error succeeding when:
* The object is added to the tracker
* The object allows UnconditionalUpdate, i.E. Update with an empty
ResourceVersion that will never conflict
* The code under test retrieves such an object and then does an Update
for it
As this change results in different ResourceVersions for tests it is
breaking.
> ⚠ Fakeclient: Set ResourceVersion when adding objects to the tracker

- pkg/log/log.go
The delegating Logger will cause a high number of memory allocations
when no actual Logger is set. This change makes us set a NullLogger
after 30 seconds if none was set yet to avoid that.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/1122
/assign @DirectXMan12 @vincepri
> 🐛 pkg/log: Set Log to NullLogger after 30 seconds

- pkg/cluster/client_builder.go
- pkg/cluster/cluster.go
- pkg/cluster/cluster_suite_test.go
- pkg/cluster/cluster_test.go
- pkg/cluster/internal.go
- pkg/manager/client_builder.go
- pkg/manager/internal.go
- pkg/manager/manager.go
- pkg/manager/manager_test.go
This change is the first step towards implementing the corresponding
[proposal][1]. It essentially consists of moving a bunch if code from
pkg/manager into pkg/cluster, slightly adjusting some tests in
pkg/manager and copying applicable tests from there into pkg/cluster.
It is not yet the full implementation, because the `Manager` will only
correctly start it's own cache and not other caches before starting the
remaining `Runnables`. This behavior matches current behavior when
building something that uses multiple caches and will be fixed in a
follow-up.
[1]: https://github.com/kubernetes-sigs/controller-runtime/blob/master/designs/move-cluster-specific-code-out-of-manager.md
> ✨ Move cluster-specifics from Manager into new pkg/cluster

- pkg/controller/controller.go
- pkg/internal/controller/controller.go
- pkg/internal/controller/controller_test.go
This PR allows users to configure timeout for cache syncs
while starting the controller.
Closes: #1219
> :sparkles: Allow configuring cache sync timeouts

- pkg/internal/controller/controller.go
This PR initializes the known reconciler metrics for a controller when the controller starts up (rather than waiting for a reconciliation to happen).
While there are ways with promql to work around missing metrics like this, it is a prometheus best practice to initialize all known metrics in advance. See: https://prometheus.io/docs/practices/instrumentation/#avoid-missing-metrics
Issue first reported here: https://github.com/operator-framework/operator-sdk/issues/4372
> ✨ initialize reconciler metrics when controller is started

- pkg/predicate/predicate.go
- pkg/predicate/predicate_test.go
Signed-off-by: Bruce Ma <brucema19901024@gmail.com>
This is a non-breaking feature :sparkles: .
Just as the title, a `LabelChangedPredicate` is introduced to trigger event on label change, if some extra specification information is carried through object's label, this predicate function will be useful.
> ✨ introduce LabelChangedPredicate to trigger event on label change

- pkg/log/log.go
- pkg/webhook/admission/response.go
This PR backports some bug fixes that have been merged to the mainline branch which are important to be included for the current release (v0.7.x). 
> :seedling: Backport bug fixes for v0.7.1 release

- pkg/cache/cache_test.go
- pkg/cache/internal/cache_reader.go
- pkg/cache/internal/informers_map.go
This PR makes the controller-runtime cache consistent with the behavior of the client when working with cluster-scoped resources. 
Closes #1323 
Current behavior:
When fetching a cluster-scoped resource using a direct client (e.g. `mgr.GetAPIReader`), the namespace in the object key is ignored. When fetching a cluster-scoped resource via the cache, the namespace key MUST be set to an empty string. Otherwise the cache will return a not found error.
Expected behavior:
When fetching a cluster-scoped resource via the cache, the namespace key is ignored, just like with a direct client. The APIReader and Cache behavior should be consistent.
> 🐛 ignore namespace key when getting cluster-scoped resources

- pkg/runtime/inject/inject.go
Deprecate `inject` interface
cc: @estroz
> :sparkles: Deprecate Inject interface

- pkg/webhook/admission/http.go
- pkg/webhook/admission/http_test.go
- pkg/webhook/admission/webhook.go
This closes #1333 and extends #549.
This non-breaking change introduces a new field on the webhook server registration, this allows you to add additional information to the request context from the `ServeHTTP` func. This is useful if you need to get information from the http.Request like parsing the request path for variables.
This example will write the request path back to 
```
type pathKeyType int
const pathKey pathKeyType = iota
func setPath(ctx context.Context, r *http.Request) context.Context {
return context.WithValue(ctx, pathKey, r.URL.Path)
}
// Get will return the new request details from the context
func getPath(ctx context.Context) string {
return ctx.Value(pathKey).(string)
}
mgr.GetWebhookServer().Register("/webhook", &webhook.Admission{
Handler: &fakeHandler{
fn: func(ctx …
```
> ✨ Adding WithContextFunc for webhook server to pass info to the handler

- hack/check-everything.sh
This adds both configfiles examples to the automated testing with `check-everything.sh`.
> ✨ Checking configfile examples on check_everything.sh

- pkg/client/client_test.go
- pkg/client/split.go
Based on https://github.com/kubernetes-sigs/controller-runtime/issues/615, it seems like there is intent to allow the DelegatingClient to cache unstructured objects. This is behavior that was possible to use before v0.7.0 by using the `NewClientFunc` manager option and creating a custom DelegatingClient.
IMO, this could be considered a regression, but since a large chunk of this code was restructured in v0.7.0, I'm not sure if dropping support for unstructured caching was intentional.
This PR adds a new boolean field to the NewDelegatingClientInput struct that allows users to opt-in to caching unstructured objects.
> 🐛 pkg/client: optionally allow caching of unstructured objects

- pkg/log/deleg.go
- pkg/log/log_test.go
For as long as the delegating loggers Fullfill wasn't called, it holds a
loggerPromise and that loggerPromise holds the same delegating logger.
Calls to With{Name,Field} and FullFill of such a loggerPromise and
delegatingLogger pair have to be serialized, because the former accesses
the actual logger and promise, while the latter sets and unsets them.
Furthermore, a call to With{Name,Field} of such a pair returns a new
pair that is attached to the parent pair by making the original promise
keep a reference to the new promise. Because of that, the aforementioned
serialization has to happen recursively for each pair.
https://github.com/kubernetes-sigs/controller-runtime/pull/1309 made this race more visible, because the defaulting of the logger controller-runtime does in the background …
> :bug: Fix a race in the delegating logger

- pkg/internal/controller/controller.go
- pkg/source/source.go
Because of an incorrectly used context, `source.Channel` gets shutdown almost immediately before it gets a chance to process any events. More details can be found in #1343.
Also fixes a minor bug in `source.Channel` where the destination append operation wasn't protected by a lock as it used to.
Fixes #1343
> :bug: Prevent source.Channel from shutting down immediately

- pkg/manager/internal.go
- pkg/manager/manager_test.go
This pr implements the second half of the ["Move cluster-specific code
out of the manager" proposal][0]: Making it start all caches before other
Runnables and not just the one of the main Cluster.
[0]: https://github.com/kubernetes-sigs/controller-runtime/blob/66537ca5b7439b06f2f3b08901640f934834c9a1/designs/move-cluster-specific-code-out-of-manager.md#L131-L132
> ✨ Manager: Start all caches before other Runnables

- pkg/manager/internal.go
During debugging a weird issue with some tests failing if they were
running too fast. In other words, calling Start() and Close() on
a manager too fast throws an error where the informers haven't been able
to sync, which then makes Start() fail with an error.
In an effort to improve this behavior, tried to use Elected() to wait
for leader election to start, which also waits for the cache.
During some debugging, this issue happened again and upon digging a bit
more it seems that the channel was closed before starting the runnables
in some cases.
This change reorders the close on cm.elected, which should fix the above
issue.
> :bug: Manager.Elected() should beclosed after runnables are started

- examples/builtins/controller.go
Fixes #1353 
Signed-off-by: rashmigottipati <chowdary.grashmi@gmail.com>
> ✨Fix context.TODO() in the example

- pkg/log/zap/zap.go
- pkg/log/zap/zap_test.go
- change name of var from `DestWritter` to `DestWriter`
Fixes: #1294
> 🌱 fix DestWritter var name typo

- pkg/log/zap/flags.go
- pkg/log/zap/zap.go
- pkg/log/zap/zap_test.go
This allows stack trace logging to be disabled for all but panic log entries.
The Zap `DisableStackTrace` config parameter (https://github.com/uber-go/zap/blob/master/config.go#L72) isn't available via the `Option` interface, so it's not possible (or at least I couldn't find a way) to disable it completely via a user-added flag.
Closes https://github.com/kubernetes-sigs/controller-runtime/issues/1035
> :sparkles: Allow panic as an option to -zap-stacktrace-level"

- pkg/log/deleg.go
- pkg/log/log_test.go
The delegatingLogger had a logger implementation embedded, calling any
method of that would race with FullFill(), which replaces the embedded
logger.
/cc @charith-elastic 
Can you verify this fixes all remaining races?
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/1359
> :warning: Fix some more races in the delegating logger

- pkg/source/source.go
- pkg/source/source_test.go
Previously, when we received from the channel in a channel source, we
didn't check if it was still open.  This lead to hotlooping and spamming
the source's handler/queue when the input channel is closed.
Now, we stop the source when the channel is closed, similarly to what
happens if the context is closed.
> :bug: Don't hotloop on channel source closure

- pkg/manager/internal.go
- pkg/manager/manager.go
This change introduces better syncronization between the leader election
code and the event recorder. Running tests with -race flag, we often saw
a panic on a closed channel, the channel was the one that the event
recorder was using internally.
After digging more through the code, it seems that we weren't properly
waiting for leader election code to stop completely, but instead we were
only calling the cancel() function asking the leader election to stop.
With this change, during a shutdown, we now wait for leader election to
finish up any internal task before we return and close an internal
channel. Only after leader election signals that the channel has been
closed, and  Run(...) has properly returned, we return execution to the
stop procedure, where the event recorder is then stopped. …
> 🐛 Fix a race condition between leader election and recorder

- pkg/manager/internal.go
- pkg/manager/manager.go
This change introduces better syncronization between the leader election
code and the event recorder. Running tests with -race flag, we often saw
a panic on a closed channel, the channel was the one that the event
recorder was using internally.
After digging more through the code, it seems that we weren't properly
waiting for leader election code to stop completely, but instead we were
only calling the cancel() function asking the leader election to stop.
With this change, during a shutdown, we now wait for leader election to
finish up any internal task before we return and close an internal
channel. Only after leader election signals that the channel has been
closed, and  Run(...) has properly returned, we return execution to the
stop procedure, where the event recorder is then stopped. …
> 🐛 [relase-0.8] Fix a race condition between leader election and recorder

- pkg/cluster/cluster.go
- pkg/internal/controller/controller.go
- pkg/manager/internal.go
- pkg/runtime/inject/inject.go
#1322 adds a bunch of logs to injection functions, which are used heavily by the manager and controller builder and therefore unavoidably print for users who aren't using injection code themselves. Until internal usage is stopped, these logs should be removed and static deprecation notices solely used.
Signed-off-by: Eric Stroczynski <ericstroczynski@gmail.com>
> :sparkles: revert injection deprecation logging until internal injection code use stops

- pkg/internal/testing/integration/internal/process.go
a temporary directory leak was found when running the tests
Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>
> 🐛: internal: fix a possible temporary directory leak

- pkg/internal/controller/controller.go
This is my first time to submit a patch via PR. I found a spelling error (at line 296) in the process of reading the code,
> :seedling: Fix typo namespace/Name to Namespace/Name

- pkg/internal/controller/controller_test.go
The additional tests verify controller implementation when `source.Channel` is passed.
Fixes #1368
Will also be helpful for discussing #1346
> :sparkles: Add tests in controller that use source.Channel

- .github/workflows/verify.yml
Currently, we do not run the PR title verification after pushes to a PR.
This means that if a PR with an invalid title is opened, then pushed to,
the check won't run and nothing will keep the PR from merging.
GitHub doesn't seem to be very explicit about the meaning of
synchronize, the only source I could quickly find is https://github.blog/2011-10-19-all-of-the-hooks/
Source for `synchronize` being a valid value: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
> :bug: Run verify workflow after pushes

- examples/builtins/validatingwebhook.go
fix typo in validatingwebhook example
> 📖  Typo: fix typo in validatingwebhook example

- pkg/manager/manager.go
- pkg/manager/manager_test.go
Cherrypick of https://github.com/kubernetes-sigs/controller-runtime/pull/1401
In pkg.LeaderElection.NewResourceLock we call rest.AddUserAgent
which resets the restcfgs useragent and sets it to the default one plus
a suffix. This resets whatever was originally set as UserAgent and since
we do not copy our restcfg before passing it in there, this leads to the
UserAgent being set to the leader-election one globally.
> :bug: [release-0.8]: Manager leader election: Don't reset restcfg UserAgent

- pkg/manager/manager.go
- pkg/manager/manager_test.go
In pkg.LeaderElection.NewResourceLock we call rest.AddUserAgent
which resets the restcfgs useragent and sets it to the default one plus
a suffix. This resets whatever was originally set as UserAgent and since
we do not copy our restcfg before passing it in there, this leads to the
UserAgent being set to the leader-election one globally.
> :bug: Manager leader election: Don't reset restcfg UserAgent

- pkg/builder/controller.go
This probably was used back in the days when the config was a property
of the controller, but is definitely unused today. The builder can just
directly call `mgr.GetConfig`, should it need one.
> :running: Builder: Remove unused restconfig attribute

- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
The fake client differs significantly from the real implementation.
With the real client implementation, upon the deletion of a resource,
when finalizers are set the DeletionTimestamp is filled with a non-null
value.
This triggers a number of reconciling loops for all controllers that then
can take the opportunity to inspect the resource being deleted, perform
the required cleaning actions and then update the resource by removing
their finalizers as the cleaning job have been done.
In the current implementation, the Delete function implements a straight
delete and hence triggers a false positive or negative test when trying
to run tests at the client level, without interacting with the objects.
For example:
```
client.CreateObject()
controller.Reconcile()
Expect(Something).To(BeDone()) …
```
> ⚠ Handle finalizers in the fake client

- pkg/manager/manager.go
The comment tries to capture more of the thoughts exchanged in #88.
It explains why a period sync happens. It also addresses two (common?) reasons for making the period shorter, and recommends an alternative.
The current comment includes this warning: "Change this value only if you know what you are doing." I found this unsatisfying, and wanted to add more context to the comment. I'm not an authority on the behavior/history of `SyncPeriod`, and I welcome feedback :slightly_smiling_face:.
> :book: Improve docs for manager.Options.SyncPeriod

- pkg/client/interfaces.go
- pkg/client/patch.go
- pkg/client/patch_test.go
- pkg/controller/controllerutil/controllerutil.go
Most uses of merge-patch will be for built-in types or kubebuilder-generated custom resources which have accessors for ResourceVersion. Using these with DeepCopyObject() is simple and fast.
```
name                            old time/op    new time/op    delta
MergeFrom/NoOptions               91.6µs ± 4%   107.3µs ±26%     ~     (p=0.417 n=7+10)
MergeFrom/NoOptions-2              112µs ±18%      88µs ±11%  -21.15%  (p=0.000 n=10+9)
MergeFrom/WithOptimisticLock       163µs ± 3%     121µs ± 3%  -25.66%  (p=0.000 n=10+8)
MergeFrom/WithOptimisticLock-2     137µs ± 4%     101µs ± 4%  -26.28%  (p=0.000 n=10+10)
name                            old alloc/op   new alloc/op   delta
MergeFrom/NoOptions               20.3kB ± 0%    20.3kB ± 0%     ~     (all equal)
MergeFrom/NoOptions-2 …
```
> ⚠️ Change client.Patch to take client.Object for performance

- pkg/client/client_test.go
- pkg/client/patch.go
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/1375
This PR adds `client.StrategicMergeFrom`.
The function is similar to `client.{MergeFrom,MergeFromWithOptions}`, but it creates a `strategic-merge-patch` instead of a `merge-patch`. See doc strings for more details about the differences of the two patch types and to figure out when to use which one.
Note, that strategic merge patches are [not supported by CRDs](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#advanced-features-and-flexibility).
> ✨ Add client.StrategicMergeFrom

- pkg/client/patch.go
I missed this in #1395 and so did the tests. 😬 This changes the variable declarations of `client.Apply` and `client.Merge` to ensure they satisfy `client.Patch`. The compiler caught the other types because their constructors return `Patch`.
> 🐛 Fix client.Apply and client.Merge to satisfy Patch

- pkg/client/client_test.go
- pkg/client/patch.go
Cherry-pick of https://github.com/kubernetes-sigs/controller-runtime/pull/1406:
This PR adds `client.StrategicMergeFrom`.
The function is similar to `client.{MergeFrom,MergeFromWithOptions}`, but it creates a `strategic-merge-patch` instead of a `merge-patch`. See doc strings for more details about the differences of the two patch types and to figure out when to use which one.
Note, that strategic merge patches are [not supported by CRDs](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/#advanced-features-and-flexibility).
> :sparkles: [release-0.8] Add client.StrategicMergeFrom

- pkg/cluster/cluster.go
NewClient does not exist any more; callers use ClientBuilder instead
Fixes #1412
> :book: Fix reference in comment

- examples/scratch-env/main.go
Print out config options for webhooks (host, port, cert dir) that are needed in order to run a webhook server that communicates with the scratch env API server
> :bug: Print webhook config options from scratch-env example
