pkg/handler/enqueue.go
pkg/handler/enqueue_mapped.go
pkg/handler/enqueue_owner.go
pkg/handler/eventhandler_test.go

This avoids race conditions where extra reconciles can happen rarely.
I still think https://github.com/kubernetes/kubernetes/pull/99185 is a better solution but failing that, here is a "userspace" solution.

✨ Deduplicate events before sending them into the workqueue.

---

pkg/controller/controller_test.go
pkg/internal/controller/controller.go
pkg/internal/controller/controller_test.go

Currently, the controller will instantly shutdown and return when its
context gets cancelled, leaving active reconciliations be. This change
makes it wait for those before finishing shutdown.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/1424

:bug: Controller: Wait for all reconciliations before shutting down

---

pkg/envtest/crd.go
pkg/envtest/envtest_test.go

Reproduces easily under load, e.G. by running `for s in $(seq 1 10); do go test ./pkg/envtest & done`. Doesn't reproduce for me with this patch.

:bug: Deflake should update CRDs if already present in the cluster

---

pkg/internal/controller/controller_test.go
pkg/source/source.go
pkg/source/source_test.go

So far, timing out the cache sync in most realistic scenarios didn't work,
bceause source.Kind gets an already started cache from the Manager. A
cache that is already started will block forever on GetInformer which we
called in source.Kinds start and not its WaitForSync. The context passed
to Start however defines the entire lifecycle of the Source, not the
Start timeout.
This change makes source.Kind call GetInformer in Start but in a new
go routine and WaitForSync just wait for that to finish or for its
context to be cancelled. This preserves the existing semantic of
starting in Start but waint for ready in WaitForSync.
/cc @varshaprasad96 @estroz @vincepri 
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/1346

:bug: Fix cache sync timeout functionality

---

pkg/envtest/server.go

fix the typo of `UseExistingCluster` field to accommodate the godoc convention

🐛fix: fix the typo of `UseExistingCluster` comment

---

pkg/certwatcher/certwatcher.go
pkg/certwatcher/certwatcher_suite_test.go
pkg/certwatcher/certwatcher_test.go
pkg/certwatcher/doc.go
pkg/certwatcher/example_test.go
pkg/webhook/server.go

Per #1292 this exports the `certwatcher` package for use with other packages, for example custom `Runnable`'s passed into a manager.
Closes #1292

🌱 Adding certwatcher as an external package

---

pkg/internal/recorder/recorder.go

This change solves a race condition when the manager is shutting down
and reconcilers are still in the process of sending events through the
recorder. If the shutdown timeout is hit too early, the event recorder
panics because we're still trying to send events through the recorder.
To avoid this issue, we introduce a RWMutex between the provider and
event recorder. When the broadcaster is shutdown, events are now
dropped.

:bug: Event recorder should not send events when broadcaster is stopped

---

README.md

The links in the README point to v0.1.12. The new links point to v0.8.x and forward.

📖 Update godoc links

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

The fake client will currently error out of given a Kind in an
UnstructuredList that doesn't end with list. This is different from what
we do in the actual client, where we tolerate that:
https://github.com/kubernetes-sigs/controller-runtime/blob/10ae090c1d3ac0c560dfa1a29b2517eb8d74442b/pkg/client/unstructured_client.go#L204
This change brings the fake client in line with the real client.
Related: The comments on https://github.com/kubernetes-sigs/controller-runtime/issues/702 although the Bug itself is about something else.

:bug: Fakeclient: Do not require ListKind

---

pkg/client/client.go
pkg/client/interfaces.go
pkg/client/watch.go
pkg/client/watch_test.go

This change adds a new WithWatch interface and implementation to the
Client package. It is a superset of the existing Client interface that
additionally contains a Watch method. It is intended to be used by CLI
apps that need to wait for a condition to arise.
Because this is not intended to be used with controllers and might cause
confusion there, the existing interface and all references to it are
kept as-is.
The basic idea of adding this was discussed and agreed-on in the March 25th meeting.

:sparkles: Add ClientWithWatch for use in CLIs

---

designs/use-selectors-at-cache.md

The controller-runtime is caching all the resource instance even if not
all of them end up being reconciled, this design document describe a
proposal to that problem by use selectors at the ListWatch informers
mechanism.
This is related to https://github.com/kubernetes-sigs/controller-runtime/pull/1404

:seedling: Add a design document to filter cache by selectors

---

pkg/client/client.go
pkg/log/warning_handler.go

- Add a `WarningHandler` that writes to `stderr`
- Deduplicates warnings
- Highlight warning output with color when the outut supports it
Fix #1150 
/hold
/cc joelanford
- Currently, by default warnings are surfaced, should an option be provided to turn off the warnings if needed as illustrated [here](https://kubernetes.io/blog/2020/09/03/warnings/#customize-client-handling)?

✨ Surface API Server warnings in client

---

hack/setup-envtest.sh

Related to #1482 
Signed-off-by: Valentin Pichard <github@w3st.fr>

🌱 Add darwin arch condition for envtest script

---

pkg/log/zap/zap.go
pkg/log/zap/zap_test.go

This PR clarifies zap level vs. logr verbosity with a link to the zapr explanation of this difference, and test cases.
/kind documentation
Signed-off-by: Eric Stroczynski <ericstroczynski@gmail.com>

:sparkles: pkg/log/zap: clarify zap level vs. logr verbosity

---

pkg/webhook/admission/webhook.go
pkg/webhook/example_test.go
pkg/webhook/internal/metrics/metrics.go
pkg/webhook/server.go
pkg/webhook/server_test.go
pkg/webhook/webhook_integration_test.go
pkg/webhook/webhook_suite_test.go

This adds helper functions to setup webhooks server without a manager. It adds 
1. `webhook.Unmanaged` that creates a `webhook.Server` without a manager / cluster connection information
2. `admission.StandalonWebhook` that creates an `http.Handler` that can be run on any arbitrary Go HTTP server (`http.SeverMux`) rather than a `webhook.Server`)
Fixes #1255

✨ Simple helper for unmanaged webhook server

---

pkg/webhook/admission/admissiontest/doc.go
pkg/webhook/admission/admissiontest/util.go
pkg/webhook/admission/validator_test.go
pkg/webhook/admission/webhook.go
pkg/webhook/webhook_integration_test.go

Fixes a bug from https://github.com/kubernetes-sigs/controller-runtime/pull/1429 where `StandaloneWebhook` never injects  the scheme and refactors the FakeValidator so it can be used to test `StandaloneWebhook`

🐛 Actually inject the scheme in StandaloneWebhook

---

Makefile
hack/test-all.sh
pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/cache/internal/deleg_map.go
pkg/cache/internal/informers_map.go
pkg/cache/internal/selector.go

Controller-Runtime controllers use a cache to subscribe to events from
Kubernetes objects and to read those objects more efficiently by avoiding
to call out to the API. This cache is backed by Kubernetes informers.
The only way to filter this cache is by namespace and resource type.
In cases where a controller is only interested in a small subset of objects
(for example all pods on a node), this might end up not being efficient enough.
This change increase the "pkg/cache" interface adding the
"BuildWithOptins" function and the "Options.SelectorsByObject" option.
The SelectorsByObject restricts the cache's ListWatch to the desired
fields per GVK at the specified object, the map's value must implement
Selector [1] using for example a Set [2]
This is the implementation of the design document …

:sparkles: Add SelectorsByObject option to cache

---

pkg/builder/controller_test.go
pkg/cache/cache_test.go
pkg/cache/internal/informers_map.go
pkg/cache/internal/metadata_infomer_wrapper.go
pkg/client/apiutil/apimachinery.go
pkg/client/client.go
pkg/client/client_cache.go
pkg/client/client_test.go

Currently we have a bug that GVK information is not passed into mapping
functions when using the OnlyMetadata option in the builder. This patch
adds a wrapper that preserves the GVK information when events come in.
This issue is most likely caused by https://github.com/kubernetes/kubernetes/issues/80609
which we have been bumping into every once in a while here and there.
/hold
for further review

:bug: Metadata only objects should always preserve GroupVersionKind

---

pkg/controller/controllerutil/controllerutil.go
pkg/controller/controllerutil/controllerutil_test.go

If we would like to patch custom resource with some `Spec` fields and `Status` which are not empty, the controllerutil.CreateOrPatch patches `Spec` only fields, but any `Status` keep unchanged,
`result` returns `OperationResultUpdatedStatus` which means that both `Spec` and `Status` where updated
The reason why this happens is that the original `Status` of the object returned when the `Patch` procedure is exited and, as a result, no` Status` fields are updated
Fixes #1392

🐛 controllerutil.CreateOrPatch doesn't update not empty Status fields if Spec fields are specified

---

pkg/webhook/admission/webhook.go
pkg/webhook/example_test.go
pkg/webhook/server.go

This better documents the fact that `webhook.Server` requires valid TLS configurations and that `admission.StandaloneWebhook` requires the user to configure TLS on their own server.
Based on feedback from https://github.com/kubernetes-sigs/controller-runtime/pull/1429#discussion_r619719298

📖 Better document TLS requirements for webhook servers

---

pkg/manager/internal.go
pkg/manager/manager.go
pkg/manager/manager_test.go

This PR adds `pkg/manager.Options.WebhookServer` to allow external configuration of a webhook server. Currently there is no way to add a custom webhook server, since `Manager.Add()` will not set `controllerManager.webhookServer`. I am treating this as a bug since the manager's internals appear to allow external webhook configuration, but no code API was ever exposed to allow this.
/kind bug
Signed-off-by: Eric Stroczynski <ericstroczynski@gmail.com>

:bug: add manager.Options.WebhookServer so webhook server can be set

---

pkg/cache/cache_test.go
pkg/cache/multi_namespace_cache.go
pkg/client/namespaced_client.go
pkg/internal/objectutil/filter.go
pkg/internal/objectutil/objectutil.go

This PR modifies the multinamespacedcache implementation to:
- create a global cache mapping for an empty namespace, so that when
cluster scoped resources are fetched, namespace is not required.
- deduplicate the objects in the `List` call, based on
unique combination of resource name and namespace.
Closes: #1377
Closes: #1378
Signed-off-by: varshaprasad96 <varshaprasad96@gmail.com>

🐛  Modify multinamespaced cache to support cluster scoped resources

---

pkg/manager/internal.go
pkg/webhook/admission/multi.go
pkg/webhook/webhook_integration_test.go

**TL;DR**
Webhooks with `multiValidating` and `multiMutating` handlers currently fail to inject decoders into their sub-handlers, resulting in nil pointer panics. This PR is fixing it.
**Full description**
Before the change in https://github.com/kubernetes-sigs/controller-runtime/pull/1307, webhook method `webhook.InjectScheme` was called before `webhook.InjectFunc`, meaning that decoder intstantiation was happening before injecting it  by `webhook.InjectFunc`.
After that PR (specifically, the changes to `controllerManager.SetFields` in `pkg/manager/internal.go`) , the order has changed, and now `webhook.InjectFunc` gets called before `webhook.InjectScheme`, meaning that we  `webhook.InjectFunc` injects a `nil` decoder.
It appears that such re-ordering was anticipated, because in the …

🐛 fix nil Decoder in multiValidating and multiMutating handlers by implementing DecoderInjector

---

Makefile
hack/test-all.sh

This accidentally got disabled in
cd065bf2f63c3057db307990c21316483fa60ce8 under the assumption that the
CI entrypoint is the Makefile in an attempt to make this configurable.
Since the script is called `test_all.sh`, it is reasonable to assume it
always test verything. If ppl want something else, they can just add
another script/maketarget.
/assign @estroz @vincepri

:bug: Run unittests in CI

---

pkg/cache/cache_test.go
pkg/cache/internal/cache_reader.go
pkg/cache/multi_namespace_cache.go

Enabled list options in `List` implementation of `Reader` by the infromer cache in order to respect `client.Limit` if set. 
Fix #1422

✨ Cache-Backed Client: Support `listOpts.Limit`

---

pkg/manager/internal.go

Fixes a race condition between conversion webhooks to start and the cache being populated.

:bug: Webhook servers should always start before cache syncs

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

When adding client.WithWatch, we forgot to extend the fakeclient to also
support that, this change adds that support.
/assign @vincepri 
WDYT about changing the existing constructors to return a `client.WithWatch` vs adding a new set of constructors? I opted for extending them, because its easier to use, as `client.WithWatch` is a superset of `client.Client`, so will work as a replacement for both.

:bug: Fakeclient: Support WithWatch

---

tools/setup-envtest/env/env.go
tools/setup-envtest/env/env_suite_test.go
tools/setup-envtest/env/env_test.go

The path could have spaces, single quotes, etc in in, so this quotes the
path and escapes single quotes so we can export properly.
This is very relevant on darwin, where our default store path contains spaces (it includes "Application Support")

:bug: Quote path with -p env in envtest-setup

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

The objecttracker requires a List type to be registered for List to
work, hence we have to register UnstructuredList for the given list GVK
if an unstructuredList is targeted and nothing is registered yet.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/702
/assign @vincepri @estroz

:bug: Fakeclient: Fix List for unregistered type through unstructured

---

examples/tokenreview/main.go
examples/tokenreview/tokenreview.go
pkg/webhook/admission/http.go
pkg/webhook/authentication/authentication_suite_test.go
pkg/webhook/authentication/doc.go
pkg/webhook/authentication/http.go
pkg/webhook/authentication/http_test.go
pkg/webhook/authentication/response.go
pkg/webhook/authentication/response_test.go
pkg/webhook/authentication/webhook.go
pkg/webhook/authentication/webhook_test.go

This adds a new `pkg/webhook/authentication/` package for setting up the `ServeHTTP` func for the webook server to be able to handle `TokenReview.authentication.k8s.io/(v1,v1beta1)` requests.
Closes #1436

🌱 adding TokenReview.auth.k8s.io/v1 webhook support

---

pkg/envtest/crd.go
pkg/envtest/server.go
pkg/envtest/webhook.go

Before this change, the webhook code was patching mutation or admission
webhooks to point to the temporary URL and CA bundle generated when the
webhook server would start.
Conversion webhooks are handled at the CRD level in Kubernetes, and we
need to make sure to patch those client configurations as well.
This patch also unexports a lot of methods that should have been private
from the very beginning, so it's marked as a breaking change.
/assign @alvaroaleman @DirectXMan12

⚠️ Envtest should modify CRDs appropriately when using webhooks

---

pkg/envtest/crd.go
pkg/envtest/server.go

Conversion webhooks require the strategy to be set and all the supported
review versions.
This change also fixes an issue where the CABundle wasn't previously
base64 encoded.
Related: Need to spend some time to make sure the whole conversion webhooks are properly tested and run correctly within envtest. I'll wait for the 1.20 refactor that @DirectXMan12 is working on.

🐛 Envtest conversion mods should set strategy and review versions

---

pkg/envtest/crd.go
pkg/envtest/server.go

:bug: Envtest should enable conversion only for convertible GVKs

---

examples/scratch-env/main.go

Signed-off-by: Zou Yu <zouy.fnst@cn.fujitsu.com>

:seedling: Fix a typo

---

pkg/envtest/envtest_test.go
pkg/envtest/server.go
pkg/envtest/webhook.go
pkg/envtest/webhook_test.go
pkg/webhook/server_test.go

- Called the webhook server cleanup function
- Only ignore controlplane cleanup when using existing cluster
- Added test to check the cleanup for Webhook after `Stop()`
Fixes #1496

✨ Cleanup Webhook server setup

---

pkg/cache/multi_namespace_cache.go
pkg/internal/objectutil/objectutil.go

In the current implementation of multinamespaced cache, we look at
global namespace while listing objects from all namespaced. Global namespace
should not be looked at while fetching namespaced resources.

:bug: filter global namespace while looking for cluster scoped resources

---

pkg/internal/testing/controlplane/apiserver.go
pkg/internal/testing/controlplane/etcd.go
pkg/internal/testing/process/arguments.go
pkg/internal/testing/process/arguments_test.go

This adds structured arguments to the testing package, deprecating the old style where we do templating in favor of a fluent API with defaults that can be overridden.
This should make it easier for consumers to override individual arguments while not breaking the necessary flags that are required for the API server to function, and should make it easier for us to deal with upcoming changes in the k8s API server that requiring setting flags in some conditions, but not in others that are unrelated to the value of the flag (e.g. certain flags *must* be passed for older versions, but must *NOT* be passed for newer versions).
The new API looks roughly like:
```go
apiServer.Configure().
Disable("insecure-port").
Append("vmodule", "httplog.go=10").
Set("v", "5")
```
There's also a helper to …

✨ Structured args in Testing

---

pkg/cluster/cluster.go

The Cluster interface docs still had a reference to client, despite
being removed in aa1bfee605cea988a4a79e9021ad1d4334b09eb8.
This restores those docs to talk about NewClient instead.
Follow up from #1409

:book: Remove reference to ClientBuilder in Cluster docs

---

pkg/envtest/server.go

The underlying templated flag machinery was marked as deprecated as part
of the envtest refactor (see ddfdfdff7), but a couple fields in the
higher-level bits of envtest were not marked as deprecated.  This fixes
that.
See also #1541

:book: Mark all templated flag pieces as deprecated

---

pkg/webhook/server.go

Some environments have automated security scans that trigger
on TLS versions or insecure cipher suites. Setting TLS to 1.3
would solve both problems (setting to 1.2 only solves the former
as the default 1.2 cipher suites are insecure).
Default TLS minimum version of 1.0 remains.

✨ Allow TLS minimum version to be configured

---

pkg/internal/testing/controlplane/apiserver.go

Kubernetes 1.21 doesn't let us use a loopback address anymore, we can
let the api-server to figure out its own advertise address by removing
the argument.

:bug: Remove advertise-address from testenv api-server

---

hack/test-all.sh

🌱 Limit parallel go test executions on MacOS

---

go.mod
hack/check-everything.sh
hack/verify.sh
pkg/internal/flock/doc.go
pkg/internal/flock/flock_other.go
pkg/internal/flock/flock_unix.go
pkg/internal/testing/addr/manager.go
pkg/internal/testing/process/process.go

Envtest is often running in parallel when using go test, which spins up
multiple indipendent go test processes that cannot talk to each other.
The address suggestion code, mostly used to find an open port, can
cause port collisions and a race condition between different envtests
running at the same time.
This change switches the internal memory to use a file based system that
creates a file.

🌱  addr.Suggest should lock a file instead of memory

---

pkg/client/namespaced_client.go

🌱 cleanup Use objectutil IsAPINamespaced

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

`Delete` takes optional varargs comprising `DeleteOption`s. Previously fakeclient was validating that these could be run through `ApplyOptions`, but otherwise ignoring them.
With this commit, fakeclient will observe a `DeleteOption` specifying a `Precondition.ResourceVersion`, rejecting the deletion if the value does not match what's on the "server", bringing fakeclient's behavior more in line with a real client.
Note that, while technically a breaking change, any test that was relying on the previous behavior was already broken.
xref #832 / 25ef372 which did something similar for `Create` and `Update`. Major difference being that those methods do `ResourceVersion` matching by default, whereas `Delete` only does it if opted in via the `Precondition`.
/assign @vincepri 
/assign @mengqiy …

:warning: Fakeclient: Reject Delete with mismatched ResourceVersion

---

pkg/metrics/client_go_adapter.go

This metric has been deprecated since kube 1.14 and [turned off in kube 1.17](https://github.com/kubernetes/kubernetes/pull/83836). Stop registering it by default, but export the appropriate variables so
consumers can register it explicitly if they wish.
fixes #1423

:warning: Disable the `rest_client_request_latency_seconds` metric by default

---

TMP-LOGGING.md

there was a missing back-tick in the logging-level section of `TMP-LOGGING.md`, causing the information about log levels to be rendered incorrectly

📖  tmp-logging - fix markdown parsing error

---

doc.go

The package name has one more s

📖 Remove extraneous "s" in pkg/events in GoDoc

---

README.md

This PR adds godoc badge to README.
It used by many other go packages and, IMO, should improve discoverability of godocs).

📖 Add godoc badge to README

---

pkg/builder/doc.go

Rewording.
This corrects the info about builder package. It is needed to remove unnecessary word which causes confusion.

:book: Update doc.go

---

pkg/webhook/server.go
pkg/webhook/server_test.go

✨  add health check for webhook server

---

pkg/webhook/server.go
pkg/webhook/server_test.go

✨   make it possible to monitor if the webhook server has been started

---

pkg/cache/internal/informers_map.go

Signed-off-by: SHLOMITK@il.ibm.com <shlomitk@il.ibm.com>
Refers to https://github.com/kubernetes-sigs/controller-runtime/issues/244#issuecomment-882808482
This PR creates a namespace-scoped client in ListFunc and WatchFunc if there is a field selector for metadata.namespace and the global namespace is not specified.

✨Restrict namespace for list/watch based on field selectors

---

pkg/internal/flock/errors.go
pkg/internal/flock/flock_unix.go
pkg/internal/testing/addr/manager.go

🐛 Use non blocking file locking for flock library

---

pkg/certwatcher/example_test.go

Fix the typo that is in certwatcher package example.

🐛 fix the typo of certwatcher example test

---

pkg/webhook/server.go

My previous PR #1588 introduced a health check for the webhooks. The health check works as intended (it reports healthy when the webhook server was up), but it also produces tls handshake timeout errors and thus a lot of log messages like:
```bash
TLS handshake error from 127.0.0.1:42498: EOF
```
xref: https://kubernetes.slack.com/archives/CD6U2V71N/p1627643594012600

🐛 fix webhook health check tls handshake timeout errors

---

pkg/cache/cache_test.go
pkg/cache/internal/cache_reader.go

Previously, `Limit(n)` only looks at the first `n` objects. This could cause `List` to return less than `n` objects if other opts apply further filtering, even though there are more than `n` total number of objects matching the list options.
With the fix, `List` will loop until it collects `n` objects before returning.

:bug: Fix a bug with `Limit` list opt returning less than expected number of objects in the result.

---

pkg/internal/testing/controlplane/etcd.go

:bug: Envtest should try to allocate a port for etcd listenPeerURL

---

hack/test-all.sh
pkg/controller/controllerutil/controllerutil.go
pkg/internal/testing/controlplane/etcd.go

etcd 3.5 now supports disabling fsync; this change adds the new flag if
it's available which helps speed up envtest execution

🌱 Disable fsync on etcd envtest

---

.github/pull_request_template.md
FAQ.md
example_test.go
pkg/manager/internal.go

Link https://github.com/kubernetes/apiserver/blob/master/pkg/apis/config/v1alpha1/defaults.go is out of date since k8s.io/{apiserver,apimachinery}/pkg/apis/config is moved to  k8s.io/component-base/config.

:sparkles: chore: Fix bad urls

---

pkg/controller/controller.go
pkg/internal/controller/controller.go
pkg/internal/controller/controller_test.go

Add an option to recover panic for controller reconcile. It ensures that any panics raised by controller reconciler are converted to normal errors.
fixes #797

✨Add an option to recover panic for controller reconcile

---

pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/cache/internal/cache_reader.go
pkg/cache/internal/deleg_map.go
pkg/cache/internal/disabledeepcopy.go
pkg/cache/internal/informers_map.go

Signed-off-by: Siyu Wang <FillZpp.pub@gmail.com>
Add UnsafeDisableCacheDeepCopy into cache option to avoid deep copy during list.
fixes #1235 
@vincepri @alvaroaleman  I fully understand why the CacheReader calls `DeepCopyObject` for each object by default, the directly modification to underlying cache object is terrible. However, we can also provide an option for those people who really need to avoid deep copy.

✨ Add UnsafeDisableDeepCopy into cache option to avoid deep copy during get/list

---

pkg/internal/recorder/recorder.go
pkg/internal/recorder/recorder_test.go
pkg/leaderelection/leader_election.go

:sparkles: Construct typed clients directly
The pattern of constructing all the clients to get a
kubernetes.Interface, only to extract one or two typed clients has the
side-effect of importing a lot of packages that are otherwise
unneeded.
Avoid doing so by constructing the clients we need.
This isn't sufficient to remove all these extra dependencies (because
of the use of scheme.Scheme as default), but it is a step closer.

Construct the typed clients we need

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

Previously the fake client tried to decode the new object after patching to the object outside, which will cause some fields that should be removed in this patch remain in the object.
It should overwrite the object using reflect set, just like [the way in cache get](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/cache/internal/cache_reader.go#L99).

🐛 Fix object overwrite on patch for fake client

---

pkg/client/apiutil/apimachinery.go

We currently only set the NegotiatedSerializer when there is none set
yet. Unfortunately, various things will break if someone sets their own
in the rest config, hence always set it.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/1654

:bug: Unconditionally set NegotiatedSerializer

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

Currently, manipulating an object that is registered through
unstructured will break all subsequent List requests that include said
object. This happens because the tracker unconditionally saves objects but
it's List() assumes that what it finds can be assigned to the .Items slice
of an object produced through scheme.New(ListGVK).
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/1511
/assign @vincepri @joelanford

:bug: Fakeclient: Allow manipulating registered types through unstructured

---

pkg/envtest/webhook.go

Without this fix it's necessary to set TypeMeta in ValidatingWebhookConfiguration and MutatingWebhookConfiguration, e.g. like this:
```golang
gvk, err := apiutil.GVKForObject(webhook, scheme.Scheme)
if err != nil {
klog.Fatalf("failed to get gvk for ValidatingWebhookConfiguration %s", o.GetName())
}
webhook.SetGroupVersionKind(gvk)
```
With this fix we will just get the type from the "struct".
xref: https://github.com/kubernetes-sigs/cluster-api/pull/5249/files#r709959229

🐛  envtest: get gvk from hook struct instead of forcing set TypeMeta

---

pkg/envtest/crd.go

Without this PR the CRD installation did not work:
* it panic'ed when `.Conversion` is nil
* it didn't add the Conversion config (because of copy in the array)
* we also have to add `ConversionReviewVersions`
Notes:
* in our case the base CRD files don't have conversion as they are added via patches: https://github.com/kubernetes-sigs/cluster-api/blob/master/config/crd/bases/cluster.x-k8s.io_clusters.yaml
* this didn't occur with v0.9 because there the conversion webhook was modified via unstructured. (this changed through this PR: https://github.com/kubernetes-sigs/controller-runtime/commit/b5eeb7106d2360ba7e282c66cd7c65d6c57c6be4#diff-b6b1b02e41870fbffb46bc5880965e53a92a1c6807bb3fae0e8473154fb416a4)

🐛  envtest: fix CRD installation

---

pkg/internal/testing/certs/tinyca.go

Generating new RSA private keys each time a envtest environment is started, causes a lot of unnecessary cpu overhead.
This causes my tests to take longer to complete.
Instead, if we use ECC, key generation is much faster (see benchmark below for confirmation).
```go
package main
import (
"crypto/ecdsa"
"crypto/elliptic"
"crypto/rand"
"crypto/rsa"
"testing"
)
var (
rsaKeySize    = 2048
ellipticCurve = elliptic.P256()
)
func BenchmarkEcdsa(b *testing.B) {
for n := 0; n < b.N; n++ {
ecdsa.GenerateKey(ellipticCurve, rand.Reader)
}
}
func BenchmarkRsa(b *testing.B) {
for n := 0; n < b.N; n++ {
rsa.GenerateKey(rand.Reader, rsaKeySize)
}
}
```
```console
$ go test -bench=.
goos: linux
goarch: amd64
pkg: sigs.k8s.io/controller-runtime/temp
cpu: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz …
```

✨Switch from rsa to ecdsa in tinyca

---

pkg/client/config/config.go

client/config: use filepath.Join for loadingRules.Precedence.
It's not url path, actually file path.

🐛  client/config: use filepath.Join for loadingRules.Precedence

---

pkg/builder/webhook.go
pkg/builder/webhook_test.go
pkg/webhook/admission/defaulter_custom.go
pkg/webhook/admission/validator_custom.go
pkg/webhook/alias.go

This changeset allows our webhook builder to take in a handler any other
struct other than a runtime.Object.
Today having an object as the primary source of truth for both
Defaulting and Validators makes API types carry a lot of information and
business logic alongside their definitions.
Moreover, lots of folks in the past have asked for ways to have an
external type to handle these operations and use a controller runtime
client for validations.
This change brings a new way to register webhooks, which admission.For
handler any type (struct) can be a defaulting or validating handler for
a runtime Object.

:sparkles: Allow webhooks to register custom validators/defaulter types

---

pkg/source/source.go
pkg/source/source_test.go

This changeset adds the ability for a Manager to not fail immediately if
a wait.Backoff parameter is given as RunnableRetryBackoff in Options.
Currently, if a runnable fails to run the Start operation is never
retried which could cause the manager and all webhooks to stop and the
deployment to go into CrashLoopBackoff. Given the eventual consistency
of controllers and managers cooperating with other controllers or the
api-server, allow some sort of backoff by trying to start runnables
a number of times before giving up.

🌱 Source should retry to get informers until timeout expires 

---

pkg/internal/httpserver/server.go
pkg/manager/internal.go
pkg/manager/manager.go
pkg/manager/manager_test.go
pkg/manager/runnable_group.go
pkg/manager/runnable_group_test.go
pkg/webhook/server.go
pkg/webhook/webhook_integration_test.go

This changeset provides a series of improvements and refactors how the
manager starts and stops. During testing with Cluster API (a user of
controller runtime), folks noticed that the manager which runs a series
of components can deadlock itself when using conversion webhooks, or
health checks, or won't cleanly shutdown and cleanup all the running
controller, runnables, caches, webhooks, and http servers.
In particular:
- The Manager internal mutex didn't actually lock operations while the
manager was in the process of starting up. The manager internal
Start() implementation started off a series of goroutines internally
and then waits. Concurrent operations on the manager, like
AddHealthzCheck or AddReadyzCheck or AddMetricsExtraHandler …

⚠️  Refactor manager to avoid race conditions and provide clean shutdown

---

pkg/manager/internal.go

This PR test a simpler and possible cleaner solution to #1685.
We should test how this impact start time

🐛 Start web hooks first

---

pkg/manager/signals/signal.go

This PR is a small follow up to https://github.com/kubernetes-sigs/controller-runtime/pull/1205, which updated `SetupSignalHandler` in `pkg/manager/signals/signal.go` to use a context instead of a stop channel without updating the godoc for that function.

:sparkles: Fix SetupSignalHandler godoc

---

pkg/internal/testing/controlplane/apiserver.go

Move an unchecked pointer dereference into a checked block so the code doesn't panic when calling `Stop` on an `APIServer` instance that failed to start.

🐛 avoid panic in envtest by checking before dereferencing

---

pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/cache/internal/informers_map.go
pkg/cache/internal/selector.go

It is already possible to configure cache selectors per gvk, but it is
not possible to default this selector for all types. This change adds
that.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/1708

:sparkles: Allow configuring a default cache selector

---

pkg/cache/cache.go
pkg/cache/internal/informers_map.go

There were two bugs in this:
* The caches `BuilderWithOptions` defaulted the opts it got from the
manager with the ones it explicitly got, resulting in new fields
like `DefaultSelector` needing to explicitly be added there
* The caches `DefaultSelector` wasn't correctly used everywhere, because
there was code left that directly accessed the gvk -> selector map and
thus didn't get the default selector. Use a getter func rather than
the map internally, to make this impossible

:bug: Correctly pass cache options on

---

pkg/internal/testing/controlplane/plane.go

Currently if the api server fails to start etcd process will be up
the next time ControlPlane.Start() is called, they will both have the
same listening address which will make the new etcd instance fail to
start.
The controlplane object will also be in an incomplete state
so calling ControlPlane.Close() will panic.

:bug: Cleanup if envtest controlplane fails to start

---

FAQ.md
README.md
designs/README.md
designs/component-config.md
doc.go
pkg/client/fake/client.go
pkg/controller/controllerutil/controllerutil.go
pkg/log/deleg.go
pkg/log/log.go
pkg/log/warning_handler.go
pkg/log/zap/zap.go
tools/setup-envtest/store/store.go

Links to godoc.org seem to unconditionally and permanently redirect to pkg.go.dev nowadays:
```bash
$ curl -I https://godoc.org/github.com/go-logr/logr
HTTP/2 301
date: Mon, 27 Dec 2021 18:53:05 GMT
content-type: text/html; charset=utf-8
location: https://pkg.go.dev/github.com/go-logr/logr?utm_source=godoc
x-cloud-trace-context: 22d12027c3a1e74c4ccb40ccfc47d4cb/10602237531594422575;o=1
via: 1.1 google
```
This PR therefore changes the links to pkg.go.dev. I also noticed one typo and then looked and found a couple of other places where `it's` and `its` were mixed up.

:book: update links to godoc.org to use pkg.go.dev

---

pkg/cache/informer_cache.go

Signed-off-by: Tamal Saha <tamal@appscode.com>
`List` suffix is not required for listing `UnstrcuturedList` objects in some parts of the client. This makes it so for the cached client.
https://github.com/kubernetes-sigs/controller-runtime/blob/b8db76e66383819c94f530bd4b8dea60025b716f/pkg/client/client_cache.go#L57-L60

🐛 Trim List if List GVK is provided

---

tools/setup-envtest/go.mod

Bump go version in setup-envtest

:sparkles: Bump go in setup-envtest

---

pkg/leaderelection/leader_election.go
pkg/manager/manager_test.go

Update the default resource lock from `configmapsleases` to `leases`.
The previous default (since v0.7.0) was `configmapsleases`, which is the migration step from `configmaps` to `leases`. Since the default was `configmapsleases` for over a year, spanning five minor releases, any actively maintained operators are very likely to have a released version that uses `configmapsleases`. Therefore defaulting to `leases` now should be safe.
Any operators currently on a version <0.7.0 should migrate from `configmaps` to `leases` via `configmapsleases`.
- If an operator is currently on version <v0.7.0, it is hardcoded to using `configmaps`
- If an operator is currently in the range v0.7.0 to a version prior to this PR merging, it is configurable, but defaulted to `configmapsleases`.
- If an …

⚠ leaderelection: use 'leases' as default resource lock object

---

pkg/predicate/predicate.go
pkg/predicate/predicate_test.go

Pass down injector in `predicate.{And,Or}` to sub-predicates.
I'm aware, that the injection mechanisms are deprecated.
However, it comes as a surprise to users that `And,Or` don't pass down the injector. Hence, I'm opening this PR to discuss fixing this unexpected behavior.

🐛 Inject func in `predicate.{And,Or}`

---

pkg/cache/internal/informers_map.go
pkg/cache/internal/informers_map_test.go
pkg/cache/internal/internal_suite_test.go

Fixes: #1789 
I copied some tests from client-go and observed that the original implementation of gvkFixupWatcher fails those tests:
```
go test ./pkg/cache/internal/... -timeout 2s
panic: test timed out after 2s
goroutine 34 [running]:
testing.(*M).startAlarm.func1()
/home/richard/sdk/go1.17/src/testing/testing.go:1788 +0x8e
created by time.goFunc
/home/richard/sdk/go1.17/src/time/sleep.go:180 +0x31
goroutine 1 [chan receive]:
testing.(*T).Run(0xc0003f49c0, {0x128a598, 0x46c533}, 0x1327bb0)
/home/richard/sdk/go1.17/src/testing/testing.go:1307 +0x375
testing.runTests.func1(0xc0003f49c0)
/home/richard/sdk/go1.17/src/testing/testing.go:1598 +0x6e
testing.tRunner(0xc0003f49c0, 0xc000187d18)
/home/richard/sdk/go1.17/src/testing/testing.go:1259 +0x102
testing.runTests(0xc0003a9980, {0x1d4e810, …
```

:bug: Fixed a bug in newGVKFixupWatcher which caused the metadata informer to hang 

---

pkg/manager/manager.go

Fixes: https://github.com/kubernetes-sigs/controller-runtime/issues/1798
Signed-off-by: Justin Kulikauskas <jkulikau@redhat.com>
This creates a new Recorder for the leader election events (using the leader config, if provided).

:bug: Use leader config for election events

---

pkg/controller/controller.go

Addresses #1794. More context in the initial post of #1794

🌱 Add controller-name as kv pair to logger instead of as name

---

pkg/internal/controller/controller_test.go
pkg/source/source.go

This fixes the false cache sync timeout error reported if context cancelled right after cache sync has started. This situation seems to happen quite frequently on rolling updates when leader election enabled.
Fixes #1786
I am not too familiar with the controller-runtime codebase, so please let me know if you think more could be done to better support context cancellation.

:bug: Cache sync cancelled should not error with timeout

---

go.mod
go.sum

This PR fixes https://github.com/golang/vulndb/issues/322 by replacing the vulnerable module with a non-vulnerable release.
```
Medium severity vulnerability found in github.com/prometheus/client_golang/prometheus/promhttp
Description: Denial of Service (DoS)
Info: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMPROMETHEUSCLIENTGOLANGPROMETHEUSPROMHTTP-2401819
Introduced through: sigs.k8s.io/controller-runtime@0.11.1, sigs.k8s.io/controller-runtime/pkg/webhook@0.11.1
From: sigs.k8s.io/controller-runtime@0.11.1 > sigs.k8s.io/controller-runtime/pkg/manager@0.11.1 > github.com/prometheus/client_golang/prometheus/promhttp@1.11.0
From: sigs.k8s.io/controller-runtime/pkg/webhook@0.11.1 > sigs.k8s.io/controller-runtime/pkg/webhook/internal/metrics@0.11.1 > …
```

🐛  prometheus/client_golang 0.11.0 -> 0.11.1 - fix DoS

---

pkg/builder/options.go

In #1660, we found that it is too easy for users to duplicate cache projections, for example by creating a watch with `OnlyMetadata`, which creates a metadata cache, and then using the concrete type to get the watched object, which automatically creates a cache of the concrete projection.
Duplicating the cached projections is probably never what the user wanted to do, and leads to:
- Increased memory usage,
- Race conditions since caches aren't synchronized.
At first, I wanted to follow the suggestion in https://github.com/kubernetes-sigs/controller-runtime/issues/1660#issuecomment-918242097:
> We could add a check for this into pkg/cache and error out if someone requests something that we already have in a different projection
I then realized that I don't really know how to make this …

📖 Explain what may happen when using OnlyMetadata and Get on the concrete type instead of PartialMetadataObject

---

pkg/manager/manager.go

Trivial documentation fixups for several fields in the `Options` struct, that make some options easier to understand and improve readability.

✨ manager.go: Fix a few Options fields' go-docs

---

go.mod
go.sum
pkg/envtest/komega/OWNERS
pkg/envtest/komega/default.go
pkg/envtest/komega/default_test.go
pkg/envtest/komega/interfaces.go
pkg/envtest/komega/komega.go
pkg/envtest/komega/komega_test.go

This is an attempt to revive #1364 by @JoelSpeed. It's essentially the same with a few changes:
- I've added the EqualObject matcher from kubernetes-sigs/cluster-api (written by @sbueringer and @killianmuldoon - I hope you're fine with that!)
- Added package global functions so it can be used by importing `. sigs.k8s.io/controller-runtime/pkg/envtest/komega` and use it similar to Gomega
- renamed `Matcher` to `komega` since it's actually not a Gomega Matcher
- changed the `With...` functions to copy komega
This still needs a lot of tests and documentation.
cc @Danil-Grigorev @joelanford @fabriziopandini  since you were interested in the original PR

✨ Add Kubernetes Gomega extension with to make testing controllers easier

---

go.mod
pkg/builder/controller.go
pkg/builder/controller_test.go
pkg/controller/controller.go
pkg/internal/controller/controller.go
pkg/internal/controller/controller_test.go

For more details, please see: https://github.com/kubernetes-sigs/controller-runtime/issues/1826
This PR introduces the `LogConstructor` controller option which replaces the previous `Log` option.
`LogConstructor` creates a `Logger` on-demand either within the context of a reconciliation based on a *reconcile.Request or outside of it (then nil is passed in).
Through this PR the logs change as follows:
When the controller is created with the builder:
```diff
-  "msg": "controller/cluster: Waiting for DockerCluster",
+  "msg": "Waiting for DockerCluster",
+  "cluster": {
+     "name": "capi-quickstart",
+     "namespace": "default"
+   },
-  "reconciler group": "cluster.x-k8s.io",
-  "reconciler kind": "Cluster",
+  "controllerGroup": …
```

⚠ logging: align to Kubernetes structured logging, add reconcileID

---

pkg/log/zap/zap.go

In #1688 the `zap-time-encoding` flag was added. Unfortunately I missed to update the documentation of `Options.BindFlags`, so this flag is not really described in the doc.
This PR addresses it and adds the documenation for the `zap-time-encoding` flag so it shows up in the [go-doc](https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/log/zap#Options.BindFlags).

:book: Add documentation for zap-time-encoding flag

---

pkg/manager/manager.go
pkg/manager/runnable_group.go
pkg/manager/runnable_group_test.go

This PR adds a new `BaseContext` option to `manager.Options`. It's designed to be used as the basis of any `Runnable`s created by a `Manager`, so there's a way to connect the contexts from the user's side to the `Runnable` side. Currently a new `context.Background()` is created so the `Runnable`s aren't canceled when a top-level context is, so this provides a way for a user to put info in their `Runnable` contexts.
There's a discussion about this in #1817, and this PR closes #1817.
I've marked this as a WIP because the functionality works fine through anecdotal usage, but I'm unable to run the tests locally using the recommended `make test`, so I can't add any tests for this at the moment. I brought it up in the #controller-runtime Slack channel but haven't seen any responses yet.

✨ [WIP] Add BaseContext to manager Options for use with Runnables

---

pkg/internal/testing/addr/manager.go

Since commit 58c17f6 ("addr.Suggest should lock a file instead of
memory"), pkg/internal/testing/addr/manager.go’s init() function tries
to create a directory using either os.UserCacheDir() or os.TempDir(),
whichever succeeds first. In many build environments, $HOME is
non-empty but points to an unusable directory; in such cases,
os.UserCacheDir() returns an unusable directory, which causes init()
to panic.
This changes init() to first try os.UserCacheDir(), including creating
the desired directory; if that fails, the whole operation is tried
again with os.TempDir().
Fixes: #1799
Signed-off-by: Stephen Kitt <skitt@redhat.com>

Try a temporary directory if the user cache fails

---

pkg/log/zap/zap_test.go

The regex used to test whether the times were being properly encoded as ISO8601 only permitted either positive tz offsets or Z. This fix adjusts the regex to also allow negative offsets.
Ref: [Wikipedia: ISO 8601 - Time offsets from UTC](https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC)
Example of failure when running on my local machine:
```
Zap log level flag options setup
/home/jstrunk/src/controller-runtime/pkg/log/zap/zap_test.go:281
with zap-time-encoding flag provided
/home/jstrunk/src/controller-runtime/pkg/log/zap/zap_test.go:487
Should propagate time encoder to logger [It]
/home/jstrunk/src/controller-runtime/pkg/log/zap/zap_test.go:529
Expected
<string>: 2022-04-05T11:35:03.086-0400
to match regular expression
<string>: …
```

:bug: zap-time-encoding test should allow negative tz offset

---

pkg/envtest/komega/default.go
pkg/envtest/komega/interfaces.go

- It fixes envtest's komega `UpdateStatus()` godoc example to reference the corresponding function call (`UpdateStatus()`) rather than the `Update()` one.
- It fixes some typos in envtest's komega godoc examples by replacing `Scucceed()` with `Succeed()`.

🐛 pkg: envtest: komega: fix UpdateStatus & typos in godoc

---

.github/workflows/golangci-lint.yml
.golangci.yml
pkg/certwatcher/certwatcher_test.go
pkg/client/client_test.go
pkg/client/fake/client.go
pkg/client/metadata_client.go
pkg/client/unstructured_client.go
pkg/client/watch.go
pkg/envtest/crd.go
pkg/internal/flock/flock_unix.go
pkg/manager/signals/signal_posix.go
tools/setup-envtest/workflows/workflows_test.go

The current version fails on files that are unchanged, e.G. here: https://github.com/kubernetes-sigs/controller-runtime/pull/1864/files#diff-5d81d5921628c398d14ca10b459beaf11485365684008a771587421685f30dd2

:running: Update golangci-lint to 1.45.2

---

pkg/controller/controllerutil/controllerutil.go
pkg/controller/controllerutil/controllerutil_test.go

When a finalizer is added or removed to an object, typically a client requests the object be updated on the server.  Instead of making an update request unconditionally, it may be desirable to do so only when the object is modified, as an optimization.  Since the add and remove finalizer routines do not return an indication whether a finalizer was add or removed respectively, a caller needs to determine this information some other way.
One way is to call `ContainsFinalizer` before calling `AddFinalizer` or `RemoveFinalizer`.  But the time complexity of each of those routines is linear, resulting in two linear time functions when a finalizer is added or removed.
Another solution is to save the length of a the finalizer slice before calling add or remove finalizer and checking if the length …

✨return a bool from AddFinalizer and RemoveFinalizer

---

pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/cache/internal/deleg_map.go
pkg/cache/internal/informers_map.go
pkg/cache/internal/transformers.go

This PR is a complement to a recent addition to client-go https://github.com/kubernetes/kubernetes/pull/107507.
Adds two new `ForOption`s, `OwnsOption`s, and `WatchesOption`s to be used with the existing `OnlyMetadata` called `WithoutAnnotations` and `WithoutManagedFields`.
We have teams which make extensive use of metadata-only watches (tens of thousands of objects), which have seen sizable reductions in RAM usage when these fields are removed. This new options makes it easy and ergonomic to opt into stripping `managedFields` and `annotations` metadata before they are persisted in the cache, to avoid wasting resources in controllers which do not use those fields.
Behind the scenes uses `SetTransform` on `SharedIndexInformer`, and uses a transformer which respects the builders' elections …

✨ Add TransformFuncByObject Option for Informer Cache

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

Signed-off-by: Bryce Palmer <bpalmer@redhat.com>
This adds functionality to the `fakeClient` to honor dry run options when using the `Delete` or `DeleteAllOf` functions. This functionality was already present for `Create`, `Update`, and `Patch` but was missing from `Delete` and `DeleteAllOf`
This is marked as a breaking change due to this comment left on Slack by @alvaroaleman : https://kubernetes.slack.com/archives/C02MRBMN00Z/p1650560938460609?thread_ts=1650560794.722809&cid=C02MRBMN00Z
fixes #1871

:warning:  make fake client delete operations honor dry run opt

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

This pr improves the fake client with `WithObjectTracker` option.
This is useful when users want to set up unit tests across different fake client.
For example, when users are testing with client-go and kubebuilder, users will create a fake clientSet and a fake client.
Users can get the object tracker from the fake clientSet and set it to the fake controller-runtime client by this new option to let them share the same fake resources.
This will allow users to write more unit tests.

✨ Improve the fake client builder with WithObjectTracker option

---

pkg/certwatcher/certwatcher.go
pkg/certwatcher/certwatcher_test.go
pkg/certwatcher/metrics/metrics.go

Helps to see how efficient is certwatcher and with debugging issues around reloading certificates from disk.

:sparkles: certwatcher: add metrics to monitor certificate reads

---

.golangci.yml
pkg/cache/multi_namespace_cache.go
pkg/client/config/config.go
pkg/client/fake/client.go
pkg/client/namespaced_client.go
pkg/envtest/crd.go
pkg/envtest/webhook.go
pkg/finalizer/finalizer.go
pkg/internal/testing/certs/tinyca.go
pkg/internal/testing/process/arguments_test.go
pkg/manager/internal.go
pkg/manager/manager.go
pkg/manager/manager_test.go
pkg/source/source.go
pkg/webhook/server.go
tools/setup-envtest/remote/client.go
tools/setup-envtest/store/store.go
tools/setup-envtest/workflows/workflows_testutils_test.go

This PR enables another 2 linters and fixes the issues that they brought up.
/kind cleanup

:seedling: enable errorlint and unused linters

---

.golangci.yml
examples/scratch-env/main.go
pkg/client/config/config_test.go
pkg/config/config.go
pkg/envtest/crd.go
pkg/envtest/webhook.go
pkg/internal/testing/controlplane/apiserver.go
pkg/internal/testing/controlplane/auth.go
pkg/internal/testing/controlplane/kubectl_test.go
pkg/internal/testing/process/process.go
pkg/internal/testing/process/process_test.go
pkg/leaderelection/leader_election.go
pkg/manager/manager_test.go
pkg/webhook/admission/http.go
pkg/webhook/authentication/http.go
pkg/webhook/conversion/conversion_test.go
pkg/webhook/server.go
pkg/webhook/server_test.go

Go 1.16 deprecated the usage of `io/ioutil` and this PR performs the necessary changes to get rid of that package. Go 1.17 is the minimum supported version of controller-runtime since #1714 (November 2021).
/kind cleanup
Fixes #1518

:seedling: do not use io/ioutil anymore

---

pkg/client/options.go

Since forever the ListOptions had the comment to use SetLabelSelector(), but I could not find any revision (going back to 0.2.x) that ever offered such a function. Therefore I updated the comment to hint to the upstream parsing function.
Fixes #1878

:book: Fix comment on ListOptions

---

pkg/client/apiutil/apiutil_suite_test.go
pkg/client/apiutil/dynamicrestmapper.go
pkg/client/apiutil/dynamicrestmapper_test.go

Fix panic for lazy dynamicRESTMapper to make `setStaticMapper` successfully once, which means if dynamicRESTMapper fails to `setStaticMapper`, it will do it once again in next `init`.
fixes #1712

🐛 Fix panic for lazy dynamicRESTMapper

---

pkg/manager/manager.go
pkg/manager/manager_options_test.go
pkg/manager/testdata/custom-config.yaml

:bug: Avoid nilref when copying leader election options from custom config

---

RELEASE.md

Doc release process for the project

:book: add info about release process

---

pkg/envtest/crd.go
pkg/envtest/crd_test.go

In #1888 I accidentally changed the semantics of `files`, which was previously always overridden with the result from `ioutil.ReadDir`, but is now only ever `append()`ed to. This causes problems when reading CRDs from multiple directories.
This PR changes the scope for the variables to fix that bug. So sorry to have broken the 0.12 release :(

:bug: fix loading CRDs from multiple directories in envtests

---

pkg/webhook/server.go
pkg/webhook/server_test.go

Some operators might want to respect cluster-wide TLS ciphers for example,
which means that these will eventually have to be passed down to the webhook server.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/1754

:sparkles: Allow TLS to be entirely configured on webhook server

---

pkg/webhook/admission/defaulter.go
pkg/webhook/admission/defaulter_test.go

Signed-off-by: AnyISalIn <anyisalin@gmail.com>
We should always return zero patches when receiving a DELETE operation in the mutation handle.
Reference Issues:
https://github.com/kubernetes-sigs/controller-runtime/issues/1762
https://github.com/kubernetes-sigs/controller-runtime/issues/1278

:bug: skip mutation handler when received deletion verb

---

pkg/builder/controller.go

The recent change
https://github.com/kubernetes-sigs/controller-runtime/commit/598978c592839b5a602af3706fce8751d2d2532c#diff-e77b9468ab935d5ea4d5cdae3b994114bada17df0001570e4b1436419afd50ccR312
introduced a bug by overriding `log` with the log created by a builder,
resulting in all logs produced by `controller-runtime` having
`controller`, `controllerGroup` and `controllerKind` set to the last
created controller.

:bug: don't override global log in builder

---

pkg/internal/testing/addr/manager.go

:bug: Fix issue with starting multiple test envs

---

pkg/manager/manager.go

Fix comment on LeaderElectionResourceLock

📖 Fix comment on LeaderElectionResourceLock

---

pkg/cache/informer_cache.go
pkg/cache/informertest/fake_cache.go
pkg/cache/internal/cache_reader.go
pkg/cache/multi_namespace_cache.go
pkg/client/client.go
pkg/client/client_test.go
pkg/client/dryrun.go
pkg/client/fake/client.go
pkg/client/interfaces.go
pkg/client/metadata_client.go
pkg/client/namespaced_client.go
pkg/client/options.go
pkg/client/options_test.go
pkg/client/split.go
pkg/client/typed_client.go
pkg/client/unstructured_client.go
pkg/controller/controllerutil/controllerutil_test.go

Add `GetOptions` as optional argument of client.Reader and all its implementation, so that ppl can set fields of `metav1.GetOptions` like `resourceVersion="0"` when they are directly getting from apiserver.
fixes #1915

⚠ Add GetOptions as optional argument of client.Reader and all its implementation

---

designs/use-selectors-at-cache.md

Signed-off-by: bzd111 <zxc@bzd111.me>
:book: fix typo  and format this file

📖 fix typo and format this file

---

pkg/client/client.go
pkg/client/namespaced_client.go

What does this do, and why do we need it? 
Just fix some typos

:sparkles:  fix some typos

---

pkg/webhook/admission/http.go
pkg/webhook/admission/http_test.go

Fix webhook write response error for broken HTTP connection
fixes #1829 
fixes [issue from slack](https://kubernetes.slack.com/archives/CAR30FCJZ/p1654871872956339)
fixes [issue from slack](https://kubernetes.slack.com/archives/CAR30FCJZ/p1655153792335999)

🐛 Fix webhook write response error for broken HTTP connection

---

pkg/client/doc.go

Just a minor nit fix in the documentation. 
This makes the documentation (https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client) more readable.

📖 nit: fix in client package documentation

---

pkg/client/client.go

Only configure the local warning handler. Please see the issue for details.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/1928.

⚠️ Do not mutate the global warning handler

---

pkg/builder/webhook_test.go
pkg/webhook/admission/defaulter_custom.go
pkg/webhook/admission/validator_custom.go
pkg/webhook/admission/webhook.go
pkg/webhook/admission/webhook_test.go

This PR provides access to the admisison.Request in custom validator and defaulter.
Fixes #1949

✨ Provide access to admission.Request in custom validator/defaulter

---

pkg/builder/webhook.go
pkg/builder/webhook_test.go
pkg/webhook/admission/webhook.go
pkg/webhook/admission/webhook_test.go

Currently, a panic occcurence in a webhook handler is not recovered and crashes the webhook server.
This change adds an option to Webhook to recover panics similar to how it is handled in Reconciler. It ensures that panics are converted to normal error response.

:sparkles: webhook: add an option to recover from panics in handler

---

pkg/client/fake/doc.go

There was a typo in docs of `pkg/client/fake/doc.go`:
s/OpeanAPI/OpenAPI/

:book: fix docs: typo in OpenAPI

---

.github/workflows/golangci-lint.yml
pkg/certwatcher/example_test.go
pkg/client/apiutil/dynamicrestmapper.go
pkg/internal/testing/process/process.go

Updates golangci-lint in github actions

:running: Update golangci-lint to 1.47.3

---

examples/scratch-env/main.go
pkg/log/deleg.go
pkg/log/zap/zap.go

Fixes #1737
Adds a depth of 1 to the DelegatingLogSink sink, instead of a global depth to the zapr sink.
This global depth is problematic because it doesn't apply to loggers obtained with `WithName` or `WithValues`.
**Notes for reviewer**
To see this fix in action (and the bug before this fix), go to `examples/scratch-env/main.go` and set Development mode to false.

🐛 Fix log depth for DelegatingLogSink

---

pkg/internal/recorder/recorder.go

The event message should be the message passed to the log statement rather than a value.
Closes #1973

🐛 Rearange `EventBroadcaster` log statement.

---

pkg/client/client_test.go
pkg/client/interfaces.go

closes https://github.com/kubernetes-sigs/controller-runtime/issues/1964
This PR adds a function to ignore `AlreadyExists` errors.

:sparkles: Implement IgnoreAlreadyExists

---

pkg/reconcile/reconcile.go

The doc for reconcile example seems to be outdated.

📖 update doc for reconcile example

---

pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/cache/cache_unit_test.go
pkg/cache/internal/transformers.go

using cache.BuilderWithOptions does not properly inherit all
options passed in from the caller:
- scheme was overridden instead of merged
- selectors were not inherited at all, even if specified options
selectors remained unset
- transforms were not inherited at all, even if specified options
transforms remained unset
- disable deep copy settings were not inherited at all, even if
specified options for disabling deep copies remained unset
This commit resolves this issues by implementing merge logic for all
fields in the cache.Options struct:
- Schemes are merged
- RESTMapper is chosen by precedence only falling back to inherited
options if left unset in specified options
- Resync is chosen by precedence only falling back to inherited
options if left unset in specified options
- Namespace …

⚠ cache.BuilderWithOptions inherit options from caller

---

pkg/config/v1alpha1/types.go
pkg/manager/manager.go

add configuration comments once use `NewManager` 
Signed-off-by: Icarus9913 <icaruswu66@qq.com>

📖 add comments for configuration

---

pkg/webhook/conversion/conversion.go

This PR fixes a panic in the conversion webhook HTTP handler when no conversion request is sent by the client.
To avoid dereferencing a nil pointer when trying to access the UID, I set a default uid to an empty UID.
Let me know if I should return an HTTP Bad Request instead.
EDIT: Bad Request is returned when the conversion request is nil

🐛 Conversion webhook should not panic when conversion request is nil

---

pkg/client/typed_client.go
pkg/client/unstructured_client.go

this pr just update some code , make  unstructured_client and typed_client  have same code style.
i think the code will be more readable for users.

🌱 Refactor typed_client and unstructured_client to be consistent

---

TMP-LOGGING.md
pkg/builder/options.go
pkg/log/zap/zap.go
tools/setup-envtest/README.md
tools/setup-envtest/main.go
tools/setup-envtest/workflows/workflows.go

A minor grammar fix that removes doubles of the word "the".

🌱 grammar: removed doubles of the word "the"

---

pkg/client/interfaces.go

Make it explicit in the function comments that the "obj" argument of the Client interface's Create method must be a struct pointer, because implementers will store in it the object returned by the K8s API server.
The added statement was already present on `Update` and `Patch` methods, but not on `Create`.
**Note**:This comment will end up in the godoc of the package, but I couldn't find the godocs in the repo, so I don't know how to update the godocs.

📖 Advertise struct pointer requirement for Create

---

pkg/envtest/webhook_test.go
pkg/manager/internal.go
pkg/manager/manager.go
pkg/manager/manager_test.go
pkg/webhook/webhook_integration_test.go

Fixes #2020
I hope I found all relevant places.

✨ Add tls options to manager.Options

---

pkg/manager/manager.go
pkg/manager/manager_test.go

Fixes: https://github.com/kubernetes-sigs/controller-runtime/issues/2026 
This allows a more flexible configuration of the controller-runtime leader election if needed. Those changes allow to provide a custom `resourcelock.Interface` that will be used for leader election.

:sparkles: Allow to provide a custom lock interface to manager

---

pkg/log/zap/zap.go
pkg/log/zap/zap_test.go

The zap logger currently defaults to epoch time encoding which is pretty much imposisble to parse for humands. Default to RFC339 instead, as that is well-parseable by both humans and machines.
Fixes #2024 
/assign @vincepri @joelanford @sbueringer @camilamacedo86 
Ccing a larger group, as changing defaults has the potential of breaking things in a way where ppl will only notice after a rollout (e.G. if their log parsing assumes the epoch time format), so I want to be sure that everyone agrees this is a good idea.

⚠ Zap log: Default to RFC3339 time encoding

---

TMP-LOGGING.md

Rename `req.NamespaceNamed` to `req.Namespacename`

:book: Fix documentation typo

---

alias.go
pkg/client/config/config.go

There have been reported issues (`flag redefined`) because CR registers the `kubeconfig` flag to the default command line FlagSet via init function. See:
* https://github.com/kubernetes-sigs/controller-runtime/issues/1396
* https://github.com/kubernetes-sigs/controller-runtime/issues/878
This PR provides an exported func to register flags that defensively tries to register the kubeconfig flag if not already defined. It does only change the current behaviour by previously checking if has already been defined.
As a follow up the registration via init should probably removed in conjunction with a :warning: release note, as it would be a breaking change for the user.
**NOTE**: I am not entirely sure if this really is the desired way to go and to start a discussion regarding the topic. …

:seedling: Register kubeconfig flag variable via RegisterFlags func

---

pkg/cache/internal/cache_reader.go
pkg/client/fake/client.go
pkg/client/fake/client_test.go
pkg/internal/field/selector/utils.go
pkg/internal/field/selector/utils_suite_test.go
pkg/internal/field/selector/utils_test.go

Allow registration of indexes into the fake client to allow usage of field selectors when doing a List. The indexing is done lazily by doing a normal list and then filtering the results by computing the index value for each list item.
To enable the main change for this commit, some refactorings are performed: an internal and unexported function that checks whether a field selector is in the form key=val or key==val is made internal and exported to be shared between real and faked code to ensure loyalty. Unit tests for it are added.
Co-authored-by: Paul Eichler <peichler@anynines.com>
This PR addresses https://github.com/kubernetes-sigs/controller-runtime/issues/1948#issuecomment-1275389911 and is a reincarnation of https://github.com/kubernetes-sigs/controller-runtime/pull/800

✨ Add indexes to fake client to mimic field selectors

---

pkg/predicate/predicate.go
pkg/predicate/predicate_test.go

This PR adds a new boolean NOT predicate function (`predicate.Not()`) to complement `predicate.And()` and `predicate.Or()` added in https://github.com/kubernetes-sigs/controller-runtime/pull/1043.
While not extremely useful, I think it can make code for bootstrapping controllers easier to read. And avoid having to create a dedicated predicate just for selecting the complement set selected by another predicate.
I have also seen a few examples of this implemented as a utility in publicly available controllers.

:sparkles: feat: add NOT predicate

---

pkg/cache/cache.go
pkg/cache/cache_unit_test.go

This PR follows up on #1980, which introduced a regression in the way `cache.BuilderWithOptions` deals with scheme selection when handling selectors.
When handling inherited selectors, we should only use the inherited scheme. However, when handling the selectors in the cache builder options, we should use the combined scheme. This ensures that callers are not forced to pass their parent `runtime.Scheme` down to every `cache.BuilderWithOptions` call.
#1980 has not yet been released, so this bug fix does not require any backport.

🐛 fix: improve semantics of combining cache selectorsByObject

---

pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/cache/informer_cache.go
pkg/cache/informertest/fake_cache.go
pkg/cache/multi_namespace_cache.go
pkg/source/source.go
pkg/source/source_integration_test.go

Support registration and removal for event handler, which is the new feature in K8s 1.26 https://github.com/kubernetes/kubernetes/pull/111122
After it merged, I will post a new PR to support removal of watches/controllers for https://github.com/kubernetes-sigs/controller-runtime/issues/1884.

⚠ Support registration and removal of event handler

---

pkg/webhook/admission/defaulter_custom.go

Signed-off-by: iiiceoo <[ziqian.xue@daocloud.io](mailto:ziqian.xue@daocloud.io)>
closes [#2048](https://github.com/kubernetes-sigs/controller-runtime/issues/2048)
Mutating webhook registered by func `WithDefaulter()` returns an error `"there is no content to decode"` when processing CR deletion request. Refer to the solution [here](https://github.com/kubernetes-sigs/controller-runtime/blob/1ead647/pkg/webhook/admission/defaulter.go#L61-L70), add the same logic to the handler of the interface `CustomDefaulter`.

🐛 Skip custom mutation handler when delete a CR

---

.github/dependabot.yml

In the slack channel for controller-runtime, it was suggested to add dependabot to controller-runtime.  This PR adds dependabot for go and github actions.  
I am unfamilar with this repo so please let me know if there is any other items that should be included.

:seedling: Add Dependabot for dependency management

---

pkg/controller/controller.go
pkg/internal/controller/controller.go
pkg/internal/controller/controller_test.go

This creates a new function `ReconcileIDFromContext` which allows to get the logged reconcile ID from context. It is proposed in #2055.
Since the controller package , where the reconcileID is created and added is internal, I had to reference the function in `pkg/controller/controller.go`. To expose the function in `pkg/reconcile` or `pkg/log` is not possible because of import cycles. And the creation of a new package `pkg/context` seemed a little exaggerated to me.

:sparkles: Add function to get reconcileID from context

---

pkg/source/source.go

Add a `String` method for the `kindWithCache` type to make log messages neater.
When the controller starts a source, the controller logs the message "Starting EventSource" along with the stringification of the source. Most source types implement the `String` method to provide pretty stringifications, but the `kindWithCache` source type was missing this, resulting in log messages like the following:
2022-11-23T08:47:35.646-0600    INFO    operator.init   controller/controller.go:241    Starting EventSource    {"controller": "configurable_route_controller", "source": "&{{%!s(*v1.Role=&{{ } {      0 {{0 0 <nil>}} <nil> <nil> map[] map[] [] [] []} []}) %!s(*cache.multiNamespaceCache=&{map[openshift-config:0xc000712110 openshift-config-managed:0xc000712108 openshift-ingress:0xc0007120f8 …

:sparkles: Tidy up startup logging of kindWithCache source

---

.github/dependabot.yml

I notice that the dependabot PRs were manually be changed to add :seedling: tag.  We can add that to the commit message.

:seedling: seedling to dependabot

---

.github/dependabot.yml

This ignores the kubernetes api dependencies

:seedling: Ignore Kubernetes Dependencies in Dependabot

---

pkg/cluster/cluster.go

This adds a new `cluster.ClientBuilderWithOptions` alongside the `cluster.DefaultNewClient`, which will allow users to easily get a client that caches `Unstructured` - which the default client intentionally doesn't, ref https://github.com/kubernetes-sigs/controller-runtime/issues/615#issuecomment-536769176.
Almost all the operators I work on seem to benefit from enabling caching of `Unstructured`. While not "that" common, I have also seen users asking for this on Slack. 😉 Adding this new func to controller-runtime will avoid having to implement the workaround explained in [this blog](https://ymmt2005.hatenablog.com/entry/2021/07/25/Caching_Unstructured_Objects_using_controller-runtime).

:sparkles: Add cluster.NewClientFunc with options

---

pkg/client/config/config.go

Signed-off-by: Maciej Karaś [maciej.karas@form3.tech](mailto:maciej.karas@form3.tech)
closes https://github.com/kubernetes-sigs/controller-runtime/issues/2053

:bug: Missing error log for in-cluster config

---

pkg/client/client.go
pkg/client/client_test.go
pkg/client/dryrun.go
pkg/client/dryrun_test.go
pkg/client/fake/client.go
pkg/client/interfaces.go
pkg/client/metadata_client.go
pkg/client/namespaced_client.go
pkg/client/namespaced_client_test.go
pkg/client/options.go
pkg/client/split.go
pkg/client/typed_client.go
pkg/client/unstructured_client.go
pkg/envtest/komega/default.go
pkg/envtest/komega/interfaces.go
pkg/envtest/komega/komega.go

This change adds a SubResourceWriter to the client package that can be used to Create, Update or Patch arbitrary subresources.
This fixes the majority of  https://github.com/kubernetes-sigs/controller-runtime/issues/172, the only thing missing for it to close would be to add subresource Get, as I think there is no existing usage of subresource Delete.
Relative to https://github.com/kubernetes-sigs/controller-runtime/pull/1922 the main changes are:
* Use distinct options for subresource Update and Patch which makes this a breaking change
* Add subresource Create, needed for example for ServiceAccount tokens
Supersedes and thereby closes https://github.com/kubernetes-sigs/controller-runtime/pull/1922
Supersedes and thereby closes https://github.com/kubernetes-sigs/controller-runtime/pull/201 …

:warning: Add client.SubResourceWriter

---

pkg/manager/internal.go
pkg/manager/manager.go
pkg/metrics/leaderelection.go
pkg/metrics/workqueue.go

This PR enables metrics of clientgo leader election ( "k8s.io/client-go/tools/leaderelection" )

✨ Enable metrics of clientgo leader election

---

.github/workflows/golangci-lint.yml
.golangci.yml
pkg/builder/webhook_test.go
pkg/client/apiutil/apimachinery.go
pkg/controller/controllerutil/controllerutil.go

Signed-off-by: Vince Prignano <vince@prigna.com>
All removed linters have been deprecated

:seedling: Update golangci-lint to v1.50.1

---

hack/check-everything.sh

The current specified version, 1.22.0, doesn't actually exist and was never built in kubebuilder-tools.
Signed-off-by: Vince Prignano <vince@prigna.com>

🌱 Default ENVTEST version to a working one (1.24.2)

---

pkg/manager/internal.go
pkg/manager/manager_test.go

Currently it is possible to start the mgr multiple times, which will cause all sorts of issues. Prevent that from happening.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/2083

:bug: Prevent manager from getting started a second time

---

pkg/config/v1alpha1/types.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/internal/controller/controller.go
pkg/internal/controller/controller_test.go

This change allows configuring the RecoverPanic setting for controllers globally. It is a breaking change as it requires changing the field type of the setting to *bool from bool in order to be able to check if it has been set already.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/2001

:warning: Allow configuring RecoverPanic for controllers globally

---

pkg/builder/controller.go
pkg/builder/controller_test.go

Requiring For does not make sense for all controllers as it is possible that their primary event triggering is not an object in the current cluster but for example an object in a different cluster or a source.Channel.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/2052

✨Builder: Do not require For

---

pkg/client/client.go
pkg/client/client_test.go
pkg/client/dryrun.go
pkg/client/fake/client.go
pkg/client/interfaces.go
pkg/client/namespaced_client.go
pkg/client/options.go
pkg/client/split.go
pkg/client/typed_client.go
pkg/client/unstructured_client.go

This changes enabled the SubResourceClient to retrieve subresources, thereby completing it for CRUD subresources (under the assumption that there is no such thing as a Delete for subresources, which does hold true for core resources).
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/172

⚠️ Add Get functionality to SubResourceClient

---

pkg/builder/controller.go
pkg/builder/controller_test.go

Fixes #2101 
When calling `Builder.Complete()` without `For`, `blder.forInput.object` is nil.
If `source.Kind` with nil Type is passed to Watch(), it results in `must specify Kind.Type` error at https://github.com/kubernetes-sigs/controller-runtime/blob/69f093833822d321742c7a729d4339cd8e101507/pkg/source/source.go#L116

🐛 controllers without For() fail to start

---

OWNERS_ALIASES

Removing me and @fillzpp from reviewers as we're now also approvers based on
```
```

🌱 Remove reviewers which are also approvers

---

pkg/client/client.go
pkg/client/client_rest_resources.go
pkg/client/typed_client.go
pkg/client/unstructured_client.go
pkg/client/watch.go

This file and bits in it were confusing, the client struct doesn't have any sort of built-in cache (as in, watch/list cache from informers). Every request goes to the API server directly instead. The "internal cache" is really just a storage for all rest client resources, this commit changes that to clarify and avoid confusion.
Signed-off-by: Vince Prignano <vince@prigna.com>

🌱 client/cache/client_cache.go should be called resources

---

pkg/envtest/webhook_test.go
pkg/webhook/admission/http.go
pkg/webhook/admission/http_test.go
pkg/webhook/admission/response.go
pkg/webhook/admission/response_test.go
pkg/webhook/admission/validator_test.go
pkg/webhook/webhook_integration_test.go

Use Result.Message instead of Result.Reason for the user supplied
portion. Reason is intended to be machine readable while Message is
intended to be human readable. While each is documented as being
informational only, the Is* family of functions in
k8s.io/apimachinery/pkg/api/errors rely on the StatusReason.
This change allows controllers to rely on
"k8s.io/apimachinery/pkg/api/errors".IsForbidden to deal with errors
consistently regardless of whether the operation failed due to an
admission webhook implemented with controller-runtime, a standard
kubernetes failure (e.g related to RBAC), or another controller not
implemented with controller-runtime.
See kubernetes/kubernetes#101926 for more information

⚠ pkg/webhook/admission: use Result.Message instead of Result.Reason

---

pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/internal/controller/controller.go

Creating a controller that is not leader elected is seems to require a bit of indirection. You currently have to create a new type that embeds the `Controller` interface and adds a `NeedLeaderElection` method as shown below so that it implements the `manager.LeaderElectionRunnable` interface.
```go
type MyReconciler struct {
client.Client
Log      logr.Logger
Scheme   *runtime.Scheme
Recorder record.EventRecorder
}
func (rec *MyReconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Result, error) {
return ctrl.Result{}, nil
}
func (rec *MyReconciler) SetupWithManager(mgr ctrl.Manager) error {
cont, err := controller.NewUnmanaged("my-controller", mgr, controller.Options{
Reconciler: rec,
})
if err != nil {
return err
}
cont = MyController{cont}
cont.Watch(&source.Kind{Type: …
```

:sparkles: Add controller option for setting leader election

---

pkg/client/options.go
pkg/client/options_test.go

This enhances #2072 to allow FieldOwner work with SubResources to set the FieldManager option.

✨ Add additional SubResource* functions for FieldOwner

---

pkg/cache/internal/informers_map.go

This PR fixes this TODO item:
https://github.com/kubernetes-sigs/controller-runtime/blob/b7561613a41a7759668636e9a69fa377d7989f84/pkg/cache/internal/informers_map.go#L320-L322
It also make sure that all informers finish (using a `sync.WaitGroup`) before returning from the `Start` function.

✨Use correct context to cancel "list and watch" & wait for all informers to complete

---

.golangci.yml
example_test.go
pkg/builder/controller_test.go
pkg/certwatcher/example_test.go
pkg/predicate/predicate_test.go
pkg/webhook/admission/admissiontest/util.go
pkg/webhook/admission/validator_custom.go
pkg/webhook/server.go

🌱 Add more linters

---

pkg/cache/multi_namespace_cache.go
pkg/client/apiutil/apimachinery.go
pkg/client/client.go
pkg/client/dryrun.go
pkg/client/fake/client.go
pkg/client/interfaces.go
pkg/client/namespaced_client.go
pkg/client/split.go
pkg/internal/objectutil/objectutil.go

Add commonly used utilities that can be nicely wrapped in the built-in clients, in more details GroupVersionKindFor(obj) can be used to retrieve the GVK for a given object, while IsObjectNamespace can be used to determine if an object is global, or namespace scoped.

⚠️ Add client.{GroupVersionKindFor, IsObjectNamespaced}

---

pkg/builder/controller.go
pkg/builder/controller_test.go
pkg/builder/options.go

This changeset modifies and adds new capabilities for our builder to overcome the limitation of removing dependency injection.

⚠ Improve builder's capabilities and general UX

---

examples/builtins/mutatingwebhook.go
examples/builtins/validatingwebhook.go
pkg/builder/webhook.go
pkg/builder/webhook_test.go
pkg/webhook/admission/defaulter_test.go
pkg/webhook/admission/http.go
pkg/webhook/admission/webhook.go
pkg/webhook/admission/webhook_test.go

`admission.Webhook` now passes a request logger to the handler via the context.
It can be retrieved by handlers via `logf.FromContext(ctx)` and is setup with commonly interesting fields about the request.
The logger and it's fields can be customized by setting `Webhook.LogConstructor`.
This is very similar to how controllers are passing a reconciliation logger to reconcilers and allows for greater harmonization across the entire codebase, i.e. using contextual loggers everywhere instead of manually passing around half-cooked loggers.

✨ Pass webhook logger to handler via context

---

pkg/builder/controller_test.go
pkg/handler/enqueue.go
pkg/handler/enqueue_mapped.go
pkg/handler/enqueue_owner.go
pkg/handler/eventhandler.go
pkg/handler/eventhandler_test.go
pkg/handler/example_test.go
pkg/internal/controller/controller_test.go
pkg/internal/source/event_handler.go
pkg/internal/source/internal_test.go
pkg/internal/source/kind.go
pkg/source/source.go
pkg/source/source_integration_test.go
pkg/source/source_test.go

This changeset adds a context.Context parameter to every EventHandler call. Most project might use MapFunc specifically to retrieve other objects with clients and potentially enqueue requests to a watching object. A context is useful in these cases to avoid using context.TODO() or Background() which never gets cancelled.

⚠ Add context to EventHandler(s)

---

pkg/builder/webhook.go
pkg/webhook/admission/webhook.go
pkg/webhook/conversion/conversion.go
pkg/webhook/conversion/conversion_test.go

:warning: Add constructor for conversion webhooks, rm admission.GetDecoder()

---

pkg/client/config/config.go

Signed-off-by: yanggang <gang.yang@daocloud.io>
fix config default value.
when the cfg.Burst!=0 , can not change it value.

:seedling:fix default value for cfg.Burst

---

pkg/client/apiutil/apimachinery.go
pkg/client/watch.go
pkg/client/watch_test.go

Currently, we use a custom `NegotiatedSerializer` for unstructured serialisation. This PR proposes to use the client-go unstructured `NegotiatedSerializer` instead.
This serializer does try to deserialize all json blobs to unstructured structs, making it possible to use Watch together with this deserializer (see changes to `pkg/client/watch.go`).

✨ Improve unstructured serialisation

---

hack/ensure-golangci-lint.sh

🐛 Update golanci-lint script

---

pkg/webhook/webhook_integration_test.go

Two goroutines were writing to the same error variable.

🐛 Don't share error concurrently in test

---

pkg/cache/cache.go
pkg/cache/informer_cache_test.go
pkg/cache/internal/informers.go
pkg/client/apiutil/apimachinery.go
pkg/client/apiutil/dynamicrestmapper.go
pkg/client/apiutil/dynamicrestmapper_test.go
pkg/client/client.go
pkg/client/client_rest_resources.go
pkg/cluster/cluster.go
pkg/cluster/cluster_test.go
pkg/cluster/internal.go
pkg/handler/eventhandler_test.go
pkg/internal/recorder/recorder.go
pkg/internal/recorder/recorder_suite_test.go
pkg/internal/recorder/recorder_test.go
pkg/manager/internal.go
pkg/manager/manager.go
pkg/manager/manager_test.go

client-go has all these fancy `NewForConfigAndClient` constructor functions.
Let's expose this functionality to the controller-runtime user too & reduce the number of different http.Clients that we use.
In https://github.com/kubernetes/kubernetes/pull/105490, the decision for making http.Client configurable is explained: "when using a custom transport, this has the consequence that each group/version had an independent TCP connection to the API server"
By re-using the same http client for all the clients, we can share customized transports, resulting in no additional TCP connections (see https://github.com/kubernetes/kubernetes/blob/5681b0da14f11165fc53ad82a3400fd027979fc4/test/integration/apiserver/apiserver_test.go#L2517-L2574 for an example)

⚠️ make *http.Client configurable and use/ share the same http.Client in the default configuration

---

pkg/certwatcher/certwatcher.go

This fixes a flake in CI, but it could also come in handy when running the certwatcher against volume mounted certificates. Ideally the timeout is going to be configurable at some point, for now, let's just retry for a fixed number of seconds, before returning an error.

🐛 pkg/certwatcher: Start should retry for 10s when adding files

---

pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/cache/cache_unit_test.go
pkg/cache/internal/informers.go
pkg/cache/multi_namespace_cache.go
pkg/cluster/cluster.go
pkg/manager/example_test.go

This changeset refactors the entire cache.Options struct to provide a legible and clear way to configure parameters when a cache is created. In addition, it handles under the hood the automatic multi-namespace cache support we currently offer through the
MultiNamespacedCacheBuilder, which is now deprecated.

⚠ Refactor cache.Options, deprecate MultiNamespacedCacheBuilder

---

pkg/cache/cache.go

Follow-up PR for https://github.com/kubernetes-sigs/controller-runtime/pull/2122 (see https://github.com/kubernetes-sigs/controller-runtime/pull/2122#discussion_r1092334261)

🌱 Return the error from rest.HTTPClientFor instead of hiding it

---

pkg/cluster/cluster.go

In #2122, I forgot to pass the HTTPClient to the API Reader (https://github.com/kubernetes-sigs/controller-runtime/pull/2122#discussion_r1092734760). Thanks @alvaroaleman for pointing this out.

:running: Use HTTPClient to create the API Reader

---

pkg/client/apiutil/apimachinery.go

As discussed here: https://github.com/kubernetes-sigs/controller-runtime/pull/2122#discussion_r1092736800, these `NewDiscoveryRESTMapper` and `RESTClientForGVK` are actually public functions.
For this reason, we want to return an error instead of panicking.
TODO: decide whether we want to just create a default httpClient if the parameter is nil
@alvaroaleman PTAL

🌱Return an error if no httpClient is provided

---

alias.go
pkg/builder/controller.go
pkg/builder/controller_test.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/doc.go
pkg/config/example_test.go
pkg/config/v1alpha1/doc.go
pkg/config/v1alpha1/register.go
pkg/config/v1alpha1/types.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/manager/example_test.go
pkg/manager/internal.go
pkg/manager/manager.go
pkg/manager/manager_options_test.go
pkg/manager/manager_test.go

This provides an early warning for users on 0.14 that the pkg/config types are going to be removed in a future release and they should migrate off.
/assign @sbueringer

🌱 [0.14] Deprecate component configuration package

---

pkg/cache/informer_cache.go
pkg/cache/internal/informers.go
pkg/client/client.go
pkg/client/client_rest_resources.go
pkg/client/fake/client.go
pkg/client/unstructured_client.go
pkg/client/watch.go
pkg/envtest/komega/equalobject.go
pkg/webhook/admission/decode.go

Fixes #415
I'm indifferent if we actually want to do this or not, if we decide not to, we should also close the related issue as well

🌱 Use runtime.Unstructured interface instead of Unstructured struct

---

pkg/client/apiutil/dynamicrestmapper.go

In #2164, I fixed this issue for `NewDiscoveryRESTMapper` and `RESTClientForGVK`. This PR also fixes the issue for `NewDynamicRESTMapper`.

🌱Return an error if no httpClient is provided for `NewDynamicRESTMapper`

---

pkg/client/apiutil/dynamicrestmapper.go
pkg/client/apiutil/lazyrestmapper.go
pkg/client/apiutil/lazyrestmapper_test.go
pkg/client/apiutil/testdata/crd.yaml

This PR adds a rest mapper that will lazily query the provided client for discovery information to do REST mappings. This allows you to significantly reduce the number of requests to the API server, as currently we do a request for each registered GroupVersion at startup. It also makes the startup time of the controller more predictable and independent of the number of CRDs installed in the system.
Fixes: https://github.com/kubernetes-sigs/controller-runtime/issues/1603

✨ Provide a truly lazy restmapper

---

pkg/client/client.go
pkg/client/client_suite_test.go
pkg/client/client_test.go
pkg/client/dryrun_test.go
pkg/cluster/cluster.go
pkg/manager/manager.go

✨ Expose Cache/Client options on Cluster

---

pkg/envtest/server.go

Signed-off-by: yanggang <gang.yang@daocloud.io>
/kind cleanup
Code clean for evntest.server. 
Because the variable ```AttachControlPlaneOutput``` is only used in the ```os.Getenv(envAttachOutput) ``` method..
Maybe we should clean the code for that condition.

:seedling: code clean for pkg/envtest/server.go

---

Makefile
hack/verify.sh

Follow-up to https://github.com/kubernetes-sigs/controller-runtime/pull/2096 to ensure we always verify that go modules and generated files are up-to-date.
(verify.sh is run by our presubmit test job)

🌱 verify.sh: verify generate & modules (in CI)

---

.golangci.yml
alias.go
pkg/config/config.go
pkg/config/config_suite_test.go
pkg/config/config_test.go
pkg/config/example_test.go
pkg/config/v1alpha1/register.go
pkg/config/v1alpha1/types.go
pkg/manager/example_test.go
pkg/manager/manager.go
pkg/manager/manager_options_test.go
pkg/manager/manager_test.go
pkg/manager/testdata/custom-config.yaml

This also modifies the deprecation text a bit, and provides information on where to share feedback

:seedling: Re-add tests for component config

---

pkg/manager/internal.go
pkg/manager/manager_test.go

This is already specified in the documentation https://github.com/kubernetes-sigs/controller-runtime/blob/v0.14.1/pkg/manager/manager.go#L293 
Fixes #2110

🐛 Allow to set GracefulShutdownTimeout to -1, disabling timeouts

---

pkg/client/apiutil/apimachinery.go

- If the user sets the GVK, make sure that's in the list of the GVK returned from the Scheme.
- Always print out the multiple GVKs when erroring out
- Add more comments on where to find more information about this issue

🌱 GVKForObject should handle multiple GVKs in Scheme gracefully

---

.github/workflows/golangci-lint.yml
README.md
RELEASE.md
doc.go

📖 Replace occurences of master with main

---

pkg/manager/manager.go

🌱 Provide more information on deprecating ComponentConfig

---

.golangci.yml
pkg/cache/cache.go
pkg/cache/cache_unit_test.go
pkg/cluster/cluster.go
pkg/manager/internal.go
pkg/manager/manager.go
pkg/manager/manager_test.go

⚠ Expose Manager.Cache/Client options, deprecate older opts

---

pkg/client/apiutil/lazyrestmapper.go
pkg/client/apiutil/lazyrestmapper_test.go

Now lazy restmapper fetches all API resources once at start and then caches them. It prevents it from discovery of new CRDs created after the controller has started.
This PR allows lazy restmapper to work with such CRDs.

🐛 Allow lazy restmapper to work with CRDs created at runtime

---

pkg/client/apiutil/lazyrestmapper.go
pkg/client/apiutil/lazyrestmapper_test.go

Manual cherry-pick of https://github.com/kubernetes-sigs/controller-runtime/pull/2208
There were conflicts in the test file. I just went with the version from main
EDIT: now resolved conflicts in a way that it works :)

[release-0.14] 🐛 Allow lazy restmapper to work with CRDs created at runtime 

---

pkg/cache/multi_namespace_cache.go
pkg/controller/controllertest/util.go
pkg/internal/source/event_handler.go
pkg/internal/source/kind.go
pkg/source/source.go

Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/2222
I have manually verified this compiles with client-go 1.26 and 1.27, but I am not sure how to get test coverage of this; likely we will not be able to.

🐛 Add cross-version compatibility with client-go 1.27

---

pkg/cache/cache.go

Now we call defaultOpts for MultiNamespaceCache twice: 
1. [Before](https://github.com/kubernetes-sigs/controller-runtime/blob/c304e7ec2ee7879f53ce69c12a7aa133853fccdb/pkg/cache/cache.go#L197) entering newMultiNamespaceCache
2. And right [after](https://github.com/kubernetes-sigs/controller-runtime/blob/c304e7ec2ee7879f53ce69c12a7aa133853fccdb/pkg/cache/multi_namespace_cache.go#L59)
This PR prevents this and ensures that defaultOpts is called only once inside newMultiNamespaceCache function.

🌱 Don't call defaultOpts for MultiNamespaceCache twice

---

pkg/cache/cache.go
pkg/cache/cache_unit_test.go

This patch enables unstructured objects that have populated GVKs to be used as keys when configuring `ByObject` cache options.
Prior to this patch, a cache setup like the following causes `manager.New` to return an error with "unstructured object has no kind":
```go
obj := &unstructured.Unstructured{}
obj.SetGroupVersionKind(schema.GroupVersionKind{"example.com", "v1", "MyKind"})
_, err := manager.New(cfg, manager.Options{
NewCache: cache.BuilderWithOptions(cache.Options {
ByObject: map[client.Object]cache.ByObject{
obj: cache.ByObject{}
},
})
})
```

🐛 Preserve unstructured object GVKs in cache.Options.ByObject

---

pkg/cache/multi_namespace_cache.go

This commit fixes a bug that was brought in long ago in #1520. When the object's scope is not deterministic from the RESTMapper it should return an error instead of ignoring it.

:bug: fix a bug in multinamespaced cache implementation

---

pkg/client/options.go
pkg/client/options_test.go

Ensure that we can force when applying to subresources (in particular status)
FIxes #2125

🐛  ForceOwnership should work with subresources

---

pkg/manager/internal.go
pkg/manager/manager.go
pkg/manager/manager_test.go
pkg/manager/server.go

This PR introduces a configurable standalone server for serving pprof to manager, just like the health and metrics server.
fixes #1779 
Additional thoughts:
I've been aware of `metricsExtraHandlers` introduced in #824 which might be an alternative for end users to serve pprof, but I don't think it's quite appropriate to do so, mainly for these two reasons:
1. pprof is a language built-in feature which is widely used, so it's more appropriate to make its server built-in in the library rather than let end users construct and run themselves in every controller.
2. `metricsExtraHandlers` bind all handlers to metrics listener which is not that general and flexible, it cannot meet cases that user want to expose metrics and pprof by different listeners (common use case: a 0.0.0.0: listener for …

✨ Introduce pprof server to manager

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

This change fixes the status handling of the fake client by
* Adding a new `WithStatusSubresource` option and pre-poluating it with
all in-tree resources that have a status subresource
* Making its `Update` and `Patch` not change the status of any such
resource
* Making its status client `Update` and `Patch` only change the status
for any such resources
Since this was completely broken before in that both non-status and
status Update/Patch would always update everything and the status
resources get pre-populated, this is a breaking change. Any test that
relied on the previous behavior would pass incorrectly though, as it
didn't match what the Kubernetes API does.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/2230

:warning: Fakeclient: Fix status handling

---

.github/workflows/golangci-lint.yml
.golangci.yml
go.mod
pkg/cache/internal/informers.go
tools/setup-envtest/store/store_test.go
tools/setup-envtest/workflows/workflows_testutils_test.go

✨ Update Go to 1.20

---

pkg/client/options.go

Mostly sugar, but useful in some cases.
/assign @alvaroaleman @sbueringer

🌱 Add client.InNamespace("xyz").AsSelector()

---

pkg/envtest/webhook.go

Similar to how it's done for the CRD installation, set default webhook options for timeout/poll interval values.
This avoids getting MaxTime=0 which changes its behaviour when moving from k8s deprecated wait.PollImmediate() to wait.PollUntilContextTimeout().
Spun off from: #2189

:seedling: envtest: set default webhook options for polling

---

pkg/source/source.go

If multiple controllers are listening to the same channel source, `Start()` will be called multiple times by the manager. This causes a race condition setting `cs.stop`
Since `cs.stop` appears not to be used, it seems simplest to remove this line.

🐛 Fix race condition in channel source

---

pkg/internal/source/kind.go

🌱 Kind source should expose type information on timeout

---

pkg/webhook/server.go
pkg/webhook/server_test.go

This change rewrites some of the webhook server logic to better handle the user setting a custom configuration for the TLS options by providing a custom GetCertificate function. When that's present, we won't start a certwatcher routine. The change also updates the documentation to better clarify when each of the options are effective.
Fixed #2269

🌱 Handle TLSOpts.GetCertificate in webhook

---

pkg/client/client.go
pkg/client/client_test.go

Before this PR the client ignored the passed in Cache.DisableFor option as we were just building a map but not using it

🐛 Client: use passed in Cache.DisableFor option

---

pkg/certwatcher/certwatcher.go
pkg/certwatcher/certwatcher_test.go

🌱 Add certwatcher callback

---

pkg/manager/internal.go

Because they should be. [Backgrounds here](https://github.com/kubernetes-sigs/controller-runtime/pull/1943#discussion_r1038896709).

🌱 Make metrics and health probe servers be Runnables

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

This change adds support for evictions into the fakeclient. 
Prior to this, it would just error on any subresource creation.
/cc @vincepri @sbueringer

:sparkles: Fakeclient: Add support for evictions

---

pkg/builder/controller_test.go
pkg/controller/controller.go
pkg/controller/controller_test.go

Currently, `controller.Options` embedds `config.Controller`. This makes its usage pretty annoying, to set `MaxConcurrentReconciles` for example, one has to do it like this:
```
controller.Options{config.Options{MaxConcurrentReconciles: 8}}
```
This makes it harder to find what options exist and causes a lot of churn for downstream consumers. Re-Define the fields from `config.Controller` in `controller.Options` instead to avoid that.
This also fixes some defaulting bugs where we wouldn't default `MaxConcurrentReconciles` and `CacheSyncTimeout` from the `config.Controller` setting in the manager.

⚠️ Flatten fields in controller.Options

---

pkg/log/deleg.go
pkg/log/log.go
pkg/log/log_test.go

:warning: Unexport delegating logger, remove async init

---

pkg/manager/internal.go

This PR reverts part of: https://github.com/kubernetes-sigs/controller-runtime/pull/2275
On main we have the following sequence in controllerManager.Start():
* ...
* add health probe server
* ...
* Start webhook runnables
* Start cache runnables
* Start other runnables (including health probe server)
Usually this works except under the following circumstances (concrete example):
* The controller implements a reconciler for a CRD called MachineDeployment
* MachineDeployment has multiple apiVersions and thus the controller also implements a conversion webhook
* There are MachineDeployments in the older apiVersion stored in etcd
Now we have the following problem:
* Start cache runnables fails because caches are not getting ready
* Caches are not getting ready because MachineDeployment list …

🐛 Revert: move health probes to runnable

---

pkg/client/example_test.go

Noticed a typo in the DeleteAllOf example.

📖 Fix typo in client example

---

pkg/builder/webhook.go
pkg/webhook/admission/http.go
pkg/webhook/admission/webhook.go
pkg/webhook/admission/webhook_test.go
pkg/webhook/authentication/http.go
pkg/webhook/authentication/webhook.go

This PR changes UID consistently to requestID + some smaller cleanups.
Result logs look like this:
> {"ts":1684151281449.506,"caller":"admission/http.go:96","msg":"admission: received request","v":1,"webhookGroup":"cluster.x-k8s.io","webhookKind":"MachineDeployment","MachineDeployment":{"name":"my-cluster-default-worker-topo-1-nfx2l","namespace":"default"},"namespace":"default","name":"my-cluster-default-worker-topo-1-nfx2l","resource":{"group":"cluster.x-k8s.io","version":"v1beta1","resource":"machinedeployments"},"user":"kubernetes-[redacted secret grafana:admin-user]","requestID":"ab1c2094-178c-413b-b805-f2e2a7ba391d"}
> {"ts":1684151281450.1562,"caller":"v1beta1/machinedeployment_webhook.go:365","msg":"admission: Replica field has been defaulted to …

✨ Cleanup webhook logging

---

pkg/manager/manager.go

xref: https://github.com/kubernetes-sigs/controller-runtime/pull/2293#issuecomment-1550011362

🌱 Fix webhook options deprecation notes

---

go.mod
pkg/client/fake/client.go
pkg/client/fake/client_test.go

Closes https://github.com/kubernetes-sigs/controller-runtime/issues/2184
The current fake client methods diverge from the behavior of real k8s. This results in scenarios where an object can be created or modified to have a deletionTimestamp and no finalizers, with a delay in garbage collection, causing inaccurate or ambiguous behavior in  test cases that use the fake client.
Bring fake client behavior closer in line with real k8s behavior by modifying the following:
- Update() and Patch() will reject changes that set a previously-unset deletionTimestamp
- Create() will ignore a deletionTimestamp on an object
- Build() will error if initialized with an object that has a deletionTimestamp but no finalizers; but will accept a deletionTimestamp if it has finalizers.

⚠ Update fake client deletionTimestamp behavior

---

pkg/log/zap/zap_test.go

Removes the skip added for k8s.io v0.27.1
Fixes #2297

🌱 Re-enable tests for v0.27.2

---

pkg/webhook/admission/http.go
pkg/webhook/authentication/http.go

Tested a bit with the CR beta and the logs are very verbose.
I"m not sure if that was also the case with v0.14 but 4 seems more reasonable.
xref: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md

⚠ Change webhook request received / response written logs to log level 4

---

go.mod
go.sum

This pulls in
https://github.com/gomodules/jsonpatch/releases/tag/v2.3.0. This patch fixes performance issues in some cases (large arrays of objects). This is a fairly common case in Kubernetes objects -- we saw in Pods with 1000 env vars, a trivial patch can take 2s of 100% CPU, and the scaling is n^2. With the patch, its ~instant.

:seedling: bump jsonpatch to v2.3.0

---

pkg/client/unstructured_client.go

When I use the client of controller-runtime to construct a `subResourceClient` by passing in unstructured obj, I found a log which made me confused, ""unstructured client did not understand object: *unstructured.Unstructured".
I went through the codebase and found that logs are wrongly printed.

✨Fix logs in unstructured client

---

pkg/client/apiutil/restmapper.go
pkg/client/apiutil/restmapper_test.go

Resolves https://github.com/kubernetes-sigs/controller-runtime/issues/2345

🐛 fix unspecified KindsFor version

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

The fake client of subresource is unable to correctly handle the case of resource version conflict when updating. The phenomenon is that it did not return a 409 status error.
Ref:
#2362 
Signed-off-by: iiiceoo <iiiceoo@foxmail.com>

🐛 fakeClient.Status().Update(...) cannot recognize resource version conflicts

---

pkg/client/options.go
pkg/client/options_test.go

This pr is try to fix issue #2098, where `HasLabels` and `MatchingLables` will step on each other (or overwrites each other)

🐛 hasLabels and matchingLabels step on each other

---

designs/cache_options.md

Prior art
* https://github.com/kubernetes-sigs/controller-runtime/pull/1962
/cc @joelanford @vincepri @sbueringer @FillZpp

:book: Add a design for cache options configuration

---

pkg/client/fake/doc.go

`NewFakeClientWithScheme(scheme, initObjs...)` is deprecated, but the doc for fake-client still uses it. 
This PR updates the doc to use the recommended way to create a fake client.
The updated part is the red box of following image.

✨ fake: Update fake client doc.go to avoid the deprecated method

---

.github/workflows/golangci-lint.yml
.golangci.yml
pkg/cache/cache_test.go
pkg/cache/informer_cache_unit_test.go
pkg/certwatcher/certwatcher_test.go
pkg/client/apiutil/restmapper_test.go
pkg/client/client_test.go
pkg/client/fake/client_test.go
pkg/client/namespaced_client_test.go
pkg/client/options_test.go
pkg/config/config_test.go
pkg/controller/controller_suite_test.go
pkg/controller/controllerutil/controllerutil_test.go
pkg/envtest/webhook_test.go
pkg/finalizer/finalizer_test.go
pkg/internal/controller/controller_test.go
pkg/internal/recorder/recorder_test.go
pkg/internal/testing/process/bin_path_finder_test.go
pkg/manager/manager_test.go
pkg/source/source_test.go
tools/setup-envtest/workflows/workflows_testutils_test.go

:seedling: Update golangc-lint to v1.53

---

pkg/controller/controller.go

Just moving away from the deprecated func. Behavior stays exactly the same
Fixes #2385

🌱 Use NewRateLimitingQueueWithConfig instead of deprecated NewNamedRateLimitingQueue

---

pkg/log/log.go

Example:
```bash
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed. Detected at:
>  goroutine 1 [running]:
>  runtime/debug.Stack()
>  	/usr/local/go-faketime/src/runtime/debug/stack.go:24 +0x65
>  main.main()
>  	/tmp/sandbox4160348257/prog.go:13 +0x2b
```

🌱 Add a prefix to the stack trace printed after SetLogger timeout

---

alias.go
pkg/manager/manager.go

Add documentation to clarify the ContentType behavior. `application/vnd.kubernetes.protobuf` will be used for all built-in resources by default.
fixes #2408

📖 Add documentation to clarify the ContentType behavior

---

pkg/builder/controller.go
pkg/builder/options.go
pkg/builder/webhook.go

🌱 Minor improvements to godoc, code style in builder pkg

---

pkg/cluster/cluster.go
pkg/envtest/webhook_test.go
pkg/manager/manager.go
pkg/manager/manager_test.go
pkg/webhook/server.go
pkg/webhook/server_test.go
pkg/webhook/webhook_integration_test.go

⚠ Remove deprecated manager, webhook and cluster options

---

pkg/builder/controller.go
pkg/builder/controller_test.go

Just saw this and was confused why we would want this behavior. I also looked at https://github.com/kubernetes-sigs/controller-runtime/issues/1021 but I don't understand the reasoning.
If we want a silent overwrite behavior I would have expected Build/Complete to overwrite the reconciler from the previous set ctrlOptions not the other way around
I think this implementation still covers the original ask, folks can pass in a `nil` reconciler to Build/Complete

⚠ builder: return error when multiple reconcilers are set

---

pkg/cache/cache_test.go
pkg/cache/multi_namespace_cache.go
pkg/client/fake/client.go
pkg/client/fake/client_test.go
pkg/controller/controllerutil/controllerutil.go
pkg/envtest/server.go
pkg/envtest/webhook_test.go
pkg/log/zap/zap.go

⚠ Remove deprecated funcs & fields

---

pkg/manager/internal.go
pkg/manager/runnable_group.go
pkg/manager/runnable_group_test.go

This PR introduces a new runnable group for basic servers (health probes, metrics and pprof server) of the manager and make it start before any other runnables. This can resolve the [cyclic dependency issue](https://github.com/kubernetes-sigs/controller-runtime/pull/2321) after we changing these servers to runnables.

🌱 Introduce a new runnable group for basic servers of the manager

---

pkg/internal/controller/controller.go
pkg/webhook/admission/http.go
pkg/webhook/authentication/http.go

This PR adds logs around the Reconcile call. I think this can be very useful to see which objects have been reconciled at which time.
I only added them on log level 4 because otherwise they would be very verbose.
This somewhat limits the benefit they have but they are still useful when running on high log-level or when it's possible to re-configure the log-level of the controller at runtime.

🌱 Add logs around Reconcile call, change webhook logs to log level 5

---

pkg/cache/cache.go
pkg/client/client.go
pkg/cluster/cluster.go
pkg/manager/manager.go

This broke when we added the HTTP client, because the user-agent gets set by a roundtripper that is constructed within `rest.HTTPClientFor`. As a result, we have to default it before we do that. Currently, it ends up being defaulted to `Go-http-client` which is not very useful.

:bug: Fix Defaulting of the User Agent

---

pkg/client/fake/client.go

The fake client logic runs through a switch case, switching on resource group to decide if unconditional update should be allowed for a particular resource or not
However, for rbac resources it checks against the string "rbac" as the group name, as opposed to "rbac.authorization.k8s.io",  which is the actual group name for rbac resources
This issue currently results in an "object modified" error when the fake client tries to update any rbac resource, as it fails the `allowsUnconditionalUpdate` check
This PR fixes that by updating the rbac group name to the correct value

⚠ fake client: use correct RBAC apiGroup name when deciding if to allow unconditional updates

---

pkg/reconcile/reconcile.go
pkg/reconcile/reconcile_test.go

Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/2430 by checking it `err` is nil before calling `Error()` on it.

:bug:  Fix TerminalError(nil).Error() panic

---

pkg/cache/cache_test.go
pkg/cache/internal/cache_reader.go

Hi, currently the cache reader ignores the continue option. This behavior could lead to a hard-to-find bug when a user mistakenly tries to paginate with the limit and continue option by the cache client. I faced the problem, and that was quite hard to debug since the limit option works correctly and I always received the first page only. I believe it is more user-friendly if we just return an error when a user mistakenly set the option instead of ignoring it silently. Thanks for your review!

:warning: Return an error if the continue list option is set for the cache reader

---

pkg/reconcile/reconcile.go

It isn't obvious for people new to the project that the returned error is part of the control flow and that if it is set, the Result will be ignored. Add some godocs to clarify that.

:book: Clarify that the reconcile.Result is ignored on non-nil error

---

.github/workflows/pr-dependabot.yaml

Follow-up to: https://github.com/kubernetes-sigs/controller-runtime/pull/2447
Looks like someone has fun with the github support mail: 
So now switching to the obscure mail that somehow works that we use in CAPI.

🌱 Fix mail of dependabot action commit

---

pkg/webhook/admission/decode.go
pkg/webhook/admission/decode_test.go

Closes: https://github.com/kubernetes-sigs/controller-runtime/issues/2429

 🐛 Add missing return statement in the webhook admissions func

---

Makefile
pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/cache/informer_cache.go
pkg/cache/internal/informers.go
pkg/client/client.go
pkg/client/client_test.go
pkg/manager/manager_test.go

This commit allows users to opt out of the "start informers in the background" behavior that the current cache implementation uses. Additionally, when opting out of this behavior, the client can be configured to do a live lookup on a cache miss. The default behaviors are:
pkg/cache: backfill data on a miss (today's default, unchanged)
pkg/client: live lookup when cache is configured to miss
Fixes #2397

✨: pkg/cache: add options for cache miss policy

---

pkg/internal/controller/controller.go

🌱 log warning if error and non-zero Result returned

---

pkg/builder/controller_test.go
pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/cache/delegating_by_gvk_cache.go
pkg/cache/informer_cache.go
pkg/cache/informertest/fake_cache.go
pkg/cache/internal/informers.go
pkg/cache/multi_namespace_cache.go
pkg/internal/controller/controller_test.go

This PR is split off from #2285 
It allows users to retrieve an informer before an informer has finished bootstrapping. This is valuable as it allows users to add/remove listeners without waiting for the informer to be ready. Since a listener is a passive observer of events, it does not require the informer to be fully initialized. Not waiting for full initialization can improve bootstrapping times and enable more flexibility with how dynamic watches are handled.

✨ Allow non-blocking retrieval of informers

---

pkg/manager/manager.go
pkg/manager/manager_test.go

Resolves https://github.com/kubernetes-sigs/controller-runtime/issues/2378
```release-note
None
```
Cherry-picked from (e92e5eebd80c46bb37d1c)
Manual cherry-pick from https://github.com/kubernetes-sigs/controller-runtime/pull/2461

[release-0.16] 🐛 Add corev1, coordinationv1 scheme for leader election when LeaderElection manager option is true 

---

pkg/manager/manager.go

During creation of the manager, the default `cluster.HTTPClient` is being used during leader election causing cert issues and not responding to events because of the conflict of the kubeconfig it uses for the manager.  It never uses the kubeconfig from the leaderElectionConfig when being set.  
This PR sets that value and creates a httpClient from the restConfig passed in on the `options.LeaderElectionConfig`
Resolves https://github.com/kubernetes-sigs/controller-runtime/issues/2454

🐛 Use http client from leaderElectionConfig

---

pkg/cache/cache.go
pkg/cache/cache_test.go

Previously `byObject.Namespaces` was always defaulted to `DefaultNamespaces` if `byObject.Namespaces` was nil independent of object is namespaced or not. This PR fixes it so  `byObject.Namespaces` is defaulted to `DefaultNamespaces` only for namespaces object.

🐛 Default namespace only for namespaced object

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

During updating with the status client, it is shown that the metadata/labels will come with the subresource client.  To mitigate this, updating the method to only use the old object in the tracker, will allow the status to be copied from the new object and put in the update chain to the fake client tracker. 
Resolves: https://github.com/kubernetes-sigs/controller-runtime/issues/2474

🐛 Do not update anything but status when using subresource client 

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

Before this, Update and Patch requests will override to-level status fields for objects that have a status resource if the status was initially empty.
This happens because the code to set the status to what we already have in the unupdated object converts the object into a `map[string]any` using json serialization/deserialization, copies the original `status` field, then converts back. The json deserializer unfortunatelly does not properly clear the target, allowing data to remain that is absent in the json serialization.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/2478
/cherrypick release-0.16

:bug: Fix status subresource getting updated on Update when it is empty

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go
pkg/client/interfaces.go

Prior to this, we overwrote the passed in pointer to `obj` on status update, which means that the caller can never see the updated object after the call. This changes makes us instead overwrite the value behind the pointer, so that it gets propagated back to the caller.
@berlin-ab I like this approach more, as it seems a bit simpler and keeps the changed contained to the place that causes the need for them. WDYT?
/cc @berlin-ab @troy0820 
Superseeds https://github.com/kubernetes-sigs/controller-runtime/pull/2486
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/2487

:bug: Fix returning object after status update

---

pkg/client/apiutil/errors.go
pkg/client/apiutil/restmapper.go
pkg/client/apiutil/restmapper_test.go

:bug: Return NoResourceMatchError when appropriate for backwards compatibility.

---

pkg/cache/cache.go
pkg/cache/cache_unit_test.go

When using BuilderWithOptions some of the inherited (manager/cluster) options are lost.
If they were provided, they would be stronger than the cache package defaults
(In my case, the default dynamic mapper is overridden with discovery).
From a quick look at 0.15/0.16 this is not an issue there.

[release-0.14] 🐛 inherited defaults not respected in cache BuilderWithOptions

---

examples/scratch-env/go.sum
go.mod
go.sum

Fixed in 3.11.0 per comment https://github.com/emicklei/go-restful/issues/521#issuecomment-1684876345
Resolves #2505

🐛Update dependency go-restful to 3.11.0

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/2503

 🐛 Correctly identify if patch call was made on status

---

pkg/cache/cache.go
pkg/cache/internal/informers.go

This would resolve #2395 
/hold

✨ SetErrorWatchHandler on SharedIndexInformer 

---

example_test.go
pkg/builder/example_test.go
pkg/client/example_test.go
pkg/handler/example_test.go

- Adds an example showing how to use [Server Side Apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/) with controller-runtime client and structs from _k8s.io/client-go/applyconfigurations/*_
- Adds an example how to watch any resource and map its changes to main reconciled resource

:book: Add more examples in documentation

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

In order to prevent unintentional mutations outside of the status during a status update, the non-status fields are copied back onto the passed object.
This operation now gracefully handles both unstructured and typed objects. Previously, it would panic if an unstructured object was passed for a GVK known to the scheme, as internally the object within the tracker is converted to the typed equivalent. The two types cannot be directly assigned to each other and instead must be copied.
Adds a failing test to demonstrate the bug, and the fix to make the test pass.
Resolves #2493

🐛 Handle unstructured status update with fake client

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

In order to prevent unintentional mutations outside of the status during a status update, the non-status fields are copied back onto the passed object.
This operation now gracefully handles both unstructured and typed objects. Previously, it would panic if an unstructured object was passed for a GVK known to the scheme, as internally the object within the tracker is converted to the typed equivalent. The two types cannot be directly assigned to each other and instead must be copied.

[release-0.16] 🐛 Handle unstructured status update with fake client

---

pkg/controller/controllerutil/controllerutil.go
pkg/controller/controllerutil/controllerutil_test.go

When creating https://github.com/kubernetes-sigs/controller-runtime/pull/2462 it was discussed that to achieve the ask of the issue #2381 two functions can help remove ControllerReferences to get around the errors of it not being able to be overwritten. 
These two functions  _(and not to be confused with the original PR that allows removal of any owner reference)_, allows the caller to see if the owner reference they want to remove in fact is a "ControllerReference" _(controller = true)_
This functionality is present with finalizers and will be helpful when trying to mitigate issues with trying to overwrite the owner reference on an object.

🌱 Add function RemoveControllerReference and HasControllerReference 

---

pkg/manager/manager.go

The `errChan` is an unbuffered channel, and if the context of the `Start` function ends, it may cause the `goroutine` writing to the `errChan` to not exit properly.
https://github.com/kubernetes-sigs/controller-runtime/blob/5771399a8ce5c84b11a543bb35f10646537602d5/pkg/manager/internal.go#L430

:bug: fix: goroutine leak

---

pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/cache/multi_namespace_cache.go

This change allows to define a cache selector config that applies to all namespaces that themselves do not have an explicit config. An example would be "Cache all namespaces without selector, except for namespace foo, there use labelSelector bar=baz".
More as a side effect than intentionally, this also makes it valid to use the empty string as a key in the `Namespaces` and `byObject.Namespaces` config of the cache. This is very useful to for example have a `namespace` CLI flag that might be empty.
This change is the last missing bit to finish the implementation of the [cache options design doc](./designs/cache_options.md).
Sidenote: If someone can come up with a less wordy title that describes what this does, that would be nice :)

:sparkles: Cache: Allow defining options that apply to all namespaces that themselves have no explicit config

---

hack/check-everything.sh
pkg/handler/eventhandler_test.go

1.24.2 has been EOL for quite some time. There are no test binaries for 1.28.1 or 1.28.2, but 1.28.0 exists.

🌱 Bump envtest to 1.28.0

---

pkg/cache/cache_test.go
pkg/cache/internal/cache_reader.go
pkg/client/example_test.go
pkg/client/fake/client.go
pkg/client/fake/client_test.go
pkg/client/options.go
pkg/internal/field/selector/utils.go
pkg/internal/field/selector/utils_test.go

add support for multiple indexes when using client.MatchingFields
Fix https://github.com/kubernetes-sigs/controller-runtime/issues/612

✨client: client.MatchingFields support multiple indexes

---

RELEASE.md
tools/setup-envtest/README.md

```bash
pkg/mod/go.uber.org/multierr@v1.10.0/error.go:224:20: undefined: atomic.Bool
note: module requires Go 1.19
```
Using `go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest` with go versions < 1.19 will complain that this can not be installed due to the above dependency needing 1.19.  To still be able to use latest, updating the documentation to show that 1.19 is needed and to use this tool with older versions of go, commit hashes from older versions can be used as setupenv-test does not have tags included with the releases. 
Resolves #2537 
Resolves https://github.com/kubernetes-sigs/controller-runtime/issues/2526

 📖Update go version in setupenv-test README. Update release-notes link in RELEASE

---

pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/cache/delegating_by_gvk_cache.go
pkg/cache/informer_cache.go
pkg/cache/informertest/fake_cache.go
pkg/cache/internal/informers.go
pkg/cache/multi_namespace_cache.go
pkg/internal/syncs/syncs.go
pkg/internal/syncs/syncs_test.go

This PR shows how Gatekeeper has forked controller runtime to support the dynamic addition/removal of informers.
Happy to flesh this out if people are interested. Not sure what the correct licensing actions are for moving code across CNCF projects.
This is related to #2159 and #1884
Basically, something like this PR will be necessary to clean up informers once no more controllers are using them.
In the interim, having this code would be helpful to Gatekeeper by eliminating our need to maintain a fork, which has been fairly labor intensive. It also may give other members of the community a way to meet their needs for dynamic watches while waiting for the dynamic controller/reference counting approach to be implemented.

🌱 Proposal for dynamic informer cache

---

pkg/internal/testing/controlplane/kubectl.go
pkg/internal/testing/process/procattr_other.go
pkg/internal/testing/process/procattr_unix.go
pkg/internal/testing/process/process.go
pkg/internal/testing/process/process_test.go

When envtest creates new processes, it wasn't setting the process group to the parent, when the main process is killed or it panics, all the other processes are orphaned, and need to be killed separately.
In addition, if for some reason we can't shutdown a process cleanly, we should try to SIGKILL before returning from Stop.

🌱 envtest: improve process cleanup

---

pkg/envtest/komega/default.go
pkg/envtest/komega/interfaces.go

This fixes the komega `Update` and `UpdateStatus`  godoc examples. I wanted to use these functions in a project and got confused by the godoc (examples).

:book: Fix komega godoc examples

---

pkg/cache/cache.go
pkg/client/apiutil/apimachinery.go
pkg/handler/eventhandler_test.go

The discovery restmapper was unused except for two places that we missed (when creating a cache directly as opposed through the manager and in a test). The discovery restmapper only ever loads mappings once during startup and is unable to reload them if they change. It also isn't lazy and we don't want anyone using it.
Instead, the `DynamicRESTMapper` should be used.

⚠️ Remove apiutil.NewDiscoveryRESTMapper, use DynamicRESTMapper by default for cache

---

pkg/client/options.go

Manual cherry-pick of https://github.com/kubernetes-sigs/controller-runtime/pull/2529

[release-0.16] :running: Make client.MatchingLabels faster

---

pkg/client/fake/client.go

Kubernetes released [v1.29.0](https://kubernetes.io/blog/2023/12/13/kubernetes-v1-29-release/#removal-of-the-v1beta2-flow-control-api-group) and with that release was the deprecation and removal of flowcontrol v1beta2.  
This PR changes the fake client to not serve that for v1.29.0 when controller-runtime v0.17 gets released

✨Add flowcontrol api v1 for Kubernetes v1.29.0

---

pkg/client/apiutil/restmapper.go
pkg/client/apiutil/restmapper_test.go

/kind bug
This PR fixes the new RESTMapper implementation to properly handle cases where an API Group / GroupVersion is not present in the system. Clients expect No{Kind,Resource}MatchErrors in this case.
The first commit increases the accuracy of the RESTMapper tests to verify the described expectations.
The second commit implements the actual fix.
The changes are from @timebertt PR https://github.com/kubernetes-sigs/controller-runtime/pull/2425. 
The PR #2425 is still needed as with non existing CRDs  we are getting `failed to find API group` error.

⚠️  RESTMapper: don't treat non-existing GroupVersions as errors

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

Currently, the fakeclient unconditionally sets metadata for all objects retrieved through it. This causes two problems:
* It differs from the behavior of the real client, except for the cached one if `DeepCopy` is enabled and might lead ppl to think that they can rely on `TypeMeta` being populated, which is absolutely not the case
* It causes panics for types that have `TypeMeta` defined as pointer, making it impossible to use the client with them
This PR changes the behavior to only populate TypeMeta for `unstructured`.

:warning: Fakeclient: Only set TypeMeta for unstructured

---

pkg/controller/controllerutil/controllerutil.go

Add documentation note to the `CreateOrUpdate` and `CreateOrPatch` methods to describe how they handle (or  not) the status sub resource of the object  being modified
Work on addressing #2627

📖 Add documentation note describing behavior with status

---

examples/crd/pkg/resource.go
pkg/builder/example_webhook_test.go
pkg/webhook/admission/defaulter.go
pkg/webhook/admission/validator.go
pkg/webhook/admission/validator_custom.go
pkg/webhook/alias.go

`admission.Validator/Defaulter` require to import controller-runtime into api packages. This is not recommended, as api packages should themselves not have any dependencies except to other api packages in order to make importing them easy without dependency issues and possibly incompatibilities.
This change marks the two as deprecated. We are not going to remove them yet to give folks some time to migrate off them.
Closes https://github.com/kubernetes-sigs/controller-runtime/issues/2596

:warning: Deprecate admission.Validator and admission.Defaulter

---

pkg/webhook/admission/http.go
pkg/webhook/admission/http_test.go
pkg/webhook/authentication/http.go
pkg/webhook/authentication/http_test.go

This PR adds a LimitedReader which prevents DOS attacks due to OOM caused by the `io.ReadAll` function.
Depends on https://github.com/kubernetes-sigs/controller-runtime/pull/2604.
Code is based on https://github.com/kubernetes/kubernetes/blob/c28c2009181fcc44c5f6b47e10e62dacf53e4da0/staging/src/k8s.io/pod-security-admission/cmd/webhook/server/server.go

⚠️ Use limited reader in webhooks

---

pkg/reconcile/reconcile.go
pkg/reconcile/reconcile_test.go

Part of #2582.
Fixes #2221.
This PR adds a new `reconcile.ObjectReconciler` interface to eliminate the following common boilerplate.
```go
func (r *MyReconciler) Reconcile(ctx context.Context, req reconcile.Request) (reconcile.Result, error) {
example := &examplev1.Example{}
if err := r.Get(ctx, req.NamespacedName, example); err != nil {
return ctrl.Result{}, client.IgnoreNotFound(err)
}
// Do business logic…
}
```
`ObjectReconciler` leverages generics to write reconcilers in terms of deserialized instances of `client.Object`. It does not replace the existing `reconcile.Reconciler` interface.
Developers can create a controller with an `ObjectReconciler` by calling the `AsReconciler` function.
```go
builder.ControllerManagedBy(manager).
For(&corev1.ConfigMap{}). …
```

✨ Add reconcile.ObjectReconciler

---

examples/scratch-env/go.sum
go.mod
go.sum

Changes an import of `github.com/evanphx/json-patch` to `github.com/evanphx/json-patch/v5`. Other codepaths use only json-patch/v5. It removes 1 direct dependency

🌱 Downgrade github.com/evanphx/json-patch library to v4 to match upstream

---

pkg/metrics/workqueue.go

Controllers making many external requests in large clusters may have normal operating latency on the order of ~100s. Add buckets that cover the range, allowing metric backends to interpolate percentile estimates properly.
For #2625

✨ Add 100/1000s buckets for prometheus workqueue histograms

---

pkg/client/client.go

Fix comments related to the read/write functionality of the client to reflect that the client reads from a local cache or API server, and writes directly to the API server.

:book: Fix Client Read/Write Functionality Comments

---

examples/scratch-env/go.mod
examples/scratch-env/go.sum
go.mod
go.sum
pkg/client/patch_test.go

This change bumps https://github.com/evanphx/json-patch in order to pick up a bugfix that made it truncate large int64s because it internally treated them as float64s.
Ref https://github.com/evanphx/json-patch/issues/189
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/2603

:bug: Don't truncate large int64s in MergePatch

---

pkg/metrics/server/server.go

The reason for this change is having the ability to set a custom ListenConfig on the metric server listener.
The reason I need (my company needs) it is that it will allow us to set unix.SO_REUSEPORT flag which works around an edge case when a port is ever leaked and you are using the host network for your controller.

✨ Add ListenerConfig for metrics server options

---

pkg/envtest/server.go

Fixes #2626
This change adds a `waitForDefaultNamespace` call which polls the apiserver for the existence of the default namespace immediately after control plane startup. This is needed because we've seen that there can be flakes when leveraging `envtest` if you expect the `default` namespace to be there immediately after startup but the namespace hasn't actually propagated so that the apiserver can see it.

:seedling: WaitForDefaultNamespace while starting up envtest

---

pkg/client/apiutil/restmapper.go
pkg/client/apiutil/restmapper_test.go

This avoids:
- Extra calls to `https://host/apis/<group>/<version>` when a version seen before and cached in apiGroups is deleted or marked as not served.
- Returnning a valid mapping for a cached version that is deleted or not served anymore.
I would like backport this fix to v0.16 (or at version of it since it won't apply cleanly). It would help us solve this issue in cluster-api https://github.com/kubernetes-sigs/cluster-api/issues/10032

🐛 Clean restmapper cache if a version is notFound

---

pkg/client/apiutil/restmapper.go
pkg/client/apiutil/restmapper_test.go

This is backport of https://github.com/kubernetes-sigs/controller-runtime/pull/2663
It changes a bit the code to maintain v0.16 behavior and return a `ErrResourceDiscoveryFailed` error when a version is not found. However, it cleans up the cache and refreshes the underlying mapper when this happens, avoiding getting the same error in the next reconciliation.
This avoids:
- Extra calls to https://host/apis/<group>/<version> when a version seen before and cached in apiGroups is deleted or marked as not served.
- Returning a valid mapping for a cached version that is deleted or not served anymore.

[release-0.16] 🐛 Avoid extra calls for not found resource

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

The fakeclient currently considers an apply patch to be a strategic merge patch. This is completely wrong, those are different things and apply patches are not supported in the fakeclient, because in order to support them it would need the entire SSA logic which isn't implemented in upstream yet.

:bug: Fakeclient: Do not consider an apply patch to be a strategic merge patch

---

pkg/client/apiutil/restmapper.go
pkg/client/apiutil/restmapper_wb_test.go

This fixes a bug introduced by my previous PR https://github.com/kubernetes-sigs/controller-runtime/pull/2663
When a group version is not found, if the group version is cached in apiGroups but not cached in knownGroups, the cache is not invalidated. Moreover and even worse, in that scenario an error is returned.
This is only an issue under the very rare case where a version has been removed during a call just after caching in apiGroups but before it's cached in knownGroups.
After the change now an error is never returned for not found versions no matter if the version was cached or not. And now the two different caches are checked and invalidated independently.

🐛 Fix lazy rest mapper cache invalidation

---

pkg/client/apiutil/restmapper.go
pkg/client/apiutil/restmapper_wb_test.go

Backport of https://github.com/kubernetes-sigs/controller-runtime/pull/2687
When a group version is not found, if the group version is cached in apiGroups but not cached in knownGroups, the cache is not invalidated. Moreover and even worse, in that scenario an error is returned.
This is only an issue under the very rare case where a version has been removed during a call just after caching in apiGroups but before it's cached in knownGroups.
After the change now an error is never returned for not found versions no matter if the version was cached or not. And now the two different caches are checked and invalidated independently.

[release-0.16] 🐛 Fix lazy rest mapper cache invalidation

---

pkg/predicate/predicate.go

I didn't benchmark this or anything, but thought that using this was better than reflect.
The maps package was introduced in go 1.21.

:seedling: Compare labels and annotations using maps.Equal

---

.github/workflows/golangci-lint.yml
pkg/builder/webhook_test.go
pkg/internal/testing/certs/tinyca_test.go
pkg/internal/testing/controlplane/apiserver_test.go
pkg/manager/manager_test.go

🌱 Update golangci-lint to v1.56.2

---

OWNERS_ALIASES

🌱 Remove outdated testing framework approvers

---

.github/workflows/golangci-lint.yml
.github/workflows/pr-dependabot.yaml
.github/workflows/verify.yml

🌱 Improve github actions dependencies versions and permissions

---

pkg/source/source.go

This PR contains minor typo fixes in docstrings.

🌱  Minor typo fixes in docstrings

---

.github/workflows/ossf-scorecard.yaml

🌱 Update scorecard github action

---

.github/workflows/golangci-lint.yml
.github/workflows/ossf-scorecard.yaml
.github/workflows/pr-dependabot.yaml

🌱 Pin checkout action in golangci-lint action, bump checkout action, use consistent tag format

---

pkg/webhook/admission/decode.go
pkg/webhook/admission/decode_test.go
pkg/webhook/admission/defaulter.go
pkg/webhook/admission/defaulter_custom.go
pkg/webhook/admission/validator.go
pkg/webhook/admission/validator_custom.go
pkg/webhook/webhook_integration_test.go

The current implementation allows to create a decoder without a scheme/codecs by just referencing the struct `&admission.Decoder{}` given that codecs is private. The field was filled in before with the inject package which has been removed. This change retains the Decoder definition and makes it an interface, `admission.NewDecoder(scheme)` is now the only way to instantiate our default decoder.
Fixes #2695

⚠ admission.Decoder is now an interface

---

pkg/builder/webhook.go
pkg/builder/webhook_test.go

Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/2739
Adds an error to be returned if the `For()` was done multiple times on a webhook builder instead of accepting the last apiType.  This mimics the behavior expected when dealing with the reconciler builder.  Reference issue above and issue https://github.com/kubernetes-sigs/controller-runtime/issues/1173

🐛 Return error if more than one For() is used on webhook builder

---

pkg/cache/cache.go
pkg/cache/defaulting_test.go

Prior to this patch, configuring for example a labelSelector in `ByObject` and then inheriting namespaces from `DefaultNamespaces` meant that the `labelSelector` would be ignored. This is because if namespaces are configured, we set p a multinamespace cache. If we do that, we expect each namespace entry to have the appropriate selectors configured.
Unfortunately we defaulted the configs for`byObject.Namespaces` before defaulting `byObject.Namespace` itself, causing the above-described issue.
This change also adds a couple more tests for the cache defaulting.

:bug: Cache: Keep selectors when byObject.Namespaces is defaulted

---

pkg/manager/internal.go
pkg/manager/manager_test.go

This PR should address a bug where the runnable group for Leader Election would start while shutting down the manager: https://github.com/kubernetes-sigs/controller-runtime/issues/2719
What's happening?
- https://github.com/kubernetes-sigs/controller-runtime/blob/395cfc7486e652d19fe1b544a436f9852ba26e4f/pkg/manager/internal.go#L344
- https://github.com/kubernetes-sigs/controller-runtime/blob/395cfc7486e652d19fe1b544a436f9852ba26e4f/pkg/manager/internal.go#L521
- https://github.com/kubernetes-sigs/controller-runtime/blob/395cfc7486e652d19fe1b544a436f9852ba26e4f/pkg/manager/internal.go#L521
- Causes the side-effect of starting the runnableGroup: https://github.com/kubernetes-sigs/controller-runtime/blob/395cfc7486e652d19fe1b544a436f9852ba26e4f/pkg/manager/runnable_group.go#L277
However when …

🐛 prevent leader election when shutting down a non-elected manager

---

.github/workflows/golangci-lint.yml
.golangci.yml
pkg/manager/internal.go
tools/setup-envtest/store/store.go

🌱 Update golanci-lint to v1.57.2

---

pkg/manager/runnable_group.go
pkg/manager/runnable_group_test.go

:bug: Runnable group should check if stopped before enqueueing

---

pkg/cache/cache.go
pkg/cache/cache_test.go
pkg/cache/internal/informers.go
pkg/cache/multi_namespace_cache.go

If `Informers` are started a second time, there is a possibility for a data race because it sets a `ctx` field on itself. This write is protected by a mutex, but reads from that field are not.
As it is generally unclear and untested what happens when a cache is started a second time, simply error out to make the user aware that they were starting the cache a second time.

:bug: Prevent race when informers are started more than once

---

pkg/client/client.go
pkg/client/client_test.go

The current signature of SubResourceCreateOptions does not match the interface definition of SubResourceCreateOption because of a typo in the method `ApplyToSubResourceCreate` name. This PR fixes the name.
It also modifies the existing test to actually use the options provided so that if an error like this were to occur again, it would fail to compile.

 🐛 Fix SubResourceCreateOptions signature in subresource client

---

pkg/envtest/komega/default.go

As the `AsyncAssertion` of `gomega` does not support `To` the samples in the documentation have been updated to use `Should`.

:book: Use `Should` instead of `To` in `komega` samples

---

pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/internal/controller/controller.go
pkg/internal/controller/controller_test.go

✨ Add controller workqueue option

---

pkg/client/fieldmanager_test.go
pkg/client/fieldowner.go

This PR adds a new `client` function `WithFieldOwner` that wraps a `client.Client` and adds a `client.FieldOwner` option to all writes from this client. If additional FieldOwner options are specified on methods of this client, the value specified here will be overridden.
I have found myself trying to distinguish between different reconcilers in the same controller-manager process for both troubleshooting purposes (i.e having `managedFields` show the specific controller) and prevent colocated reconcilers from managing the same field.
The alternative was to add `client.FieldManager` to each individual call, which is tedious and error-prone. Instead, I would prefer to have the client use the same fieldManager across all its write calls.

✨ client: Add client-wide fieldManager

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

This PR should fix a bug https://github.com/kubernetes-sigs/controller-runtime/issues/2678 where patching a resource would throw a conflict error when the new object doesn't specify any RV.
- Fix patch by setting the new accessors' RV to the old accessors' RV.
- Add test to ensure the correct behavior

🐛 allow fakeclient to patch CR with no RV

---

pkg/manager/internal.go
pkg/manager/runnable_group.go
pkg/manager/runnable_group_test.go
pkg/manager/server.go

In operator-framework, we have run into a few situations where we need to run a custom HTTP server inside a controller process. In order to decouple from assumptions made by the metrics server (which allows extra handlers to be added), we  need a fully separate server. Since controller-runtime already has a generic HTTP server runnable for use with health probes and pprof handlers, it seems useful to export this implementation to users as well so that they can run their own HTTP servers without having to worry about implementing the `manager.Runnable` interface correctly.

✨ Export HTTP server manager runnable implementation

---

pkg/manager/internal.go

Fixes godoc comment according to 
https://github.com/kubernetes-sigs/controller-runtime/pull/2473/files#r1566017792

📖 manager: fix godoc about http servers

---

pkg/handler/enqueue.go
pkg/handler/enqueue_mapped.go
pkg/handler/enqueue_owner.go
pkg/handler/eventhandler.go

We will need to break them if we want to introduce a generic reconciler with a generic workqueue so mark them as experimental.

📖  Mark Typed Handlers as experimental

---

pkg/cache/cache.go
pkg/cache/cache_test.go

Currently, if there are global namespaces configured and no per-object namesapces, while there is both a global and a per-object labelSelector, we will:
1. Default the namespaces labelSelector from `DefaultLabelSelector`
2. Copy the namespaces including config into `byObject.Namespaces`
And thus end up with the global labelSelector overriding the per-object one, this change fixes that by swapping step 1 and 2.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/2804

:bug: Cache: Fix label defaulting of byObject when namespaces are configured

---

pkg/internal/source/internal_test.go
pkg/internal/source/kind.go

Reverse the nil check in the String function of the internal Kind source to print the type when known.
Fixes: 2add01e7 ("Event, source, handler, predicates: Use generics")

🐛 correct kind source type

---

pkg/manager/internal.go
pkg/manager/manager.go
pkg/manager/manager_test.go
pkg/metrics/server/server.go

🐛 Reintroduce AddMetricsServerExtraHandler on manager

---

alias.go

fix description for SetupSignalHandler() in alias.go to match actual behaviour of returning a context (instead of a channel)

:bug: fix description for SetupSignalHandler() in alias.go

---

pkg/controller/controllerutil/controllerutil.go
pkg/controller/controllerutil/controllerutil_test.go

Currently, `SetOwnerReference()` and `SetControllerReference()` in controllerutil do not allow configuring `BlockOwnerDeletion` field of the underlying `OwnerReference`. This is limiting for scenarios where one would like to use these helper methods but configure `BlockOwnerDeletion` field in a different way than the current defaults.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/2846

✨ controllerutil: configure BlockOwnerDeletion when setting OwnerReference

---

tools/setup-envtest/README.md

Starting with 0.18, setup-envtest requires golang 1.22. This change updates the README to clarify the required golang version. It also provides an alternative install instruction for developers using golang 1.20 and 1.21.
Indirectly relates to #2744 - though from the issue discussion this is tracking release process changes for setup-envtest.
Fixes #2824

:book: Add setup-envtest Instructions for Go < 1.22

---

.github/dependabot.yml

We recently introduce a linter which ensure that our dependencies stay in sync with k/k.
This is important so consumers of CR don't run into compile issues between transitive dependencies of CR & k/k (e.g. if we would use different prometheus versions).
Through this validation we realized that it's basically impossible to bump any dependencies without running out-of-sync in some way with k/k (e.g. even bumping ginkgo leads to a lot of out-of-sync dependencies: https://github.com/kubernetes-sigs/controller-runtime/pull/2842 / https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_controller-runtime/2842/pull-controller-runtime-test/1795194368211030016)
This PR:
* Removes the dependabot config to bump Go modules
* …

🌱 dependabot: remove go modules bumps, bump all actions at once

---

pkg/cache/cache.go

The comment is outdated, support for it was added in Kube 1.30, ref https://github.com/kubernetes/kubernetes/pull/117046

:book: Document that indexes can be added after Informer was started

---

pkg/manager/internal.go

The `Info` method takes key/value pairs as arguments, not format strings. Triggering this code paths panics instead of logging the intended message.

:bug: AddMetricsServerExtraHandler: Info takes key/value pairs

---

pkg/client/apiutil/apimachinery.go
pkg/client/apiutil/apimachinery_test.go

Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/2869
A particular Kind may only be present in a specific version of a Group. When querying the RESTMapper we should include the Version to ensure the cached Group is updated to pick up new Versions as needed.
Without this fix, the failure noted in the linked issue can occur. A new Version can be introduced to a pre-existing Group with new Kinds. Because the cached Group does not include this Version, the namespaced GVK check can fail to find the Kind and will not update the cache. The issue will continue to occur until the controller pod is restarted to re-initialize the cache with new CRDs found in the cluster.

:bug: Fix namespaced GVK check to use version

---

pkg/client/client.go
pkg/client/client_suite_test.go
pkg/client/client_test.go

This adds:
- Tests that verify warning suppression in the client. Note that one of the test fails, confirming the bug. These tests are meant to help us validate the fix, and avoid future regression.
- Ensures, by configuring the warning handler in client-go, that API server warnings are in fact suppressed.
<details>
<summary>Test failure</summary>
```
> Enter [BeforeEach] Client - /home/prow/go/src/sigs.k8s.io/controller-runtime/pkg/client/client_test.go:153 @ 07/24/24 03:22:08.098
< Exit [BeforeEach] Client - /home/prow/go/src/sigs.k8s.io/controller-runtime/pkg/client/client_test.go:153 @ 07/24/24 03:22:08.098 (0s)
> Enter [It] should not log warnings when warning suppression is enabled - /home/prow/go/src/sigs.k8s.io/controller-runtime/pkg/client/client_test.go:273 @ 07/24/24 …
```

:bug: Suppress API server warnings in the client

---

pkg/client/fieldvalidation.go
pkg/client/fieldvalidation_test.go
pkg/client/options.go

This allows our users to enable strict field validation by default for all create, update, and patch requests.
The client can be used in a similar way to the specialized fieldManager-configuring client added in #2771.
Fixes #2859

:sparkles: Adds a client that enables strict field validation by default.

---

pkg/metrics/workqueue.go

Currently, all controller-related metrics use the `controller` label to identity the controller. The workqueue metrics however use the `name` label instead. This is very confusing and unintuitive. Add the `controller` label to the workqueue as well with the same value as the existing `name` label. This keeps the cardinality the same, is backwards-compatible and allows using one label throughout for filtering.

:sparkles: Workqueue: Add `controller` label

---

pkg/source/source.go

The godoc for `Start()` talked about an eventhander, this info is out of date. Also mention that `Start()` must not block.

:book: Improve godocs for source

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

Adds basic GET/UPDATE support to the scale sub-resource according to the docs: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client#SubResourceClientConstructor

✨ Add scale subresource logic to fake client

---

pkg/certwatcher/certwatcher.go
pkg/certwatcher/certwatcher_suite_test.go
pkg/certwatcher/certwatcher_test.go

The current certwatcher misses some events, so if the certificate is maintained in a failsafe-backup way it cannot be watched and fails to get any updates.
For example, when it started with `certwartcher.New("app.crt", "app.key")` and someone does:
```console
curl -O app.crt.new example.com/cert
curl -O app.key.new example.com/key
diff app.crt.new app.crt || (echo "No change"; exit 0)
ln app.crt app.crt.old
ln app.key app.key.old
mv app.crt.new app.crt
mv app.key.new app.key
```
The FD of the file gets these inotify events and stops being watched.
```
# Diff
app.crt OPEN
app.crt CLOSE_NOWRITE,CLOSE
# Move
app.crt ATTRIB
app.crt MOVE_SELF
app.crt ATTRIB
app.crt DELETE_SELF
```
Please take a look at the added test for the implementation of failsafe cert replacement.
The problem is that in …

🐛 Recreate watcher if the file unlinked and replaced

---

pkg/manager/internal.go
pkg/manager/manager_test.go

Runnable implementations that return ctx.Err() cause a spurious "error received after stop" log message.
Fixes #1927

🐛 Quiet context.Canceled errors during shutdown

---

pkg/builder/controller.go

This updates the godocs in the builder to reference the current implementations of `source.Kind` correctly in the godocs that explain `For` and `Owns`.
Also removes the warning in `WatchesRawSource`. With the introduction of the typed handler and predicates, this became a valid use case.

:book: Builder: Improve godocs

---

pkg/predicate/predicate.go

This was missing missing from https://github.com/kubernetes-sigs/controller-runtime/pull/2783.

✨ Add missing generic version of ResourceVersionChangedPredicate

---

pkg/builder/controller.go
pkg/builder/controller_test.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/controller/name.go

When re-using the same name among multiple controllers, they will report to the same metrics and use the same logger. This can be very confusing, might not be obvious and can happen accidentally.
Validate controller names are unique at runtime to avoid all of this.

:warning: Validate controller names are unique

---

pkg/builder/webhook.go
pkg/builder/webhook_test.go
pkg/config/controller.go
pkg/controller/controller.go
pkg/internal/controller/controller.go
pkg/internal/controller/controller_test.go
pkg/internal/controller/metrics/metrics.go
pkg/webhook/admission/metrics/metrics.go
pkg/webhook/admission/webhook.go
pkg/webhook/admission/webhook_test.go

Recover panics in reconcilers & webhooks per default. Also adds corresponding metrics.
Fixes #2167

⚠ Recover panics per default

---

pkg/client/client.go
pkg/client/client_test.go
pkg/client/example_test.go

As a follow-up to https://github.com/kubernetes-sigs/controller-runtime/pull/2887, and https://github.com/kubernetes-sigs/controller-runtime/pull/2896, this removes client.Options.WarningHandler.
Instead of using client.Options.WarningHandler users define config.WarningHandler. This change:
- Reduces the number of "sources" of warning handler configuration from two to one, and thereby reduces confusion.
- Allows users to define custom warning handlers, and thereby increases flexibility.
- Removal does not change the default behavior, which is to de-duplicate and surface warnings.
Note: Because the PR changes the go module public API, the "pull-controller-runtime-apidiff" test fails, as expected.

:warning: Remove options.WarningHandler

---

.github/workflows/pr-gh-workflow-approve.yaml

This automatically approves GitHub actions once ok-to-test is set. This avoids that maintainers have to click the approve button for GitHub actions on PRs of new contributors

🌱 Add action to approve actions if ok-to-test is set

---

pkg/client/fieldvalidation_test.go
pkg/client/options.go

Context: https://kubernetes.slack.com/archives/C02MRBMN00Z/p1722597459373689?thread_ts=1722596951.583619&cid=C02MRBMN00Z

🐛 Fix WithFieldValidation client

---

.github/workflows/golangci-lint.yml
.github/workflows/pr-dependabot.yaml
.github/workflows/release.yaml
.gitignore
Makefile

This PR adds a GitHub action which will build & upload binaries whenever a tag/release is created
(this requires no changes to our release workflow, simply creating a GitHub release still works)
An example can be seen here: https://github.com/sbueringer/controller-runtime/releases/tag/v0.19.0-beta.0

✨ Publish setup-envtest binaries on releases

---

pkg/config/controller.go
pkg/controller/controller.go
pkg/controller/controller_test.go

Follow-up to: https://github.com/kubernetes-sigs/controller-runtime/pull/2902#issuecomment-2284194683

🌱 Add SkipNameValidation option

---

pkg/client/fake/doc.go

This PR addresses a discrepancy in method naming when constructing a fake client.
The documentation at https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/client/fake#pkg-overview currently references a `WithObj` method. However, it appears this may be a typo, and the correct method name should be `WithObjects` since there is no WithObj method
This PR fixes this.

📖  Update incorrect method name on doc.go

---

pkg/builder/webhook_test.go

Follow-up to https://github.com/kubernetes-sigs/controller-runtime/pull/2877#discussion_r1742504288

🌱 Cleanup defaulter & validator unit tests

---

.github/workflows/verify.yml
hack/verify-pr-title.sh

The kubebuilder-release-tools image will become unavailable soon, so moving to a shell script (has been used/tested before in Cluster API)

🌱 Verify PR titles with shell script

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

This updates the fake client to retain the PartialObjectMeta TypeMeta when getting resources.
Fixes: #2923

🐛  Fakeclient: preserve TypeMeta for PartialObjectMeta resources

---

pkg/controller/controllerutil/controllerutil.go
pkg/controller/controllerutil/controllerutil_test.go

I added HasOwnerReference API. This API check if owners contains specific owner.

✨ Add HasOwnerReference

---

pkg/client/apiutil/apimachinery_test.go
pkg/client/apiutil/restmapper.go
pkg/client/apiutil/restmapper_test.go
pkg/client/apiutil/restmapper_wb_test.go

This change makes the `RESTMapper` use [AggredatedDiscovery][0] if available. `AggregatedDiscovery` is beta and thus enabled by default since Kube 1.27.
What this means in particular is that during startup, we will always do a request to `/api` and `/apis`. If `AggregatedDiscovery` is enabled, that is all we have to do. If not, we have to do a third request.
The behavior for reloading remains the same: Do one request unless the request didn't include a version. In that case we have to find the group. If the group is unknown, we will keep on doing a request to `/api` and one to `/apis` to find it. If it is found we are again done in the `AggregatedDiscovery` case and have to do a third request otherwise.
All in all this means that with `AggregatedDiscovery` enabled, the only case where …

:sparkles: Use aggregated discovery if available

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

Adds the [TokenRequest API ](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/)

✨ fakeclient: Add support for ServiceAccount Token subresource

---

pkg/cluster/cluster.go

🌱 Remove deprecated cluster.Options.SyncPeriod

---

.github/workflows/golangci-lint.yml
.golangci.yml
pkg/cache/cache_test.go
pkg/client/client_test.go
pkg/envtest/crd.go
pkg/envtest/envtest_test.go
pkg/envtest/webhook.go
pkg/log/zap/flags.go
pkg/webhook/admission/response.go
tools/setup-envtest/store/store.go

Upgade the golangci-lint version to v1.61.0.

:bug: upgrade golangci-lint to v1.61.0

---

tools/setup-envtest/README.md

This [PR](https://github.com/kubernetes-sigs/controller-runtime/pull/2971) introduced an issue where setupenvtest is now pointing at a go.mod for setupenvtest@latest to require go1.23.  This PR updates the docs to reflect that.

📖Update docs for setupenvtest 

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

The fake client currently has a number of time of check time of use races, where it fetches an object to determine what to do in a mutating operation. The problem is that the object might change in between fetching it and doing the mutating operation. Most notably, this happens when:
* Patching is done in parallel. Only one of the patches will succeed, the other ones will fail with a conflict
* Updates of objects that allow unconditional updates: All updates will succeed, but not all of them will increment the resource version (i.E dirty writes for the RV)
* An update for an object that allows createOnUpdate races with a create or delete
* A DeleteAllOf call races with Delete calls
* A scale update races with a normal update
This change:
* Adds tests for all of these cases
* Fixes them by …

:bug: Fakeclient: Fix TOCTOU races

---

examples/multiclustersync/main.go

This addresses issue [2988](https://github.com/kubernetes-sigs/controller-runtime/issues/2988).

🐛 Rename SecretSyncReconcier to SecretSyncReconciler (typo)

---

pkg/predicate/predicate.go

comments of GenerationChangedPredicate is confusing, we know that `generation` is not updated if its status is defined as subresource.

:book: clarify comments of GenerationChangedPredicate

---

pkg/builder/webhook.go
pkg/builder/webhook_test.go

This PR adds a way to configure mutating and validating webhooks using a custom path (for the HTTP call). It answer a problem described in [this](https://github.com/kubernetes-sigs/controller-runtime/issues/868) issue.
By default, the `WebhookBuilder` will generates the path using the `generateMutatePath(gvk)`/`generateValidatePath(gvk)` function. But if the user wants to use a custom path, it can build the `WebhookBuilder` using the `WithCustomPath(customPath)` function.
Example:
```go
WebhookManagedBy(mgr).
For(&TestDefaulter{}).
WithDefaulter(&TestCustomDefaulter{}).
WithCustomPath(customPath).
Complete()
```

✨ Add custom path option for webhooks

---

pkg/builder/webhook.go
pkg/webhook/admission/defaulter_custom.go
pkg/webhook/admission/defaulter_custom_test.go

When creating a patch for the custom defaulter, don't return the removals generated by object decoding with the local scheme.
Otherwise, the patch will include a remove instruction for fields that the go type doesn't contain.
This could happen when building a webhook for a resource that belongs to another project (including k8s types).
This PR stops the defaulter from pruning the fields that are not recognized in the local scheme.
When doing this we are creating two patches one before and one after the custom defaulter call and only send back the remove operations that are not present in both patches.
The user can opt-out from this new behavior by specifying the  `DefaulterRemoveUnknownFields`  option when calling ` WithCustomDefaulter`. 
(This is a rework of #2931)

🐛 Fix custom defaulter: avoid deleting unknown fields (zero change patch)

---

examples/scratch-env/go.mod
examples/scratch-env/go.sum
go.mod
pkg/internal/controller/controller.go
pkg/internal/controller/controller_test.go
pkg/internal/source/kind.go

Contrary to everything else in controller-runtime, we expect `source.Start` to be non-blocking. If someone implements a custom source and gets this wrong, the resulting behavior is that the binary starts successfully, but no reconciliation happens which is extremely difficult to understand and debug.
This change makes us use the `CacheSyncTimeout` not only for the sources `WaitForSync` but also for its `Start`.
It is worth noting that the current design of both requiring `Start` to not block and `WaitForSync` to block is very confusing. It likely came to be because we basicaly require two distinct contexsts in `Start`, one to indicate the lifetime of the `Source` and one to indicate the `Start` timeout.
To overall simplify and improve the code, the change also parallelizes the `Start` of …

:bug: Error when source.Start() never returns

---

pkg/internal/controller/controller.go

Addresses
https://github.com/kubernetes-sigs/controller-runtime/pull/2997#discussion_r1834925687, followup to https://github.com/kubernetes-sigs/controller-runtime/pull/2997

🌱  Source.Start(): Use errgroup without context

---

pkg/internal/controller/controller.go
pkg/internal/controller/controller_test.go

Addresses the comments on https://github.com/kubernetes-sigs/controller-runtime/pull/2997
/hold

:seedling: Fixups to error when source.Start never returns

---

pkg/cache/cache.go
pkg/cache/defaulting_test.go
pkg/cache/internal/informers.go

AllowWatchBookmarks is generally pretty safe to enable as it has been available in Kuberentes for a long while, and the server ignores the flag if it doesn't implement it (per docs).

✨ Add EnableWatchBookmarks option to cache informers

---

pkg/internal/controller/controller.go
pkg/internal/controller/controller_test.go

A controller may watch several sources. This change makes it easier to debug which source fails to be synced.

🌱 (:seedling:, other) Log the syncing source when WaitForSync fails

---

examples/scratch-env/go.mod
examples/scratch-env/go.sum
go.mod
pkg/certwatcher/certwatcher.go
pkg/certwatcher/certwatcher_suite_test.go
pkg/certwatcher/certwatcher_test.go
pkg/certwatcher/example_test.go
pkg/certwatcher/metrics/metrics.go

In the current controller-runtime/certwatcher behaviour if any of the files (cert or key) are deleted before the replacement, the code removes the watcher. It gets stuck with watching nothing, so when the replacement arrives - no goroutine will receive that event and all the future certificate updates (including this) are missed until the code is restarted.
The added test in the PR shows the example scenario of updating the certificate in two steps:
1. `rm /certs/mtls.pem /certs/mtls.key`
2. `tar xvf -C /certs new_mtls.tar.gz` (or similar).
**Expected behaviour:**
Return the previous certificate until the new files appear, reestablish the watch and reread the certs when ready.
**Current behaviour:**
The watch is removed and new files do not trigger anything.
1. The …

🐛 Refactor certificate watcher to use polling, instead of fsnotify

---

pkg/leaderelection/leader_election.go
pkg/manager/manager.go
pkg/manager/manager_test.go

This change makes the leader elector use a client that internally has a smaller timeout than the renew deadline, which avoids a situation where a single request timing out makes us lose the leader lease.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/3027

:warning: Use leader elector with client timeout

---

pkg/leaderelection/leader_election.go

This change is a follow-up to the one that introduces the usage of the leader-elector with client timeout. That change was breaking because it introduces a new option and always assumed it was set. This change makes us only use that option if its actually set.
Ref https://github.com/kubernetes-sigs/controller-runtime/pull/3028

:seedling: Make using leader elector with client timeout non-breaking

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

The cache allows to add indexes at runtime, however doing so isn't really testable with the fakeclient, as it didn't have that capability. Add it.

:sparkles: Fake client: Allow adding indexes at runtime

---

pkg/certwatcher/certwatcher.go

🌱 add deprecated Watch() to certwatcher

---

pkg/cluster/cluster.go

Make it easier to understand that GetAPIReader returns a Reader which does not use the cache.

:book: More explicit docs for Cluster.GetAPIReader

---

pkg/client/interfaces.go

Nit: Correct a typo in the docstring

✨ Nit: Correct a typo in the docstring

---

pkg/webhook/admission/defaulter_custom.go
pkg/webhook/admission/defaulter_custom_test.go

This PR fixes an issue that occurs when comparing non-hashable values.
For more details, see https://github.com/kubernetes-sigs/controller-runtime/pull/2982#issuecomment-2568136431.

🐛 Fix custom defaulter: compare only remove patches

---

examples/scratch-env/go.mod
examples/scratch-env/go.sum
go.mod
pkg/certwatcher/certwatcher.go
pkg/certwatcher/certwatcher_test.go

This PR adds fsnotify back to the cert-watcher.
This helps in cases where fsnotify works and that depend on an instant certificate reload.
For example if the webhook certificate is directly used as caBundle in MutatingWebhookConfigurations / ValidatingWebhookConfigurations / CRDs.
Please note: It is highly recommended to use a CA (that is used as caBundle in MutatingWebhookConfigurations / ValidatingWebhookConfigurations / CRDs) and a separate serving certificate using that CA. So during serving cert rotation both the old and new certificate are valid. In that case fsnotify is not required and a cert reload within 10 seconds is good enough.

🌱 Add fsnotify watcher+polling

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

Currently, if a List call to the fake client references an invalid fieldSelector, we will return an error and put all items into the passed List. Avoid putting anything into the passed list if the selector is invalid.

:bug: Fakeclient: Don't return items on invalid selector

---

examples/priorityqueue/main.go
pkg/config/controller.go
pkg/controller/controller.go
pkg/controller/controller_test.go
pkg/controller/priorityqueue/metrics.go
pkg/controller/priorityqueue/priorityqueue.go
pkg/controller/priorityqueue/priorityqueue_test.go
pkg/handler/eventhandler.go
pkg/handler/eventhandler_test.go

This change:
* addresses Stefans review comments from the [original PR](https://github.com/kubernetes-sigs/controller-runtime/pull/3014)
* fixes a bug in the metrics where we always included items that are not ready yet - This is incorrect, metrics are only implemented on the [basequeue][0] in upstream, meaning they are only emitted for items that are ready. The impact of this was for example an incorrect queue_depth metric.
* fixes an issue where we might panic due to to manipulating the btree while iterating it
[0]: https://github.com/kubernetes/kubernetes/blob/b1cb471982b74c13c26dbcc0f4e1b5ae92ea47e6/staging/src/k8s.io/client-go/util/workqueue/queue.go#L157

:bug: Bugfixes for priority queue

---

.golangci.yml
pkg/cache/internal/informers.go
pkg/client/config/config_test.go
pkg/controller/controllerutil/controllerutil_test.go
pkg/controller/priorityqueue/priorityqueue_test.go
pkg/envtest/webhook.go
pkg/internal/testing/controlplane/apiserver.go
pkg/internal/testing/controlplane/auth.go
pkg/internal/testing/process/process.go
pkg/log/zap/flags.go
pkg/manager/internal/integration/manager_test.go
pkg/manager/manager_test.go
pkg/metrics/filters/filters_test.go
pkg/metrics/server/server.go
pkg/webhook/admission/response.go
pkg/webhook/example_test.go
pkg/webhook/server.go
tools/setup-envtest/remote/read_body.go
tools/setup-envtest/store/store.go

It yields a lot of false positives as seen by the number of nolint directives this change removes.

🌱 Remove gosec linter

---

designs/cache_options.md

📖 Updates the cache options design and examples to reflect the implementation.
for example DefaultNamespaces is of type DefaultNamespaces map[string]Config, and thus expects an empty struct in the examples instead of nil.

📖 update cache options design to reflect the implementation

---

pkg/controller/priorityqueue/metrics.go
pkg/controller/priorityqueue/priorityqueue.go
pkg/controller/priorityqueue/priorityqueue_test.go

The priorityqueue needs to call `metrics.add` but only once an item was ready. When an item was initially added with `After`, so not ready, then without which makes it ready, we didn't do that, resulting in potentially negative values for the queue depth metric.

:bug: Fix a bug in the priorityqueue metrics

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

Follow-up to #3022
After 3022 the fake client List call was dropping TypeMeta (apiVersion + kind)

🐛 fake client: preserve TypeMeta during List call with UnstructuredList

---

pkg/internal/controller/controller.go
pkg/source/source.go

When using a custom source, the error when starting will fail because the `fmt.Stringer` interface is not implemented by the source.  The builtin sources have already implanted this interface allow the below line to not fail:
```go
log := c.LogConstructor(nil).WithValues("source", watch.String())
```
```
fatal error: concurrent map iteration and map write
```
Resolves https://github.com/kubernetes-sigs/controller-runtime/issues/3057

🐛 Check to see if custom source implements fmt.Stringer when logging

---

.github/workflows/golangci-lint.yml
.golangci.yml
pkg/client/fake/client.go

Gets us to the latest release of it

🌱Bump golangci-lint to v1.63.4

---

pkg/cache/cache.go
pkg/cache/defaulting_test.go

This PR adds clones to the cache packages `defaultOpts` function.
This is necessary to prevent data races when creating caches in parallel using the same options.
Note: we found this in CAPI and workaround using: https://github.com/kubernetes-sigs/cluster-api/pull/11707
Data races before:
```
==================
WARNING: DATA RACE
Write at 0x00c00046c900 by goroutine 29:
runtime.mapaccess2()
/Users/schlotterc/.bin/go-archive/go1.23.2.darwin-arm64/src/runtime/map.go:479 +0x28c
sigs.k8s.io/controller-runtime/pkg/cache.defaultOpts()
/Users/schlotterc/go/src/sigs.k8s.io/controller-runtime/pkg/cache/cache.go:523 +0x650
sigs.k8s.io/controller-runtime/pkg/cache.TestDefaultOptsRace.func1()
/Users/schlotterc/go/src/sigs.k8s.io/controller-runtime/pkg/cache/cache_race_test.go:35 +0xe8
Previous read …
```

🐛 cache: clone maps to prevent data race when concurrently creating caches using the same options

---

examples/priorityqueue/main.go
pkg/controller/controller.go
pkg/controller/priorityqueue/priorityqueue.go

This debug logging prints the state of the workqueue in order to allow debugging it. It will continously check at runtime if debug logging is enabled and do nothing if not, making it very cheap if unused.
Sample output piped through `jq` for readability:
```
{
"level": "debug",
"ts": "2025-01-19T12:00:43-05:00",
"msg": "workqueue_state",
"controller": "configmap",
"items": [
{
"key": {
"Namespace": "kube-system",
"Name": "kubeadm-config"
},
"addedCounter": 1,
"priority": -100
}
]
}
```

🌱 Add debug logging for the state of the priority queue

---

pkg/internal/controller/controller.go
pkg/internal/controller/controller_test.go

The code that calls `WaitForSync(ctx)` checks for the original `SyncingSource`. This does not work for custom typed controllers where `TypedSyncingSource` is passed with a type parameter other than `reconcile.Request` .
this fix should be backported to v0.20 and v0.19

🐛fix(controller): support WaitForSync in custom TypedSyncingSource

---

pkg/internal/controller/controller.go
pkg/internal/controller/controller_suite_test.go
pkg/internal/controller/controller_test.go

this is a cherry pick of https://github.com/kubernetes-sigs/controller-runtime/pull/3084

[release-0.19] 🐛fix(controller): support WaitForSync in custom TypedSyncingSource

---

pkg/controller/priorityqueue/metrics.go
pkg/controller/priorityqueue/priorityqueue.go
pkg/controller/priorityqueue/priorityqueue_test.go

Inside the priorityqueues `spin` we call the metrics `add` if an item becomes ready so that the `queue_depth` metric gets incremented. To avoid doing this multiple times for the same item, we track the key in a map and remove it there when we hand the item out.
If an item gets added without `RequeueAfter` that is already on the queue but with a `RequeueAfter` we also call the metrics `add` - But if we already did that in `spin` we will count the item twice.

:bug: Priorityqueue: Yet another queue_depth metric fix

---

pkg/internal/controller/metrics/metrics.go
pkg/metrics/registry.go

Default add GoCollector and ProcessCollector metrics for controller-runtime metrics package

✨feat: add GoCollector and ProcessCollector metrics

---

pkg/controller/priorityqueue/priorityqueue.go
pkg/controller/priorityqueue/priorityqueue_test.go

https://github.com/kubernetes-sigs/controller-runtime/blob/2e8ba92873fd2a92ba473926f02e493619480771/pkg/controller/priorityqueue/priorityqueue.go#L130-L146
Since `priorityqueue.AddWithOpts()` allows adding multiple items, if `o.RateLimited` is true, the `o.After` value could get overwritten in the loop and affect subsequent items.

🐛Fix behavior of rate limit option in priorityqueue.AddWithOpts

---

pkg/cache/cache_test.go
pkg/cache/multi_namespace_cache.go

When the cache options are configured with DefaultNamespaces which include an entry with `cache.AllNamespaces`, listing from the cache should fallback to the global cache if there are no namespace-specific caches that match the namespace from the list options.

🐛 fix: cache should list out of global cache when present and necessary

---

hack/apidiff.sh
hack/check-everything.sh

🌱 fix: make test fails with make: *** [Makefile:73: test] Error 1

---

pkg/envtest/crd.go
pkg/envtest/crd_test.go

I would like to export ReadCRDFiles so I can use the functionality without being forced to use the entire InstallCRDs func.
CreateCRDs and WaitForCRDs are already exported

🌱 Export envtest.ReadCRDFiles

---

alias.go
pkg/client/config/config.go
pkg/client/config/config_test.go

Sig-Apimachinery recommends [disabling the client-side ratelimiter][0] and rely on API priority and fairness instead for any [Kubernetes version >= 1.22][1]. Update our config getters to do that.
[0]: https://kubernetes.slack.com/archives/C0EG7JC6T/p1680889646346859?thread_ts=1680791299.631439&cid=C0EG7JC6T
[1]: https://kubernetes.slack.com/archives/C0EG7JC6T/p1680892224956789?thread_ts=1680791299.631439&cid=C0EG7JC6T

:warning: Config: Disable client-side ratelimiter by default

---

pkg/cache/cache_test.go
pkg/cache/internal/cache_reader.go
pkg/cache/multi_namespace_cache.go

Implements option 2 mentioned in https://github.com/kubernetes-sigs/controller-runtime/pull/3045
This should make it a lot easier to detect usages of pagination with the cached client (which is not supported)

🐛 Return error if pagination is used with the cached client

---

examples/scratch-env/go.mod
examples/scratch-env/go.sum
go.mod
hack/check-everything.sh
pkg/client/apiutil/restmapper_test.go
pkg/envtest/binaries.go
pkg/envtest/binaries_test.go
pkg/envtest/server.go

✨ envtest: add option to download binaries, bump envtest to v1.32.0

---

pkg/envtest/binaries.go

Fixes https://github.com/kubernetes-sigs/controller-runtime/pull/2810#issuecomment-2694913008

🐛 Create BinaryAssetsDirectory if it doesn't exist

---

pkg/config/controller.go
pkg/controller/controller.go
pkg/controller/example_test.go
pkg/manager/manager.go
pkg/manager/manager_test.go

Currently, `NewUnmanaged` and `NewTypedUnmanaged` require a manager but the only properties they ever access from it are `GetControllerOptions` and `GetLogger`. It makes no sense to require a `Manager` for something that is unmanaged, so remove that.
Doing so naively means that we require two options parameters for these constructors, one that has the actual options and another one to default from which again is confusing. Remove the options struct to default from and instead implement a `DefaultFromConfig` that defaults the controller options `config.Controller` which also clarifies what belongs where. This defaulting gets automatically called in the managed constructors and is exported so anyone can use it.
This change is breaking only for users of `New[Typed]Unmanaged` in that:
* The …

⚠️  NewTypedUnmanaged: Stop requiring a manager

---

pkg/client/fake/client.go

update the json-patch dependency from v4 to v5 in the fake client implementation. This change aligns the dependency with its latest version in the `github.com/evanphx/json-patch` package.
also, fix a minor formatting issue in a TODO comment for consistency.

📖 chore: Add explanatory comment for continuing to use json-patch v4 in the fake client

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

We have a scheme write lock but plenty of other codeptaths that read from the scheme and that don't do looking, resulting in dataraces if the two happen in parallel.
This change introduces a simple RW lock and makes the fakeclient acquire read locking for all its operations except when needing the write lock. This isn't particularly smart, but given that we only have one codepath that writes to the scheme, it seems good enough.
Fixes #3139 
/cherrypick release-0.20
/cherrypick release-0.19

:bug: Fakeclient: Fix dataraces when writing to the scheme

---

pkg/internal/controller/metrics/metrics.go

This reverts commit fc485839d5c10112642325e7e6df25084553c0e4.
This change breaks some users.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/3144

[release-0.20] :bug: Revert "✨ Expose all Go runtime metrics"

---

pkg/client/client_test.go

If someone is interacting with objects through unstructured, we generally do not expect that to require any sort of registration in the scheme. It look like we never had any tests for this, this change adds them.

:seedling: Validate that unstructued objects don't require scheme registration

---

pkg/manager/manager_test.go

Saw tests failing a few times with race condition: https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/kubernetes-sigs_controller-runtime/3138/pull-controller-runtime-test/1898308642759774208

🐛 Fix race in logger test

---

pkg/cache/cache.go
pkg/cache/internal/informers.go
pkg/cache/multi_namespace_cache.go
pkg/controller/controllertest/util.go
pkg/internal/controller/controller.go
pkg/internal/source/kind.go
pkg/log/log_test.go
pkg/source/source.go

Follow-up to https://github.com/kubernetes-sigs/controller-runtime/pull/3104#discussion_r1946317566
Fixes #2987

⚠ Improve logging by adopting contextual logging

---

pkg/handler/enqueue.go
pkg/handler/enqueue_mapped.go
pkg/handler/enqueue_owner.go
pkg/handler/eventhandler.go
pkg/handler/eventhandler_test.go

Resolves https://github.com/kubernetes-sigs/controller-runtime/issues/3105
Handlers: 
This brings the handler `TypedEnqueueRequestForObject` , `enqueueRequestForOwner` and `enqueuRequestFromMapFunc` handlers to use priority queue if the `workqueue.TypedRateLimitingInterface[reconcile.Request]` is of type  `priorityqueue.PriorityQueue[reconcile.Request]` without having to use the wrapper `WithLowPriorityWhenUnchanged`.
**NOTE: Added tests implement the same logic to show that this maps to the functionality of the wrapped handler in the tests**
/assign @alvaroaleman @sbueringer

🐛Implement priorityqueue as default on handlers if using priorityqueue interface

---

pkg/handler/enqueue_mapped.go
pkg/handler/eventhandler.go
pkg/handler/eventhandler_test.go

This change makes the `TypedFuncs` and `enqueueRequestsFromMapFunc` set a low priority when the object is unchanged by default, as well as extend the test coverage to validate this behavior for `EnqueueRequestForOwner`.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/3105

:seedling: Handlers: Use low priority when object is unchanged and priority queue

---

pkg/internal/testing/controlplane/apiserver.go

old code:
```go
func (s *APIServer) Stop() error {
if s.processState != nil {
if s.processState.DirNeedsCleaning {
s.CertDir = "" // reset the directory if it was randomly allocated, so that we can safely restart
}
if err := s.processState.Stop(); err != nil {
return err
}
}
return s.Authn.Stop()
}
```
If setup failed, and then Stop() gets called, `s.Authn` could be nil.
This PR checks if s.Auth is nil.

:seedling: envtest: fix nil pointer exception in Stop().

---

pkg/client/apiutil/restmapper.go
pkg/client/apiutil/restmapper_test.go

When requesting a resource without version through methods such as `RESTMapping`, the mapper would previously return a random version rather than the preferred one, this change fixes that.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/3133
/cherrypick release-0.20

:bug: Restmapper: Respect preferred version

---

pkg/controller/controllerutil/controllerutil.go

I checked the `CreateOrPatch` function and it checked if `MutateFn` is nil, but `CreateOrUpdate` did not check.
Or is it possible to modify the `mutate` function directly and execute `MutateFn` only when `MutateFn` is not nil?
https://github.com/kubernetes-sigs/controller-runtime/blob/5dcea7e94b7158e410d22f4a1eed16780497fe66/pkg/controller/controllerutil/controllerutil.go#L425

:bug: fix(controllerutil): avoid panic when the MutateFn is nil

---

pkg/controller/priorityqueue/metrics.go
pkg/controller/priorityqueue/metrics_test.go
pkg/controller/priorityqueue/priorityqueue.go
pkg/controller/priorityqueue/priorityqueue_test.go
pkg/internal/metrics/workqueue.go

Part of https://github.com/kubernetes-sigs/controller-runtime/issues/2374

🌱 Add priority label to PQ depth metric

---

pkg/cache/multi_namespace_cache.go
pkg/controller/controllertest/util.go
pkg/event/event.go
pkg/handler/enqueue_mapped.go
pkg/handler/eventhandler.go
pkg/handler/eventhandler_test.go
pkg/internal/source/event_handler.go
pkg/internal/source/internal_test.go
pkg/internal/source/kind.go
pkg/source/source.go

Let's start using IsInitialList that is provided in the OnAdd func of ResourceEventHandlers.
This can be leveraged to determine in a clean way if an add/create event came from an initial list.
https://kubernetes.slack.com/archives/C02MRBMN00Z/p1742119089612549?thread_ts=1741482643.357719&cid=C02MRBMN00Z
Reverts the parts of https://github.com/kubernetes-sigs/controller-runtime/pull/2223 that we don't need anymore.

✨ Leverage isInInitialList of ResourceEventHandler.OnAdd, Add IsInInitialList to TypedCreateEvent

---

pkg/builder/webhook.go
pkg/builder/webhook_test.go

Following this PR #2998. I implemented the custom path for webhooks considering that it will be used by either only the `validating` or the `defaulting`. However, the user can actually use the both of them on the same webhook manager.
Until now, when the user was using `.WithDefaulter(&TestCustomDefaulter{})`, `.WithValidator(&TestCustomValidator{})` and `.WithCustomPath(customPath)` at the same time, an endless loop was launched by constantly calling the other webhook. This bug is caused because they are both register at the same path.
This is the reason why I made this PR. I split the `.WithCustomPath()` function into two functions `.WithDefaultingCustomPath()` and `.WithValidatingCustomPath()` in order to be used in this way:
```go
WebhookManagedBy(mgr).
For(&TestDefaulter{}). …
```

:bug: Fix custom path for webhooks conflict

---

pkg/builder/controller.go

The handlers themselves already support this, so there is no need to also do it in the builder.
/hold
xref: #3105

:seedling: Remove redundant WithLowPriorityWhenUnchanged in builder

---

pkg/handler/eventhandler.go

This PR fixes the godoc of TypedEventHandler, before only l.69 showed up
Follow-up to https://github.com/kubernetes-sigs/controller-runtime/pull/3111#discussion_r1992735055

🌱 Fix godoc of TypedEventHandler

---

pkg/controller/name.go

/hold
It seems worthwhile to mention that this validation can be disabled and how.

🌱 Mention the SkipNameValidation option in the name validation error

---

pkg/internal/controller/metrics/metrics.go
pkg/internal/metrics/workqueue.go
pkg/webhook/internal/metrics/metrics.go

Adopts Native Histograms in an opt-in and backward-compatible manner to overcome the limitations of traditional histograms.
This solves https://github.com/kubernetes-sigs/controller-runtime/issues/3164

✨ Adopt native histograms

---

pkg/envtest/envtest_test.go
pkg/envtest/server.go

Pulling function from internal https://github.com/kubernetes-sigs/controller-runtime/blob/b826f390522092f54fbea9ff18a97ddde4a828b5/pkg/internal/testing/controlplane/kubectl.go#L42-L81
This is useful for creating kubeconfig file in order to pass filename to KUBECONFIG env which can be helpful in writing [unit tests](https://github.com/vmware-tanzu/velero/blob/a51cc56b43b34ac379a2a5d9908b0e0427c25a34/pkg/cmd/cli/install/install_test.go#L84-L97) without having to break apart some of the current client code to accept a rest.Config
Signed-off-by: Tiger Kaovilai <tkaovila@redhat.com>
Used in
- https://github.com/vmware-tanzu/velero/pull/6152
- https://github.com/vmware-tanzu/velero/pull/6155

✨ envtest: Add Environment.KubeConfig field

---

pkg/handler/enqueue_owner.go
pkg/handler/eventhandler_test.go

We already did this for RequestForOwner, but not the typed variation, this change adds that.
/hold
Ref https://github.com/kubernetes-sigs/controller-runtime/issues/3105

:seedling: TypedEnqueueRequestForOwner: Decrease priority when unchanged

---

.github/workflows/release.yaml
Makefile
tools/setup-envtest/main.go
tools/setup-envtest/version/version.go
tools/setup-envtest/version/version_suite_test.go
tools/setup-envtest/version/version_test.go
tools/setup-envtest/workflows/workflows.go
tools/setup-envtest/workflows/workflows_test.go

With the setup-envtest binary, it is difficult to determine the version of the binary that is installed.  This will allow the user to use the command `setup-envtest version` to see what version of the binary is installed.
~~**Note: This is targeting the branch when built and not a specific tag.  The setup-envtest instructions for installation shows to target the release branch for specific versions**~~
**This will target the release tag defined in the GitHub action when binaries are built.**
Resolves https://github.com/kubernetes-sigs/controller-runtime/issues/3158

✨Add RELEASE_TAG to tools/setup-envtest to show binary version with setup-envtest version

---

pkg/client/client.go
pkg/client/example_test.go
pkg/log/warning_handler.go

/hold
/assign @alvaroaleman @vincepri 
Tested it with Cluster API, warning logs look now like this
> {"ts":1742724964192.3147,"caller":"log/warning_handler.go:64","msg":"metadata.finalizers: \"cluster.cluster.x-k8s.io\": prefer a domain-qualified finalizer name including a path (/) to avoid accidental conflicts with other finalizer writers","controller":"cluster","controllerGroup":"cluster.x-k8s.io","controllerKind":"Cluster","Cluster":{"name":"in-memory-7608","namespace":"default"},"namespace":"default","name":"in-memory-7608","reconcileID":"198f6d32-150f-46c1-a276-75b838ce8320","v":0}

🌱 Adopt WarningHandlerWithContext

---

tools/setup-envtest/README.md

It seems that with https://github.com/kubernetes-sigs/controller-runtime/commit/9d65299bd59d88a93735a99f04cd70e9fae3de20 Go 1.24+ is required for latest envtest.
This PR would help to quickly fix pipeline errors like: https://github.com/SAP/cf-service-operator/actions/runs/14042277233/job/39315277162
```
test -s /workspace/bin/setup-envtest || GOBIN=/workspace/bin go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
go: downloading sigs.k8s.io/controller-runtime v0.20.4
go: downloading sigs.k8s.io/controller-runtime/tools/setup-envtest v0.0.0-20250324134234-561fa39c550f
go: sigs.k8s.io/controller-runtime/tools/setup-envtest@latest: sigs.k8s.io/controller-runtime/tools/setup-envtest@v0.0.0-20250324134234-561fa39c550f requires go >= 1.24.0 (running go 1.23.0; …
```

📖Golang 1.24+ in setup-envtest/README.md

---

README.md

This used to be true in the very beginning of the projects but isn't anymore today, there are different people working on these projects.

:seedling: Clarify that controller-runtime is not a kubebuilder subproject

---

pkg/internal/controller/controller.go
pkg/internal/controller/controller_test.go

This PR is a small refactor of the controller code.
It's the first step to implementing https://github.com/kubernetes-sigs/controller-runtime/pull/3121 as the watches need to be started in two places, so pulling this into its own method.
1) An warmup method if the controller is a warm replica
2) When the controller wins leader election (current behavior)

✨ [Warm Replicas] Extract startWatches into helper method.

---

pkg/log/zap/flags.go
pkg/log/zap/zap.go
pkg/log/zap/zap_test.go

This allows logging to be disabled for all but panic log entries.
The Zap Level config parameter (https://github.com/uber-go/zap/blob/6d482535bdd97f4d97b2f9573ac308f1cf9b574e/config.go#L62) isn't available via the Option interface, so it's not possible to disable it completely via a user-added flag.

:sparkles: Allow panic as log level

---

pkg/cache/cache_test.go
pkg/cache/multi_namespace_cache.go

This PR fixes an issue in the multi-namespace cache implementation where repeated calls to the `List()` method on the same list object would accumulate results instead of resetting the list each time. This happens because the current implementation extracts existing items from the provided list object, then appends new items to it, causing the list to grow with each call.
The fix initializes a fresh empty slice for collected items instead of extracting from the existing list object.
fix #3194

⚠ fix: Stop accumulating lists in multi-namespace cache implementation

---

pkg/controller/controllerutil/controllerutil.go

This updates the documentation for the `CreateOrUpdate` and `CreateOrPatch` methods to include a section on the pitfalls of using these methods.
Closes #3191

📖 Document pitfalls of CreateOrUpdate and CreateOrPatch

---

.github/workflows/golangci-lint.yml
.golangci.yml
Makefile
examples/builtins/controller.go
examples/crd/main.go
examples/crd/pkg/groupversion_info.go
pkg/cache/cache_test.go
pkg/cache/internal/informers.go
pkg/client/config/config_test.go
pkg/client/fake/client.go
pkg/envtest/webhook.go

This updates golangci-lint to v2.0.2 with the associated configuration in workflows and Makefile

🌱ci: Update golangci-lint to v2.1.6 and adjust configuration

---

README.md

This should've been done during the uplift of the k8s-version from v0.33-beta.1 -> v0.33.  
Helps with https://github.com/kubernetes-sigs/controller-runtime/issues/3123

📖 Update README with compatability matrix

---

pkg/client/fake/client_test.go

This change removes supports for objects that have type or object meta defined as pointer.
This is because the `FieldManagedObjectTracker` needed for support of SSA in the fakeclient can not support it, as it has a lot of places where it unconditionally accesses these fields using reflect, which will cause panics.

:warning: Fakeclient: Remove support for objects with pointer meta

---

pkg/leaderelection/leader_election.go
pkg/manager/manager.go
pkg/manager/manager_test.go

This PR makes two changes:
* Refactors leader_election.go to not use NewWithKubeConfig() and instead perform the timeout calculation itself
* Adds a new option to managers to allow users to set custom labels that will be set on the lease when it changes owner (solves #3216)

✨ feat: add support for custom labels on leader election leases ✨

---

go.mod
pkg/client/fake/client.go
pkg/client/fake/client_test.go
pkg/client/fake/typeconverter.go
pkg/client/fake/typeconverter_test.go

This change adds apply support into the fake client.
This relies on the upstream support for this which is implemented in a new [FieldManagedObjectTracker][0]. In order to support many types, a custom `multiTypeConverter` is added.
The `FieldManagedObjectTracker` results in `ManagedFields` being set after any operations. As that would be a very breaking change, the fake client will by default unset them and allows to optionally leave them.
Based on all existing tests still passing, I believe this change is fully backwards-compatible (But depends on breaking changes such as a very new client-go and apimachinery and https://github.com/kubernetes-sigs/controller-runtime/pull/3228).
Fixes #2341 
[0]: https://github.com/kubernetes/kubernetes/blob/4dc7a48ac6fb631a84e1974772bf7b8fd0bb9c59/staging …

✨  Fakeclient: Add apply support

---

pkg/controller/priorityqueue/priorityqueue.go

The PQ still stores new items when shutdown and triggers processing when Get is called, avoid all of that.

:bug: Priorityqueue: Shutdown on shutdown

---

OWNERS_ALIASES

Sync after https://github.com/kubernetes/org/pull/5691

📖 Sync admins & maintainers with kubernetes/org

---

pkg/cache/internal/informers.go
pkg/client/apiutil/apimachinery.go
pkg/client/applyconfigurations.go
pkg/client/client.go
pkg/client/client_rest_resources.go
pkg/client/client_test.go
pkg/client/dryrun.go
pkg/client/fake/client.go
pkg/client/fake/client_test.go
pkg/client/fieldowner.go
pkg/client/fieldvalidation.go
pkg/client/fieldvalidation_test.go
pkg/client/interceptor/intercept.go
pkg/client/interceptor/intercept_test.go
pkg/client/interfaces.go
pkg/client/namespaced_client.go
pkg/client/namespaced_client_test.go
pkg/client/options.go
pkg/client/options_test.go
pkg/client/patch.go
pkg/client/typed_client.go
pkg/client/unstructured_client.go

This change adds native server-side apply support to the client by extending it with an `Apply` method that takes a `runtime.ApplyConfiguration`.
Ref https://github.com/kubernetes-sigs/controller-runtime/issues/3183

:warning: Add native SSA support

---

pkg/manager/manager.go
pkg/manager/manager_test.go
pkg/manager/runnable_group.go

Fixes #3218
A race condition during manager shutdown can cause a goroutine leak if the graceful shutdown period is exceeded.
When the `gracefulShutdownTimeout` is reached, the manager stops waiting for runnables and terminates the goroutine responsible for draining errors from runnables. If a slow runnable subsequently fails, its attempt to send an error on the shared channel (errChan) will block its goroutine forever, causing a leak.
This change prevents the leak by replacing the blocking error send in the runnableGroup with a non-blocking select statement. If the context is canceled, indicating a shutdown is in progress, the error is logged and dropped. This allows the runnable's goroutine to terminate cleanly instead of blocking forever.
Example test failure without this fix:
```
$ go …
```

🐛 Fix(manager): Prevent goroutine leak on shutdown timeout

---

README.md
VERSIONING.md

While its technically true that we do semver because semver allow to do anything for as long as a major version zero is used, referring to it doesn't really explain our versioning scheme. Clarify that in the readme and also mention why we won't publish a major version > 0.
Closes https://github.com/kubernetes-sigs/controller-runtime/issues/601

:seedling: Clarify our versioning scheme

---

pkg/certwatcher/certwatcher.go
pkg/certwatcher/certwatcher_test.go

Controller-Runtime starts the certwatcher in the webhook server, which means it always runs regardless of the current replica being leader or not.
It turns out that kubebuilder adds it to the manager and as a result, it only runs on leader replicas. Make it a `LeaderElectionRunnable` and don't require leader election so that it will work correctly even if other projects use it in ways that were not originally anticipated.

:seedling: Certwatcher: Don't require leaderelection

---

pkg/client/options.go
pkg/client/options_test.go

If the selector is not set for `MatchingLabelsSelector` and `MatchingFieldsSelector`, then the list call panics.
This PR updates `MatchingLabelsSelector` and `MatchingFieldsSelector` to default their Selector fields to labels.Nothing() and fields.Nothing() respectively if unset in ApplyToList.

⚠️  Default selectors to Nothing if it is nil for `MatchingLabelsSelector` and `MatchingFieldsSelector`

---

pkg/cache/cache.go

There is a common misunderstanding about SyncPeriod. It does **not** sync between api-server and local cache.
This PR updates the docs to make this more clear.
Related: https://github.com/kubernetes-sigs/controller-runtime/pull/3269#discussion_r2272237638

:book: Docs for SyncPeriod: No sync from api-server.

---

pkg/handler/eventhandler.go
pkg/handler/eventhandler_test.go

This change makes `WithLowPriorityWhenUnchanged` set the priority for
AddAfter, AddRatelimited and AddWithOpts (if not already set) as well.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/3171
Based on top of https://github.com/kubernetes-sigs/controller-runtime/pull/3289 so that needs to merge first
/hold

:sparkles:  WithLowPriorityWhenUnchanged: Set Priority for all add methods 

---

examples/scratch-env/go.mod
examples/scratch-env/go.sum
go.mod
pkg/envtest/binaries.go
pkg/envtest/binaries_test.go

This allows configuring the `DownloadBinaryAssetsVersion` field of `envtest.Environment` with only the Major.Minor portions of a Kubernetes API version. In that case, the framework searches the asset index for the latest stable version in that release series.
This matches the behavior of `setup-envtest use {major}.{minor}` without the full complexity of version selectors. The leading `v` is now optional, too. For example:
- `"v1.29"` resolves to [v1.29.4](https://github.com/kubernetes-sigs/controller-tools/blob/50b4feecf68291368219a53ef3645dc0de9a4819/envtest-releases.yaml#L24)
- `"1.27"` resolves to [v1.27.1](https://github.com/kubernetes-sigs/controller-tools/blob/50b4feecf68291368219a53ef3645dc0de9a4819/envtest-releases.yaml#L134)
- `"1.24"` resolves to …

✨ envtest: search the assets index for latest of a release series

---

pkg/certwatcher/certwatcher.go

After manually updating a certificate, it’s unclear whether the target certificate was updated. This PR adds identification of the source certificate.

🌱 certwatcher: add instance-specific logger with cert/key context

---

pkg/client/config/config.go

Remove the outdated doc comments about the default config of the client-side ratelimiter.

📖 pkg/client/config: remove outdated doc comments

---

pkg/client/fake/client_test.go
pkg/client/patch.go

🌱 Revert deprecation of client.Apply

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go

We already set this for normal create operations, but missed to do it for creations that happen through SSA.
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/3310

:warning: Fakeclient: Set ResourceVersion for SSA Create

---

pkg/client/fake/client.go
pkg/client/fake/client_test.go
pkg/client/fake/versioned_tracker.go

Prior to this, updates through Apply did not call `versionedTracker.updateObject` which does a number of things such as:
* Resetting status if the object has a status resource and its not a status update
* Fail if the RV is incorrect
* Bump the RV
* Delete the object if the request removed the last finalizer
The reason this happend is that `versionedTracker` embedded an `testing.ObjectTracker` and as a result, we inherited the `Apply` of that upstream tracker rather than implementing our own.
This PR contains three commits:
1. Move `versionedTracker` into its own file
2. Make `versionedTracker` a `testing.ObjectTracker` and stop embedding its upstream
3. Call `updateObject` from the versioned trackers `Apply` and update things as needed, as well as adding tests
/hold

:warning: Fakeclient: Fix a number of bugs when updating through apply

---

pkg/controller/controllerutil/controllerutil.go

This modernizes (https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize) the finalizer utils by using modern features of Go and its standard library. No impact for end-users, thus the 🌱.
I was running modernize of one of our projects, leading me to remove our own finalizer utils to use controller-runtime ones instead and found they were not "modernized" themselves.
A larger PR would be to modernize every single file `go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./..` but is out of scope here and possibly contrary to the k8s guidelines

🌱 [noop] Modernize finalizer utils

---

.github/workflows/golangci-lint.yml
.golangci.yml
examples/crd/pkg/groupversion_info.go
examples/tokenreview/tokenreview.go
pkg/log/zap/flags.go
pkg/reconcile/reconcile.go

🌱chore: Update golangci-lint version to v2.5.0

---

pkg/client/client.go
pkg/client/client_test.go
pkg/client/dryrun.go
pkg/client/dryrun_test.go
pkg/client/fake/client.go
pkg/client/fake/client_test.go
pkg/client/fake/versioned_tracker.go
pkg/client/fieldowner.go
pkg/client/fieldowner_test.go
pkg/client/fieldvalidation.go
pkg/client/fieldvalidation_test.go
pkg/client/interceptor/intercept.go
pkg/client/interceptor/intercept_test.go
pkg/client/interfaces.go
pkg/client/namespaced_client.go
pkg/client/namespaced_client_test.go
pkg/client/options.go
pkg/client/options_test.go
pkg/client/patch.go
pkg/client/typed_client.go
pkg/client/unstructured_client.go

This change adds subresource apply support to the client. It is breaking, as that entails extending the interface.
The fake client currently only supports the `status` subresource for apply and will error out if it is used for any other subresource.
Ref https://github.com/kubernetes-sigs/controller-runtime/issues/3183
/hold

⚠️ Add subresource apply support

---

pkg/internal/controller/controller.go
pkg/internal/controller/controller_test.go
pkg/reconcile/reconcile.go

Part of https://github.com/kubernetes-sigs/controller-runtime/issues/2374

✨ Add optional Priority field to reconcile.Result

---

examples/priorityqueue/main.go
pkg/config/controller.go
pkg/controller/controller.go
pkg/controller/controller_test.go

✨ Priorityqueue: Enable per default
