kubernetes-sigs/controller-runtime

- pkg/admission/cert/generator/certgenerator.go
- pkg/admission/cert/writer/doc.go
- pkg/admission/cert/writer/multiple_test.go
- pkg/admission/cert/writer/secret.go
- pkg/admission/cert/writer/secret_test.go
- pkg/admission/controller.go
address the remaining comments from #22
> address the remaining comments from #22

- pkg/cache/cache_test.go
- pkg/cache/informer_cache.go
- pkg/envtest/server.go
* Initial pass for tests of informer cache.
* Test coverage 76.9%
> First pass at informer cache tests

- README.md
> Minor changes to doc links in README

- pkg/admission/controller_test.go
- pkg/builder/build_test.go
- pkg/builder/builder_suite_test.go
- pkg/client/apiutil/apimachinery.go
- pkg/controller/controllerutil/controllerutil_suite_test.go
- pkg/controller/controllerutil/controllerutil_test.go
- pkg/envtest/envtest_test.go
- pkg/runtime/log/deleg.go
- pkg/runtime/log/log.go
- pkg/runtime/log/null.go
- pkg/runtime/scheme/scheme_suite_test.go
- pkg/runtime/scheme/scheme_test.go
- pkg/runtime/signals/signal.go
- pkg/runtime/signals/signal_posix.go
- pkg/runtime/signals/signal_windows.go
Fixes https://github.com/kubernetes-sigs/controller-runtime/issues/120
/assign mengqiy
> Add license headers to go files

- example/main.go
- example/mutatingwebhook.go
- pkg/webhook/admission/builder/builder.go
- pkg/webhook/admission/doc.go
Address comments came from https://github.com/mengqiy/webhook-scaffolding/pull/1
> change how to set webhook type and how we default path in builder

- example/main.go
- example/mutatingwebhook.go
- example/validatingwebhook.go
- pkg/webhook/admission/builder/builder.go
- pkg/webhook/admission/http.go
- pkg/webhook/admission/http_test.go
- pkg/webhook/admission/response.go
- pkg/webhook/admission/webhook.go
- pkg/webhook/admission/webhook_test.go
- pkg/webhook/bootstrap.go
- pkg/webhook/doc.go
- pkg/webhook/server.go
- drop KVMap from Server
- cleanup godoc
- tweak some defaulting regarding webhook name and path
> drop KVMap

- pkg/webhook/admission/builder/builder.go
> set path in builder

- pkg/webhook/bootstrap.go
Sort webhooks to get deterministic results.
> sort webhooks

- pkg/internal/controller/controller_test.go
Fixes #199 
I've had a look at the tests for the metrics and refactored them a bit, using `Reset()` instead of manually assigning the metrics seems to be a better approach and then making sure the values are reset before starting the rest of the test
I've also changed the check for the histogram test, it seemingly was reconciling twice during the test so sample count was 2 every so often. I've made it so we check that at least 1 sample is counted to fix the flake, not sure there's a better way to fix it than that
I ran the tests with `ginkgo -untilItFails` over 50 times before I gave up
CC @droot @DirectXMan12
> Refactor metrics tests

- pkg/webhook/internal/cert/writer/certwriter.go
> Fix typos: wehbook -> webhook

- pkg/cache/cache_test.go
- pkg/cache/internal/cache_reader.go
> Set GVK when getting the object from the cache.

- .github/pull_request_template.md
- RELEASE.md
- VERSIONING.md
- hack/release/common.sh
- hack/release/release-notes.sh
Reads through the current branch, grabbing merge commits and turning
them into fancy release notes.
Also updates the VERSIONING.md doc with simplifications to the process.
> :running: Release notes script

- pkg/webhook/internal/cert/provisioner.go
- pkg/webhook/internal/cert/provisioner_test.go
> :bug: gen cert for the server even there are no webhooks

- pkg/reconcile/reconcile.go
> 📖 Make reconcile.Request requeue behavior less ambiguous

- pkg/client/interfaces.go
> :docs: Clarify IndexerFunc comment with namespaced objects

- pkg/builder/build.go
Cherrypick #331 to release-0.1 branch
> :bug: try manager's config before kubeconfig

- pkg/client/client_test.go
fixes #345 
Leftover debug statements made it into the test.
> :bug: remove fmt.Printf statements that made it in a merge.

- pkg/client/typed_client.go
Cherry Pick of #425 in the release-0.1 branch.
@DirectXMan12
> :bug: List requests should not pass a body.

- CONTRIBUTING.md
Update contributing docs to use golangci instead of gometalinter
> 📖 (:book:, docs) Update contributing.md to use golangci-lint

- VERSIONING.md
> :book: Fix links in VERSIONING.md

- pkg/log/zap/zap.go
> :bug: Fix comments for option in zap

- OWNERS
I believe that I can add value as a reviewer to the controller runtime repo.
/cc @DirectXMan12
> :running: Add shawn-hurley as reviewer

- OWNERS
- OWNERS_ALIASES
Adding myself as reviewer
/assign @DirectXMan12
> :running: Add alvaroaleman as reviewer

- OWNERS_ALIASES
I have participated in several PRs now, tested out dependencies, and am active in supporting users in #kubebuilder and #kubernetes-operators. Like the others and as a fellow consumer of controller-runtime that is critical to our project, I'd love to help review!
> Add gerred as reviewer

- OWNERS_ALIASES
> :running: Add joelanford as reviewer

- pkg/predicate/predicate.go
Simplify the `if` statement with single `return`.
> :running: Minor nit in predicates

- go.mod
- go.sum
Updating dependencies to the latest versions
> 🏃 Update ginkgo@1.11.0 and gomega@1.8.1

- OWNERS_ALIASES
I did couple of reviews already and I am working on #563
> Add 'alenkacz' as reviewer

- OWNERS_ALIASES
> :running: Add vincepri to reviewers

- README.md
Travis support was removed in #593
> 🏃 (:running:, other) Remove travis badge from readme

- doc.go
Adds documentation to cover discussion seen in #343
> 📖: Add note about split client cache inconsistency

- OWNERS_ALIASES
> Add shawn-hurley to approvers

- README.md
Those coming across controller-runtime because they want to write their
own controller may really want to use kubebuilder to get started.
Fixes #820
> 📖 reference kubebuilder in README

- pkg/reconcile/reconcile.go
> 📖 Fix a minor typo in the Reconciler docs

- OWNERS_ALIASES
I've been around the kubebuilder project as a whole for a while now, and I'd love to officially become a reviewer // continue getting deeper as a contributor. Between the three projects I spend the vast majority of my time these days in controller runtime, so I opened the PR here 🙂 
I've submitted 7 PRs to controller-runtime and 20 to the trio of kubebuilder projects total [[link]](https://github.com/search?p=2&q=author%3Aalexeldeib+repo%3Akubernetes-sigs%2Fkubebuilder+repo%3Akubernetes-sigs%2Fcontroller-runtime+repo%3Akubernetes-sigs%2Fcontroller-tools&type=Commits), plus reviews and discussion in many issues (I couldn't count easily).  I'm always hanging out in slack helping users and make as many of the community meetings as I can. I like to think I have a decent grasp on most of the …
>  🏃 add alexeldeib as a reviewer

- pkg/client/config/config.go
- pkg/client/interfaces.go
- pkg/client/options.go
- pkg/client/options_test.go
- pkg/controller/controllerutil/controllerutil.go
- pkg/controller/controllerutil/controllerutil_test.go
- pkg/envtest/crd.go
- pkg/envtest/envtest_test.go
- pkg/envtest/helper.go
- pkg/envtest/testdata/webhooks/manifests.yaml
- pkg/envtest/webhook.go
- pkg/envtest/webhook_test.go
- pkg/log/zap/kube_helpers.go
- pkg/log/zap/zap_test.go
> Backports for v0.5.3

- pkg/client/example_test.go
Signed-off-by: knight42 <anonymousknight96@gmail.com>
This PR corrects the example of `client.Create` and provides an example of `client.Patch`
> 📖 provide example of client.Patch

- examples/builtins/controller.go
- go.mod
- pkg/client/client_test.go
- pkg/client/example_test.go
- pkg/client/fake/client.go
- pkg/client/fake/client_test.go
- pkg/client/patch.go
- pkg/controller/controller.go
- pkg/controller/controllerutil/controllerutil.go
- pkg/controller/controllerutil/controllerutil_test.go
- pkg/envtest/server.go
- pkg/internal/controller/controller.go
- pkg/internal/controller/controller_test.go
- pkg/manager/manager.go
- pkg/source/source.go
- pkg/source/source_test.go
- pkg/webhook/internal/certwatcher/certwatcher.go
> Prepare for v0.6.1

- OWNERS_ALIASES
Makes alvaroaleman approver
I am:
* Actively using the project since 2018
* Actively contributing since 2018: https://github.com/kubernetes-sigs/controller-runtime/pulls?q=is%3Apr+author%3Aalvaroaleman+is%3Aclosed+sort%3Acreated-asc
* Reviewing since 2019: https://github.com/kubernetes-sigs/controller-runtime/pulls?q=is%3Apr+-author%3Aalvaroaleman+is%3Aclosed+sort%3Acreated-asc+commenter%3Aalvaroaleman+
* An official reviewer since 2019: b33d735bc32726b4aff7c23d372322458a343b83
* Actively helping with issues: https://github.com/kubernetes-sigs/controller-runtime/issues?q=is%3Aissue+-author%3Aalvaroaleman+sort%3Acreated-asc+commenter%3Aalvaroaleman+
/assign @DirectXMan12 @vincepri
> :running: Make alvaroaleman approver

- pkg/predicate/predicate.go
- pkg/predicate/predicate_test.go
> ✨ Implement NewPredicateFuncs to create predicate functions from a filter function

- pkg/envtest/server.go
> ✨ Fix typo in envtest.Environment struct

- pkg/client/client.go
- pkg/client/client_test.go
- pkg/client/dryrun.go
- pkg/client/example_test.go
- pkg/client/fake/client.go
- pkg/client/interfaces.go
- pkg/client/split.go
- pkg/manager/manager.go
- pkg/runtime/inject/inject_test.go
> ⚠ Expose Client runtime.Scheme

- go.mod
- go.sum
> 🌱 [0.5] Update json-patch to v4.9.0

- go.mod
- go.sum
> :seedling: Update json-patch to v4.9.0

- pkg/scheme/scheme.go
update Builder.Register() 's comment - one or more
📖
> update Builder.Register() 's comment - one or more

- go.mod
- hack/tools/go.mod
> :seedling: Update Go mod version to 1.15

- pkg/controller/controller.go
When I read the controller.go file, I found this step is duplicated with https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/controller/controller.go#L99-L101. Thus I create a PR to remove it.
> 🌱 Remove duplicate lines in controller.go

- go.mod
- go.sum
- pkg/log/log.go
Signed-off-by: Arghya Sadhu <arghya88@gmail.com>
Fixes #1275
> 🌱Use go-logr context functions

- pkg/log/log.go
Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>
> 📖: Fix IntoContext() documentation

- pkg/internal/testing/integration/internal/integration_tests/etcd_integration_test.go
- pkg/webhook/server_test.go
> 🌱: testing: Cleanup temporary files

- pkg/cluster/cluster.go
- pkg/internal/controller/controller.go
- pkg/manager/internal.go
- pkg/runtime/inject/inject.go
> :sparkles: [release-0.8]Revert injection deprecation logging

- pkg/builder/controller.go
As the subject explains.
The references to `ControllerManagedBy` there seemed like a refactoring that went too far :-)
> 📖  Fix doc strings for Complete() and Build().

- pkg/envtest/crd.go
> :seedling: Handle unstructured CRD objects in envtest webhook mods

- go.mod
- go.sum
Signed-off-by: Tamal Saha <tamal@appscode.com>
ref: https://github.com/gomodules/jsonpatch/pull/29
> 🌱 Use gomodules.xyz/jsonpatch/v2 v2.2.0

- OWNERS_ALIASES
- SECURITY_CONTACTS
As per
https://groups.google.com/g/kubebuilder/c/-5hOFa_adr4/m/Sp_Zb755AwAJ
> :seedling: Move directxman12 to approvers-emeritus

- OWNERS_ALIASES
Add myself as reviewer
Contributions:
PRs created: https://github.com/kubernetes-sigs/controller-runtime/pulls?q=+is%3Apr+author%3Avarshaprasad96
Issues involved with: https://github.com/kubernetes-sigs/controller-runtime/issues?q=is%3Aissue+involves%3Avarshaprasad96
PRs reviewed: https://github.com/kubernetes-sigs/controller-runtime/pulls?q=is%3Apr+reviewed-by%3Avarshaprasad96+-author%3Avarshaprasad96
Signed-off-by: varshaprasad96 <varshaprasad96@gmail.com>
> :running: Add varshaprasad96 as reviewer

- pkg/webhook/server.go
My previous PR #1598 introduced a health check for the webhooks. The health check works as intended (it reports healthy when the webhook server was up), but it also produces tls handshake timeout errors and thus a lot of log messages like:
```bash
TLS handshake error from 127.0.0.1:42498: EOF
```
xref: https://kubernetes.slack.com/archives/CD6U2V71N/p1627643594012600
>  🐛   0.9: fix webhook health check tls handshake timeout errors

- OWNERS_ALIASES
Moves me (@joelanford) from approvers to maintainers to improve coverage for maintainer-requiring tasks, e.g. making releases.
> :seedling: OWNERS_ALIASES: move joelanford to maintainers

- pkg/internal/testing/process/process.go
Fix a small typo in the comment: wether --> whether
Signed-off-by: Hu Shuai <hus.fnst@fujitsu.com>
> 📖 Fix a small typo

- OWNERS_ALIASES
I have actively worked in controller-runtime for a long time (a year or more). I would like to be a reviewer and maybe an approver in the future :)
- PRs authored:
- https://github.com/kubernetes-sigs/controller-runtime/pull/1149
- https://github.com/kubernetes-sigs/controller-runtime/pull/1274
- https://github.com/kubernetes-sigs/controller-runtime/pull/1627
- https://github.com/kubernetes-sigs/controller-runtime/pull/1651
- https://github.com/kubernetes-sigs/controller-runtime/pull/1703
- PRs reviewed and issues responded to:
- https://github.com/kubernetes-sigs/controller-runtime/pull/1279
- https://github.com/kubernetes-sigs/controller-runtime/pull/1519
- https://github.com/kubernetes-sigs/controller-runtime/pull/1570
- …
> 🌱 Add FillZpp as a reviewer

- pkg/internal/testing/controlplane/etcd.go
> :book: Fix a typo

- designs/README.md
Fix issues with format, wording and some grammar.
This is needed to remove ambiguity and make the design docs clear
for new developers starting with this project.
>  :book: docs Update design readme

- pkg/log/zap/kube_helpers.go
- pkg/log/zap/zap_test.go
If object is nil, this func will panic.
Co-authored-by: Marty Spiewak <mspiewak@vmware.com>
> 🐛  Check to see if obj is nil so there is no panic trying to get the gvk

- pkg/internal/controller/controller.go
Details in #1793
Fixes #1793
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5709
> 🌱 log panic in reconcile even if panic should not be recovered

- pkg/client/example_test.go
> :book: Fix examples typo

- pkg/source/source.go
Currently, `kind.Start` prints the last error from the polling process, except for the NoKindMatchError. 
This behavior makes it users hard to debug the cause (e.g. forgot to add types to the scheme) of the `getInformer` call failure since it always returns the context timeout error, which is the last error while polling.
This commit logs all returned errors while calling `getInformer` in the polling process.
Signed-off-by: Sunghoon Kang <hoon@linecorp.com>
> 🌱 Log all errors from cache.GetInformer call

- .golangci.yml
> 🌱 Bump linters to Go 1.18

- .github/workflows/verify.yml
Just to keep it up-to-date.
See: https://github.com/kubernetes-sigs/kubebuilder-release-tools/releases/tag/v0.2.0
> 🌱 Bump kubebuilder-release-tools to v0.2.0

- OWNERS_ALIASES
Hey folks,
I would like to volunteer as a reviewer, some previous work on CR:
* [PRs created](https://github.com/kubernetes-sigs/controller-runtime/pulls?q=+is%3Apr+author%3Asbueringer)
* [Issues involved with](https://github.com/kubernetes-sigs/controller-runtime/issues?q=is%3Aissue+involves%3Asbueringer)
* [PRs reviewed](https://github.com/kubernetes-sigs/controller-runtime/pulls?q=is%3Apr+reviewed-by%3Asbueringer+-author%3Asbueringer)
> 🌱 Add sbueringer as reviewer

- OWNERS_ALIASES
Otherwise ppl will ask them to review their changes without any realistic chance of that happening.
/assign @vincepri @joelanford 
/cc @gerred @shawn-hurley @alenkacz  @alexeldeib
> :running: Clean up OWNERS who haven't been active in the last year

- .github/workflows/verify.yml
> 🌱 Bump kubebuilder-release-tools to v0.3.0

- pkg/config/v1alpha1/types.go
> :book: Fix typo in ComponentConfig Godoc

- OWNERS_ALIASES
I would like to become a reviewer (was proposed by @vincepri).
> 📖 Add inteon to reviewers

- .github/workflows/golangci-lint.yml
- .golangci.yml
> 🌱 Bump golangci-lint to v1.51.1

- pkg/client/fake/client.go
Fix a typo in a godoc comment
recocnized -> recognized
> 📖  Fix a typo in a godoc comment

- .github/workflows/golangci-lint.yml
- Makefile
> 🐛 Use Go 1.19 in golangci-lint action

- .github/workflows/golangci-lint.yml
- .golangci.yml
- pkg/predicate/predicate_test.go
> :seedling: Update golangci-lint to v1.52.1

- examples/builtins/mutatingwebhook.go
- examples/builtins/validatingwebhook.go
> :seedling: update builtin webhook paths

- OWNERS_ALIASES
- SECURITY_CONTACTS
> :seedling: Update SECURITY_CONTACTS and maintainer list

- pkg/log/deleg.go
- pkg/log/log_test.go
> :bug: SetLogger should work with nil sinks

- pkg/webhook/admission/http.go
- pkg/webhook/authentication/http.go
Replaces function-wide variable assignment with more local variable assignment.
Removes unnecessary intermediate variables.
> ✨ Cleanup webhook variable assignment

- pkg/cache/cache.go
> :book: Tiny comment fix.

- .github/workflows/ossf-scorecard.yaml
> :seedling: Add OSSF scorecard action

- OWNERS
- pkg/envtest/komega/OWNERS
- pkg/internal/testing/OWNERS
> 🌱 Cleanup owners files

- pkg/cache/internal/cache_reader.go
fix typo of CacheReader comment
> 🌱 fix: typo of CacheReader comment

- pkg/source/source.go
- pkg/source/source_test.go
> 🌱 Fix typo in channel option

- pkg/controller/controller_integration_test.go
Add a test for dynamically adding a watcher for the controller.
> :sparkles: Add dynamic watcher tests

- README.md
> 📖 Document compatibility with k8s.io/*, client-go and Go

- .github/workflows/verify.yml
> 🌱 Fix PR verify action

- pkg/client/interfaces.go
This commit fixes a minor typo in IndexField docs.
> 📖  (fix): typo in IndexField method docs

- pkg/leaderelection/leader_election.go
- pkg/manager/manager.go
- pkg/manager/manager_test.go
> :bug: Fix RenewDeadline typo in leader election

- examples/scratch-env/go.mod
- examples/scratch-env/go.sum
- go.mod
- pkg/certwatcher/certwatcher.go
- pkg/certwatcher/certwatcher_test.go
> [release-0.19] 🌱 Add fsnotify watcher+polling

- examples/scratch-env/go.mod
- examples/scratch-env/go.sum
- go.mod
- pkg/certwatcher/certwatcher.go
- pkg/certwatcher/certwatcher_test.go
Cherry-pick of https://github.com/kubernetes-sigs/controller-runtime/pull/3050
> [release-0.18] 🌱 Add fsnotify watcher+polling

- OWNERS_ALIASES
I've been following and using this project for a long time, reviewing various PRs and adding various features over the years, providing feedback on issues etc.
I would like to start helping with the PR reviews as well, so adding myself as a reviewer to start getting pings for help.
> 🌱 Add JoelSpeed to reviewers

- OWNERS_ALIASES
Over the last couple of years, I have been contributing to this project with PRs, triaging issues, reviewing PRs and am a long-term user of this project.  Active in k8s as a whole and wanted to start reviewing PRs as a reviewer.  
/assign @sbueringer
> 🌱Add troy0820 to reviewers

- tools/setup-envtest/version/version.go
Follow up to https://github.com/kubernetes-sigs/controller-runtime/pull/3166
/hold 
/assign @sbueringer
> 🐛 Fix Godoc for version.Version in setupenvtest

- .github/workflows/golangci-lint.yml
> 🌱chore: Update golangci-lint version to v2.3.0

- pkg/builder/controller_test.go
> 🌱 Fix typo in unit test name
